import type { TriggerMeta } from "./automation-trigger-types";

export const SUPPORT_TRIGGER_META: TriggerMeta[] = [
  {
    value: "ticket.created",
    label: "Support ticket created",
    description: "Runs when a new support ticket is opened",
    module: "support",
    fields: [
      { value: "subject", label: "Subject" },
      { value: "priority", label: "Priority (LOW, HIGH, URGENT)" },
      { value: "status", label: "Status" },
      { value: "requesterEmail", label: "Requester email" },
    ],
    samplePayload: {
      id: 1,
      subject: "Cannot log in",
      priority: "URGENT",
      status: "OPEN",
      requesterEmail: "user@customer.com",
    },
  },
  {
    value: "ticket.priority_changed",
    label: "Ticket priority changed",
    description: "Runs when a support ticket's priority is updated",
    module: "support",
    fields: [
      { value: "priority", label: "New priority" },
      { value: "previousPriority", label: "Previous priority" },
      { value: "status", label: "Status" },
    ],
    samplePayload: {
      id: 1,
      priority: "URGENT",
      previousPriority: "MEDIUM",
      status: "OPEN",
    },
  },
  {
    value: "ticket.message_received",
    label: "Ticket message received",
    description: "Runs when a new message is posted on a support ticket",
    module: "support",
    fields: [
      { value: "isInternal", label: "Is internal note" },
      { value: "sourceChannel", label: "Source channel" },
      { value: "priority", label: "Ticket priority" },
    ],
    samplePayload: {
      ticketId: 1,
      isInternal: false,
      sourceChannel: "email",
      priority: "HIGH",
    },
  },
  {
    value: "ticket.assigned",
    label: "Ticket assigned",
    description: "Runs when a support ticket is assigned to an agent",
    module: "support",
    fields: [
      { value: "title", label: "Title" },
      { value: "assigneeId", label: "Assignee ID" },
      { value: "priority", label: "Priority" },
      { value: "status", label: "Status" },
    ],
    samplePayload: {
      ticketId: 1,
      title: "Cannot log in",
      status: "OPEN",
      priority: "URGENT",
      category: null,
      assigneeId: null,
    },
  },
  {
    value: "ticket.status_changed",
    label: "Ticket status changed",
    description: "Runs when a support ticket moves to a different status",
    module: "support",
    fields: [
      { value: "title", label: "Title" },
      { value: "status", label: "New status" },
      { value: "priority", label: "Priority" },
      { value: "category", label: "Category" },
    ],
    samplePayload: {
      ticketId: 1,
      title: "Cannot log in",
      status: "RESOLVED",
      priority: "URGENT",
      category: null,
      assigneeId: null,
    },
  },
  {
    value: "ticket.escalated",
    label: "Ticket escalated",
    description: "Runs when a support ticket is escalated",
    module: "support",
    fields: [
      { value: "title", label: "Title" },
      { value: "priority", label: "Priority" },
      { value: "status", label: "Status" },
    ],
    samplePayload: {
      ticketId: 1,
      title: "Cannot log in",
      status: "OPEN",
      priority: "URGENT",
      category: null,
      assigneeId: null,
    },
  },
  {
    value: "sla.breached",
    label: "SLA breached",
    description: "Runs when a service level target is missed",
    module: "support",
    fields: [],
    samplePayload: {},
  },
];
