import type { AutomationTrigger } from "@/hooks/api/automations";

export type TriggerModule = "crm" | "support" | "finance" | "hr";

export interface TriggerMeta {
  value: AutomationTrigger;
  label: string;
  description: string;
  module: TriggerModule;
  fields: { value: string; label: string }[];
  samplePayload: Record<string, unknown>;
}

export const TRIGGER_META: TriggerMeta[] = [
  {
    value: "lead.created",
    label: "Lead created",
    description: "Runs when a new lead is added to the CRM",
    module: "crm",
    fields: [
      { value: "name", label: "Lead name" },
      { value: "email", label: "Email" },
      { value: "source", label: "Source (referral, website, etc.)" },
      { value: "assignedToId", label: "Assigned rep ID" },
    ],
    samplePayload: {
      id: 1,
      name: "Acme Corp",
      email: "buyer@acme.com",
      source: "website",
      assignedToId: "",
    },
  },
  {
    value: "deal.stage_changed",
    label: "Deal stage changed",
    description: "Runs when a deal moves to a different stage",
    module: "crm",
    fields: [
      { value: "name", label: "Deal name" },
      { value: "value", label: "Deal value" },
      { value: "stage", label: "New stage (WON, NEGOTIATION, etc.)" },
      { value: "previousStage", label: "Previous stage" },
      { value: "assignedToId", label: "Assigned rep ID" },
    ],
    samplePayload: {
      id: 1,
      name: "Enterprise renewal",
      value: "50000",
      stage: "WON",
      previousStage: "NEGOTIATION",
      assignedToId: "",
    },
  },
  {
    value: "ticket.created",
    label: "Support ticket created",
    description: "Runs when a new support ticket is opened",
    module: "support",
    fields: [
      { value: "subject", label: "Subject" },
      { value: "priority", label: "Priority (LOW, HIGH, URGENT)" },
      { value: "status", label: "Status" },
      { value: "requesterEmail", label: "Requester email" },
    ],
    samplePayload: {
      id: 1,
      subject: "Cannot log in",
      priority: "URGENT",
      status: "OPEN",
      requesterEmail: "user@customer.com",
    },
  },
  {
    value: "ticket.priority_changed",
    label: "Ticket priority changed",
    description: "Runs when a support ticket's priority is updated",
    module: "support",
    fields: [
      { value: "priority", label: "New priority" },
      { value: "previousPriority", label: "Previous priority" },
      { value: "status", label: "Status" },
    ],
    samplePayload: {
      id: 1,
      priority: "URGENT",
      previousPriority: "MEDIUM",
      status: "OPEN",
    },
  },
  {
    value: "ticket.message_received",
    label: "Ticket message received",
    description: "Runs when a new message is posted on a support ticket",
    module: "support",
    fields: [
      { value: "isInternal", label: "Is internal note" },
      { value: "sourceChannel", label: "Source channel" },
      { value: "priority", label: "Ticket priority" },
    ],
    samplePayload: {
      ticketId: 1,
      isInternal: false,
      sourceChannel: "email",
      priority: "HIGH",
    },
  },
  {
    value: "invoice.overdue",
    label: "Invoice overdue",
    description: "Runs when an invoice passes its due date unpaid",
    module: "finance",
    fields: [
      { value: "number", label: "Invoice number" },
      { value: "amount", label: "Amount due" },
      { value: "daysOverdue", label: "Days overdue" },
      { value: "clientEmail", label: "Client email" },
    ],
    samplePayload: {
      id: 1,
      number: "INV-1024",
      amount: "12000",
      daysOverdue: 7,
      clientEmail: "ap@client.com",
    },
  },
  {
    value: "candidate.application_created",
    label: "Candidate applied",
    description: "Runs when a new candidate application is submitted",
    module: "hr",
    fields: [
      { value: "source", label: "Application source" },
      { value: "jobTitle", label: "Job title" },
      { value: "jobPostingId", label: "Job posting ID" },
    ],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobPostingId: 42,
      jobTitle: "Senior Engineer",
      source: "LINKEDIN",
      appliedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "candidate.stage_changed",
    label: "Candidate stage changed",
    description: "Runs when a candidate moves to a different stage",
    module: "hr",
    fields: [
      { value: "newStatus", label: "New stage" },
      { value: "previousStatus", label: "Previous stage" },
    ],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      previousStatus: "INTERVIEW",
      newStatus: "OFFER",
    },
  },
  {
    value: "interview.scheduled",
    label: "Interview scheduled",
    description: "Runs when a new interview is scheduled for a candidate",
    module: "hr",
    fields: [
      { value: "type", label: "Interview type" },
      { value: "durationMinutes", label: "Duration (minutes)" },
    ],
    samplePayload: {
      interviewId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      interviewerId: "",
      interviewerEmail: "interviewer@company.com",
      type: "VIDEO",
      scheduledAt: "2026-06-21T14:00:00Z",
      durationMinutes: 60,
      meetingLink: "https://meet.google.com/abc-defg",
    },
  },
  {
    value: "interview.completed",
    label: "Interview completed",
    description: "Runs when an interview result is recorded",
    module: "hr",
    fields: [
      { value: "result", label: "Result (PASS, FAIL, HOLD, NO_SHOW)" },
      { value: "rating", label: "Rating (1–5)" },
    ],
    samplePayload: {
      interviewId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      jobTitle: "Senior Engineer",
      result: "PASS",
      rating: 4,
      interviewerId: "",
      completedAt: "2026-06-21T15:00:00Z",
    },
  },
  {
    value: "scorecard.submitted",
    label: "Scorecard submitted",
    description: "Runs when an interviewer submits an evaluation scorecard",
    module: "hr",
    fields: [{ value: "recommendation", label: "Recommendation" }],
    samplePayload: {
      interviewId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      interviewerName: "Alex Johnson",
      recommendation: "HIRE",
      submittedAt: "2026-06-21T15:30:00Z",
    },
  },
  {
    value: "offer.sent",
    label: "Offer sent",
    description: "Runs when a job offer is dispatched to a candidate",
    module: "hr",
    fields: [],
    samplePayload: {
      offerId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      offeredSalary: "120000",
      joiningDate: "2026-07-01",
      validUntil: "2026-06-28",
      sentAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "offer.accepted",
    label: "Offer accepted",
    description: "Runs when a candidate accepts a job offer",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      offerId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      decision: "ACCEPTED",
      respondedAt: "2026-06-21T11:00:00Z",
    },
  },
  {
    value: "offer.rejected",
    label: "Offer declined",
    description: "Runs when a candidate declines a job offer",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      offerId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      decision: "REJECTED",
      respondedAt: "2026-06-21T11:00:00Z",
    },
  },
  {
    value: "candidate.bgv_status_changed",
    label: "BGV status changed",
    description:
      "Runs when a candidate's background verification status changes",
    module: "hr",
    fields: [{ value: "newBgvStatus", label: "New BGV status" }],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      previousBgvStatus: "INITIATED",
      newBgvStatus: "CLEARED",
      bgvAgency: "VerifyPro",
    },
  },
  {
    value: "sla.breached",
    label: "Recruitment SLA breached",
    description:
      "Runs when a candidate has been in a stage beyond the allowed time",
    module: "hr",
    fields: [
      { value: "stage", label: "Stage" },
      { value: "hoursInStage", label: "Hours in stage" },
    ],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      stage: "INTERVIEW",
      enteredAt: "2026-06-18T10:00:00Z",
      breachedAt: "2026-06-21T10:00:00Z",
      hoursInStage: 72,
    },
  },
  {
    value: "onboarding.started",
    label: "Onboarding started",
    description: "Runs when a new hire's onboarding process begins",
    module: "hr",
    fields: [],
    samplePayload: {
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      departmentId: 3,
      joiningDate: "2026-07-01",
      startedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "onboarding.task_overdue",
    label: "Onboarding task overdue",
    description:
      "Runs when an onboarding task passes its due date without completion",
    module: "hr",
    fields: [
      { value: "ownerRole", label: "Task owner role" },
      { value: "daysOverdue", label: "Days overdue" },
    ],
    samplePayload: {
      taskId: 1,
      taskTitle: "Submit bank details",
      userId: "",
      employeeName: "Jane Smith",
      ownerRole: "NEW_HIRE",
      dueDate: "2026-06-20",
      daysOverdue: 1,
    },
  },
  {
    value: "onboarding.document_submitted",
    label: "Onboarding document submitted",
    description: "Runs when a new hire uploads a required onboarding document",
    module: "hr",
    fields: [],
    samplePayload: {
      documentId: 1,
      userId: "",
      employeeName: "Jane Smith",
      documentTypeName: "PAN Card",
      status: "SUBMITTED",
      submittedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "onboarding.completed",
    label: "Onboarding completed",
    description: "Runs when all onboarding tasks for an employee are completed",
    module: "hr",
    fields: [],
    samplePayload: {
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      completedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "leave.requested",
    label: "Leave requested",
    description: "Runs when an employee submits a leave request",
    module: "hr",
    fields: [
      { value: "leaveType", label: "Leave type" },
      { value: "totalDays", label: "Total days" },
      { value: "priority", label: "Priority (LOW, MEDIUM, HIGH)" },
    ],
    samplePayload: {
      leaveRequestId: 1,
      userId: "",
      employeeName: "Jane Smith",
      leaveType: "Annual Leave",
      startDate: "2026-07-01",
      endDate: "2026-07-05",
      totalDays: 5,
      reason: "Family vacation",
      priority: "MEDIUM",
    },
  },
  {
    value: "leave.approved",
    label: "Leave approved",
    description: "Runs when a leave request is approved",
    module: "hr",
    fields: [
      { value: "decision", label: "Decision" },
      { value: "leaveType", label: "Leave type" },
    ],
    samplePayload: {
      leaveRequestId: 1,
      userId: "",
      employeeEmail: "jane@company.com",
      employeeName: "Jane Smith",
      leaveType: "Annual Leave",
      startDate: "2026-07-01",
      endDate: "2026-07-05",
      decision: "APPROVED",
      approverId: "",
      rejectionReason: null,
      decidedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "leave.rejected",
    label: "Leave rejected",
    description: "Runs when a leave request is rejected",
    module: "hr",
    fields: [
      { value: "decision", label: "Decision" },
      { value: "leaveType", label: "Leave type" },
    ],
    samplePayload: {
      leaveRequestId: 1,
      userId: "",
      employeeEmail: "jane@company.com",
      employeeName: "Jane Smith",
      leaveType: "Annual Leave",
      startDate: "2026-07-01",
      endDate: "2026-07-05",
      decision: "REJECTED",
      approverId: "",
      rejectionReason: "Team is short-staffed",
      decidedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "attendance.anomaly",
    label: "Attendance anomaly",
    description:
      "Runs when an employee has missed check-ins beyond a threshold",
    module: "hr",
    fields: [{ value: "missedDays", label: "Missed days" }],
    samplePayload: {
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      missedDays: 3,
      weekOf: "2026-06-15",
    },
  },
  {
    value: "resignation.submitted",
    label: "Resignation submitted",
    description: "Runs when an employee submits their resignation",
    module: "hr",
    fields: [],
    samplePayload: {
      resignationId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      lastWorkingDate: "2026-07-21",
      noticePeriodDays: 30,
      reasonCategory: "BETTER_OPPORTUNITY",
      submittedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "resignation.approved",
    label: "Resignation approved",
    description: "Runs when a resignation is formally approved",
    module: "hr",
    fields: [],
    samplePayload: {
      resignationId: 1,
      userId: "",
      employeeName: "Jane Smith",
      lastWorkingDate: "2026-07-21",
      approvedBy: "",
      approvedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "employee.terminated",
    label: "Employee terminated",
    description: "Runs when an employee termination is executed",
    module: "hr",
    fields: [],
    samplePayload: {
      terminationId: 1,
      userId: "",
      employeeName: "John Doe",
      effectiveDate: "2026-06-21",
      reasons: ["Performance issues"],
      noticePeriodWaived: false,
    },
  },
  {
    value: "certification.expiring",
    label: "Certification expiring",
    description:
      "Runs when an employee certification is within 30 days of expiry",
    module: "hr",
    fields: [{ value: "daysUntilExpiry", label: "Days until expiry" }],
    samplePayload: {
      certificationId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      certificationName: "AWS Solutions Architect",
      issuingOrganization: "Amazon",
      expiryDate: "2026-07-21",
      daysUntilExpiry: 30,
    },
  },
  {
    value: "document.review_requested",
    label: "Document review requested",
    description: "Runs when a document is submitted for review",
    module: "hr",
    fields: [],
    samplePayload: {
      documentId: 1,
      documentTitle: "Employee Handbook v2",
      requesterId: "",
      requesterName: "HR Manager",
      reviewerIds: [],
      dueDate: "2026-06-28",
    },
  },
  {
    value: "performance.review_cycle_started",
    label: "Performance review cycle started",
    description: "Runs when a new performance review cycle is kicked off",
    module: "hr",
    fields: [],
    samplePayload: {
      cycleId: 1,
      cycleName: "Q2 2026 Review",
      startDate: "2026-06-21",
      endDate: "2026-07-21",
      reviewerCount: 12,
    },
  },
  {
    value: "expense.submitted",
    label: "Expense submitted",
    description: "Runs when an employee submits a new expense claim",
    module: "hr",
    fields: [],
    samplePayload: {
      expenseId: 1,
      userId: "",
      employeeName: "Jane Smith",
      amount: "2500",
      category: "Travel",
      submittedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "reimbursement.approved",
    label: "Reimbursement approved",
    description: "Runs when a reimbursement request is approved",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      reimbursementId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      amount: "2500",
      decision: "APPROVED",
    },
  },
  {
    value: "reimbursement.rejected",
    label: "Reimbursement rejected",
    description: "Runs when a reimbursement request is rejected",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      reimbursementId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      amount: "2500",
      decision: "REJECTED",
    },
  },
];

export const NON_CRM_TRIGGER_META = TRIGGER_META.filter((t) => t.module !== "crm");

export function getModuleForTrigger(
  trigger: AutomationTrigger,
): TriggerModule {
  const entry = TRIGGER_META.find((t) => t.value === trigger);
  return entry?.module ?? "hr";
}

export function getTriggerMeta(trigger: AutomationTrigger): TriggerMeta {
  return TRIGGER_META.find((t) => t.value === trigger) ?? TRIGGER_META[0];
}
