import type { TriggerMeta } from "./automation-trigger-types";

export const HR_RECRUITMENT_TRIGGER_META: TriggerMeta[] = [
  {
    value: "candidate.application_created",
    label: "Candidate applied",
    description: "Runs when a new candidate application is submitted",
    module: "hr",
    fields: [
      { value: "source", label: "Application source" },
      { value: "jobTitle", label: "Job title" },
      { value: "jobPostingId", label: "Job posting ID" },
    ],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobPostingId: 42,
      jobTitle: "Senior Engineer",
      source: "LINKEDIN",
      appliedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "candidate.stage_changed",
    label: "Candidate stage changed",
    description: "Runs when a candidate moves to a different stage",
    module: "hr",
    fields: [
      { value: "newStatus", label: "New stage" },
      { value: "previousStatus", label: "Previous stage" },
    ],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      previousStatus: "INTERVIEW",
      newStatus: "OFFER",
    },
  },
  {
    value: "interview.scheduled",
    label: "Interview scheduled",
    description: "Runs when a new interview is scheduled for a candidate",
    module: "hr",
    fields: [
      { value: "type", label: "Interview type" },
      { value: "durationMinutes", label: "Duration (minutes)" },
    ],
    samplePayload: {
      interviewId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      interviewerId: "",
      interviewerEmail: "interviewer@company.com",
      type: "VIDEO",
      scheduledAt: "2026-06-21T14:00:00Z",
      durationMinutes: 60,
      meetingLink: "https://meet.google.com/abc-defg",
    },
  },
  {
    value: "interview.completed",
    label: "Interview completed",
    description: "Runs when an interview result is recorded",
    module: "hr",
    fields: [
      { value: "result", label: "Result (PASS, FAIL, HOLD, NO_SHOW)" },
      { value: "rating", label: "Rating (1–5)" },
    ],
    samplePayload: {
      interviewId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      jobTitle: "Senior Engineer",
      result: "PASS",
      rating: 4,
      interviewerId: "",
      completedAt: "2026-06-21T15:00:00Z",
    },
  },
  {
    value: "scorecard.submitted",
    label: "Scorecard submitted",
    description: "Runs when an interviewer submits an evaluation scorecard",
    module: "hr",
    fields: [{ value: "recommendation", label: "Recommendation" }],
    samplePayload: {
      interviewId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      interviewerName: "Alex Johnson",
      recommendation: "HIRE",
      submittedAt: "2026-06-21T15:30:00Z",
    },
  },
  {
    value: "offer.sent",
    label: "Offer sent",
    description: "Runs when a job offer is dispatched to a candidate",
    module: "hr",
    fields: [],
    samplePayload: {
      offerId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      offeredSalary: "120000",
      joiningDate: "2026-07-01",
      validUntil: "2026-06-28",
      sentAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "offer.accepted",
    label: "Offer accepted",
    description: "Runs when a candidate accepts a job offer",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      offerId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      decision: "ACCEPTED",
      respondedAt: "2026-06-21T11:00:00Z",
    },
  },
  {
    value: "offer.rejected",
    label: "Offer declined",
    description: "Runs when a candidate declines a job offer",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      offerId: 1,
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      jobTitle: "Senior Engineer",
      decision: "REJECTED",
      respondedAt: "2026-06-21T11:00:00Z",
    },
  },
  {
    value: "candidate.bgv_status_changed",
    label: "BGV status changed",
    description: "Runs when a candidate's background verification status changes",
    module: "hr",
    fields: [{ value: "newBgvStatus", label: "New BGV status" }],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      candidateEmail: "jane@example.com",
      previousBgvStatus: "INITIATED",
      newBgvStatus: "CLEARED",
      bgvAgency: "VerifyPro",
    },
  },
  {
    value: "sla.breached",
    label: "Recruitment SLA breached",
    description: "Runs when a candidate has been in a stage beyond the allowed time",
    module: "hr",
    fields: [
      { value: "stage", label: "Stage" },
      { value: "hoursInStage", label: "Hours in stage" },
    ],
    samplePayload: {
      candidateId: 1,
      candidateName: "Jane Smith",
      stage: "INTERVIEW",
      enteredAt: "2026-06-18T10:00:00Z",
      breachedAt: "2026-06-21T10:00:00Z",
      hoursInStage: 72,
    },
  },
];
