import type { TriggerMeta } from "./automation-trigger-types";

export const HR_EMPLOYEE_TRIGGER_META: TriggerMeta[] = [
  {
    value: "onboarding.started",
    label: "Onboarding started",
    description: "Runs when a new hire's onboarding process begins",
    module: "hr",
    fields: [],
    samplePayload: {
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      departmentId: 3,
      joiningDate: "2026-07-01",
      startedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "onboarding.task_overdue",
    label: "Onboarding task overdue",
    description: "Runs when an onboarding task passes its due date without completion",
    module: "hr",
    fields: [
      { value: "ownerRole", label: "Task owner role" },
      { value: "daysOverdue", label: "Days overdue" },
    ],
    samplePayload: {
      taskId: 1,
      taskTitle: "Submit bank details",
      userId: "",
      employeeName: "Jane Smith",
      ownerRole: "NEW_HIRE",
      dueDate: "2026-06-20",
      daysOverdue: 1,
    },
  },
  {
    value: "onboarding.document_submitted",
    label: "Onboarding document submitted",
    description: "Runs when a new hire uploads a required onboarding document",
    module: "hr",
    fields: [],
    samplePayload: {
      documentId: 1,
      userId: "",
      employeeName: "Jane Smith",
      documentTypeName: "PAN Card",
      status: "SUBMITTED",
      submittedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "onboarding.completed",
    label: "Onboarding completed",
    description: "Runs when all onboarding tasks for an employee are completed",
    module: "hr",
    fields: [],
    samplePayload: {
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      completedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "leave.requested",
    label: "Leave requested",
    description: "Runs when an employee submits a leave request",
    module: "hr",
    fields: [
      { value: "leaveType", label: "Leave type" },
      { value: "totalDays", label: "Total days" },
      { value: "priority", label: "Priority (LOW, MEDIUM, HIGH)" },
    ],
    samplePayload: {
      leaveRequestId: 1,
      userId: "",
      employeeName: "Jane Smith",
      leaveType: "Annual Leave",
      startDate: "2026-07-01",
      endDate: "2026-07-05",
      totalDays: 5,
      reason: "Family vacation",
      priority: "MEDIUM",
    },
  },
  {
    value: "leave.approved",
    label: "Leave approved",
    description: "Runs when a leave request is approved",
    module: "hr",
    fields: [
      { value: "decision", label: "Decision" },
      { value: "leaveType", label: "Leave type" },
    ],
    samplePayload: {
      leaveRequestId: 1,
      userId: "",
      employeeEmail: "jane@company.com",
      employeeName: "Jane Smith",
      leaveType: "Annual Leave",
      startDate: "2026-07-01",
      endDate: "2026-07-05",
      decision: "APPROVED",
      approverId: "",
      rejectionReason: null,
      decidedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "leave.rejected",
    label: "Leave rejected",
    description: "Runs when a leave request is rejected",
    module: "hr",
    fields: [
      { value: "decision", label: "Decision" },
      { value: "leaveType", label: "Leave type" },
    ],
    samplePayload: {
      leaveRequestId: 1,
      userId: "",
      employeeEmail: "jane@company.com",
      employeeName: "Jane Smith",
      leaveType: "Annual Leave",
      startDate: "2026-07-01",
      endDate: "2026-07-05",
      decision: "REJECTED",
      approverId: "",
      rejectionReason: "Team is short-staffed",
      decidedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "attendance.anomaly",
    label: "Attendance anomaly",
    description: "Runs when an employee has missed check-ins beyond a threshold",
    module: "hr",
    fields: [{ value: "missedDays", label: "Missed days" }],
    samplePayload: {
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      missedDays: 3,
      weekOf: "2026-06-15",
    },
  },
  {
    value: "resignation.submitted",
    label: "Resignation submitted",
    description: "Runs when an employee submits their resignation",
    module: "hr",
    fields: [],
    samplePayload: {
      resignationId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      lastWorkingDate: "2026-07-21",
      noticePeriodDays: 30,
      reasonCategory: "BETTER_OPPORTUNITY",
      submittedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "resignation.approved",
    label: "Resignation approved",
    description: "Runs when a resignation is formally approved",
    module: "hr",
    fields: [],
    samplePayload: {
      resignationId: 1,
      userId: "",
      employeeName: "Jane Smith",
      lastWorkingDate: "2026-07-21",
      approvedBy: "",
      approvedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "employee.terminated",
    label: "Employee terminated",
    description: "Runs when an employee termination is executed",
    module: "hr",
    fields: [],
    samplePayload: {
      terminationId: 1,
      userId: "",
      employeeName: "John Doe",
      effectiveDate: "2026-06-21",
      reasons: ["Performance issues"],
      noticePeriodWaived: false,
    },
  },
  {
    value: "certification.expiring",
    label: "Certification expiring",
    description: "Runs when an employee certification is within 30 days of expiry",
    module: "hr",
    fields: [{ value: "daysUntilExpiry", label: "Days until expiry" }],
    samplePayload: {
      certificationId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      certificationName: "AWS Solutions Architect",
      issuingOrganization: "Amazon",
      expiryDate: "2026-07-21",
      daysUntilExpiry: 30,
    },
  },
  {
    value: "document.review_requested",
    label: "Document review requested",
    description: "Runs when a document is submitted for review",
    module: "hr",
    fields: [],
    samplePayload: {
      documentId: 1,
      documentTitle: "Employee Handbook v2",
      requesterId: "",
      requesterName: "HR Manager",
      reviewerIds: [],
      dueDate: "2026-06-28",
    },
  },
  {
    value: "performance.review_cycle_started",
    label: "Performance review cycle started",
    description: "Runs when a new performance review cycle is kicked off",
    module: "hr",
    fields: [],
    samplePayload: {
      cycleId: 1,
      cycleName: "Q2 2026 Review",
      startDate: "2026-06-21",
      endDate: "2026-07-21",
      reviewerCount: 12,
    },
  },
  {
    value: "expense.submitted",
    label: "Expense submitted",
    description: "Runs when an employee submits a new expense claim",
    module: "hr",
    fields: [],
    samplePayload: {
      expenseId: 1,
      userId: "",
      employeeName: "Jane Smith",
      amount: "2500",
      category: "Travel",
      submittedAt: "2026-06-21T10:00:00Z",
    },
  },
  {
    value: "reimbursement.approved",
    label: "Reimbursement approved",
    description: "Runs when a reimbursement request is approved",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      reimbursementId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      amount: "2500",
      decision: "APPROVED",
    },
  },
  {
    value: "reimbursement.rejected",
    label: "Reimbursement rejected",
    description: "Runs when a reimbursement request is rejected",
    module: "hr",
    fields: [{ value: "decision", label: "Decision" }],
    samplePayload: {
      reimbursementId: 1,
      userId: "",
      employeeName: "Jane Smith",
      employeeEmail: "jane@company.com",
      amount: "2500",
      decision: "REJECTED",
    },
  },
];
