import type { TriggerMeta } from "./automation-trigger-types";

export const CRM_TRIGGER_META: TriggerMeta[] = [
  {
    value: "lead.created",
    label: "Lead created",
    description: "Runs when a new lead is added to the CRM",
    module: "crm",
    fields: [
      { value: "name", label: "Lead name" },
      { value: "email", label: "Email" },
      { value: "source", label: "Source (referral, website, etc.)" },
      { value: "assignedToId", label: "Assigned rep ID" },
    ],
    samplePayload: {
      id: 1,
      name: "Acme Corp",
      email: "buyer@acme.com",
      source: "website",
      assignedToId: "",
    },
  },
  {
    value: "lead.status_changed",
    label: "Lead status changed",
    description: "Runs when a lead moves to a different status",
    module: "crm",
    fields: [
      { value: "name", label: "Lead name" },
      { value: "status", label: "New status" },
      { value: "previousStatus", label: "Previous status" },
    ],
    samplePayload: {
      id: 1,
      name: "Acme Corp",
      status: "QUALIFIED",
      previousStatus: "NEW",
    },
  },
  {
    value: "lead.assigned",
    label: "Lead assigned",
    description: "Runs when a lead is assigned to a different rep",
    module: "crm",
    fields: [
      { value: "name", label: "Lead name" },
      { value: "assignedToId", label: "Assigned rep ID" },
      { value: "previousAssignedToId", label: "Previous rep ID" },
    ],
    samplePayload: {
      id: 1,
      name: "Acme Corp",
      assignedToId: "",
      previousAssignedToId: "",
    },
  },
  {
    value: "lead.score_updated",
    label: "Lead score updated",
    description: "Runs when a lead's score is recalculated",
    module: "crm",
    fields: [],
    samplePayload: {
      id: 1,
      name: "Acme Corp",
    },
  },
  {
    value: "deal.created",
    label: "Deal created",
    description: "Runs when a new deal is opened",
    module: "crm",
    fields: [],
    samplePayload: {
      id: 1,
      name: "Acme Corp — annual",
      value: "50000",
    },
  },
  {
    value: "deal.stage_changed",
    label: "Deal stage changed",
    description: "Runs when a deal moves to a different pipeline stage",
    module: "crm",
    fields: [
      { value: "name", label: "Deal name" },
      { value: "value", label: "Deal value" },
      { value: "stage", label: "New stage (WON, NEGOTIATION, etc.)" },
      { value: "previousStage", label: "Previous stage" },
      { value: "assignedToId", label: "Assigned rep ID" },
    ],
    samplePayload: {
      id: 1,
      name: "Acme Corp — annual",
      value: "50000",
      stage: "NEGOTIATION",
      previousStage: "PROPOSAL",
      assignedToId: "",
    },
  },
  {
    value: "deal.won",
    label: "Deal won",
    description: "Runs when a deal is closed as won",
    module: "crm",
    fields: [],
    samplePayload: {
      id: 1,
      name: "Acme Corp — annual",
      value: "50000",
      stage: "WON",
    },
  },
  {
    value: "deal.lost",
    label: "Deal lost",
    description: "Runs when a deal is closed as lost",
    module: "crm",
    fields: [],
    samplePayload: {
      id: 1,
      name: "Acme Corp — annual",
      value: "50000",
      stage: "LOST",
    },
  },
];
