import type { Permission } from "./types";

export const CRM_PERMISSIONS: Permission[] = [
  {
    name: "crm:leads:view",
    resource: "crm:leads",
    action: "view",
    description: "View CRM leads",
  },
  {
    name: "crm:leads:create",
    resource: "crm:leads",
    action: "create",
    description: "Create CRM leads",
  },
  {
    name: "crm:leads:update",
    resource: "crm:leads",
    action: "update",
    description: "Update CRM leads",
  },
  {
    name: "crm:leads:assign",
    resource: "crm:leads",
    action: "assign",
    description: "Assign CRM leads",
  },
  {
    name: "crm:leads:delete",
    resource: "crm:leads",
    action: "delete",
    description: "Delete CRM leads",
  },
  {
    name: "crm:targets:view",
    resource: "crm:targets",
    action: "view",
    description: "View targets",
  },
  {
    name: "crm:targets:manage",
    resource: "crm:targets",
    action: "manage",
    description: "Manage targets",
  },
  {
    name: "crm:reports:view",
    resource: "crm:reports",
    action: "view",
    description: "View CRM reports",
  },
  {
    name: "crm:reports:export",
    resource: "crm:reports",
    action: "export",
    description: "Export CRM reports",
  },
  { name: "crm:clients:read", resource: "crm:clients", action: "read", description: "View client accounts" },
  { name: "crm:clients:update", resource: "crm:clients", action: "update", description: "Update client accounts" },
  { name: "crm:incentives:read", resource: "crm:incentives", action: "read", description: "View incentives" },
  { name: "crm:incentives:approve", resource: "crm:incentives", action: "approve", description: "Approve incentives" },
  { name: "crm:incentives:config", resource: "crm:incentives", action: "config", description: "Configure incentive rates" },
  { name: "crm:contacts:view", resource: "crm:contacts", action: "view", description: "View CRM contacts" },
  { name: "crm:contacts:manage", resource: "crm:contacts", action: "manage", description: "Create and manage CRM contacts" },
  { name: "crm:contacts:merge", resource: "crm:contacts", action: "merge", description: "Merge duplicate CRM contacts" },
  { name: "crm:organizations:view", resource: "crm:organizations", action: "view", description: "View CRM companies" },
  { name: "crm:organizations:manage", resource: "crm:organizations", action: "manage", description: "Create and manage CRM companies" },
  { name: "crm:organizations:merge", resource: "crm:organizations", action: "merge", description: "Merge duplicate CRM companies" },
  { name: "crm:assignment-rules:manage", resource: "crm:assignment-rules", action: "manage", description: "Manage lead assignment rules" },
  { name: "crm:automations:manage", resource: "crm:automations", action: "manage", description: "Manage CRM automation rules" },
  { name: "crm:campaigns:manage", resource: "crm:campaigns", action: "manage", description: "Create, update, and delete CRM campaigns" },
  { name: "crm:campaigns:view", resource: "crm:campaigns", action: "view", description: "View CRM campaigns, attribution reports, and ROI metrics" },
  { name: "crm:clients:manage", resource: "crm:clients", action: "manage", description: "Manage client accounts" },
  { name: "crm:customer360:view", resource: "crm:customer360", action: "view", description: "View Customer 360 aggregated profile (respects per-module permissions)" },
  { name: "crm:data-quality:view", resource: "crm:data-quality", action: "view", description: "View CRM data quality dashboard" },
  { name: "crm:email-templates:manage", resource: "crm:email-templates", action: "manage", description: "Manage CRM email templates" },
  { name: "crm:offer-fulfillment:create", resource: "crm:offer-fulfillment", action: "create", description: "Create CRM offer → Inventory SKU fulfillment mappings" },
  { name: "crm:offer-fulfillment:delete", resource: "crm:offer-fulfillment", action: "delete", description: "Delete CRM offer → Inventory SKU fulfillment mappings" },
  { name: "crm:offer-fulfillment:update", resource: "crm:offer-fulfillment", action: "update", description: "Update CRM offer → Inventory SKU fulfillment mappings" },
  { name: "crm:offer-fulfillment:view", resource: "crm:offer-fulfillment", action: "view", description: "View CRM offer → Inventory SKU fulfillment mappings" },
  { name: "crm:products:manage", resource: "crm:products", action: "manage", description: "Manage the CRM product catalog" },
  { name: "crm:scoring-rules:manage", resource: "crm:scoring-rules", action: "manage", description: "Manage lead scoring rules" },
  { name: "crm:sequences:manage", resource: "crm:sequences", action: "manage", description: "Manage CRM email/call sequences" },
  { name: "crm:settings:manage", resource: "crm:settings", action: "manage", description: "Manage CRM configuration (pipelines, stages, options, validation rules, blueprints)" },
  { name: "crm:settings:view", resource: "crm:settings", action: "view", description: "View CRM configuration (pipelines, stages, options, validation rules, blueprints)" },
  { name: "crm:sla:manage", resource: "crm:sla", action: "manage", description: "Manage CRM SLA policies" },
  { name: "crm:tasks:update", resource: "crm:tasks", action: "update", description: "Update, complete, and snooze CRM tasks" },
  { name: "crm:tasks:view", resource: "crm:tasks", action: "view", description: "View CRM tasks and inbox" },
  { name: "crm:territories:manage", resource: "crm:territories", action: "manage", description: "Manage CRM territories" },
  { name: "crm:web-forms:manage", resource: "crm:web-forms", action: "manage", description: "Manage CRM web forms" },
];
