import type { Permission } from "./types";

export const HR_PERMISSIONS: Permission[] = [
  {
    name: "hr:employees:view",
    resource: "hr:employees",
    action: "view",
    description: "View employees list",
  },
  {
    name: "hr:employees:create",
    resource: "hr:employees",
    action: "create",
    description: "Create new employees",
  },
  {
    name: "hr:employees:update",
    resource: "hr:employees",
    action: "update",
    description: "Update employee information",
  },
  {
    name: "hr:employees:delete",
    resource: "hr:employees",
    action: "delete",
    description: "Delete employees",
  },
  {
    name: "hr:attendance:view",
    resource: "hr:attendance",
    action: "view",
    description: "View attendance records",
  },
  {
    name: "hr:attendance:manage",
    resource: "hr:attendance",
    action: "manage",
    description: "Manage attendance records",
  },
  {
    name: "hr:leaves:view",
    resource: "hr:leaves",
    action: "view",
    description: "View leave requests",
  },
  {
    name: "hr:leaves:create",
    resource: "hr:leaves",
    action: "create",
    description: "Create leave requests",
  },
  {
    name: "hr:leaves:approve",
    resource: "hr:leaves",
    action: "approve",
    description: "Approve/reject leave requests",
  },
  {
    name: "hr:payroll:view",
    resource: "hr:payroll",
    action: "view",
    description: "View payroll information",
  },
  {
    name: "hr:payroll:generate",
    resource: "hr:payroll",
    action: "generate",
    description: "Generate payroll",
  },
  {
    name: "hr:payroll:approve",
    resource: "hr:payroll",
    action: "approve",
    description: "Approve payroll",
  },
  {
    name: "hr:payroll:manage",
    resource: "hr:payroll",
    action: "manage",
    description: "Manage legacy payroll records (compatibility surface)",
  },
  {
    name: "hr:payroll:lock",
    resource: "hr:payroll",
    action: "lock",
    description: "Lock legacy payroll runs (compatibility surface)",
  },
  {
    name: "hr:payroll:reopen",
    resource: "hr:payroll",
    action: "reopen",
    description: "Reopen legacy payroll runs (compatibility surface)",
  },
  {
    name: "hr:payroll:publish",
    resource: "hr:payroll",
    action: "publish",
    description: "Publish legacy payslips (compatibility surface)",
  },
  {
    name: "hr:payroll:export",
    resource: "hr:payroll",
    action: "export",
    description: "Export legacy payroll data (compatibility surface)",
  },
  {
    name: "hr:payrolls:read",
    resource: "hr:payrolls",
    action: "read",
    description: "Read legacy payroll records (compatibility surface)",
  },
  {
    name: "hr:payrolls:manage",
    resource: "hr:payrolls",
    action: "manage",
    description: "Manage legacy payroll records (compatibility surface)",
  },
  {
    name: "hr:bonuses:manage",
    resource: "hr:bonuses",
    action: "manage",
    description: "Manage legacy bonus records (compatibility surface)",
  },
  {
    name: "hr:loans:view",
    resource: "hr:loans",
    action: "view",
    description: "View legacy salary loan records (compatibility surface)",
  },
  {
    name: "hr:loans:manage",
    resource: "hr:loans",
    action: "manage",
    description: "Manage legacy salary loan records (compatibility surface)",
  },
  {
    name: "hr:tax:view",
    resource: "hr:tax",
    action: "view",
    description: "View legacy tax declarations (compatibility surface)",
  },
  {
    name: "hr:tax:manage",
    resource: "hr:tax",
    action: "manage",
    description: "Manage legacy tax declarations (compatibility surface)",
  },
  {
    name: "hr:salary:view",
    resource: "hr:salary",
    action: "view",
    description: "View salary structures",
  },
  {
    name: "hr:salary:manage",
    resource: "hr:salary",
    action: "manage",
    description: "Manage salary structures",
  },
  {
    name: "hr:expenses:view",
    resource: "hr:expenses",
    action: "view",
    description: "View expenses",
  },
  {
    name: "hr:expenses:create",
    resource: "hr:expenses",
    action: "create",
    description: "Create expense requests",
  },
  {
    name: "hr:expenses:approve",
    resource: "hr:expenses",
    action: "approve",
    description: "Approve expense requests",
  },
  {
    name: "hr:assets:view",
    resource: "hr:assets",
    action: "view",
    description: "View assets",
  },
  {
    name: "hr:assets:manage",
    resource: "hr:assets",
    action: "manage",
    description: "Manage assets",
  },
  {
    name: "hr:documents:view",
    resource: "hr:documents",
    action: "view",
    description: "View documents",
  },
  {
    name: "hr:documents:manage",
    resource: "hr:documents",
    action: "manage",
    description: "Manage documents",
  },
  {
    name: "hr:performance:view",
    resource: "hr:performance",
    action: "view",
    description: "View performance reviews",
  },
  {
    name: "hr:performance:manage",
    resource: "hr:performance",
    action: "manage",
    description: "Manage performance reviews",
  },
  {
    name: "hr:goals:view",
    resource: "hr:goals",
    action: "view",
    description: "View goals",
  },
  {
    name: "hr:goals:manage",
    resource: "hr:goals",
    action: "manage",
    description: "Manage goals",
  },
  {
    name: "hr:employees:manage",
    resource: "hr:employees",
    action: "manage",
    description: "Manage employees (admin-level: full CRUD + HR operations)",
  },
  {
    name: "hr:benefits:view",
    resource: "hr:benefits",
    action: "view",
    description: "View employee benefit plans and enrollments",
  },
  {
    name: "hr:benefits:manage",
    resource: "hr:benefits",
    action: "manage",
    description: "Manage benefit plans, enrollment windows, and review claims",
  },
  {
    name: "hr:travel:manage",
    resource: "hr:travel",
    action: "manage",
    description: "Approve and manage travel requests",
  },
];
