import type { Permission } from "./types";

export const HR_PERMISSIONS: Permission[] = [
  {
    name: "hr:employees:view",
    resource: "hr:employees",
    action: "view",
    description: "View employee records",
  },
  {
    name: "hr:employees:create",
    resource: "hr:employees",
    action: "create",
    description: "Create new employees",
  },
  {
    name: "hr:employees:update",
    resource: "hr:employees",
    action: "update",
    description: "Update employee information",
  },
  {
    name: "hr:employees:delete",
    resource: "hr:employees",
    action: "delete",
    description: "Delete employees",
  },
  {
    name: "hr:attendance:view",
    resource: "hr:attendance",
    action: "view",
    description: "View attendance records",
  },
  {
    name: "hr:attendance:manage",
    resource: "hr:attendance",
    action: "manage",
    description: "Manage attendance records",
  },
  {
    name: "hr:leaves:view",
    resource: "hr:leaves",
    action: "view",
    description: "View leave requests",
  },
  {
    name: "hr:leaves:create",
    resource: "hr:leaves",
    action: "create",
    description: "Create leave requests",
  },
  {
    name: "hr:leaves:approve",
    resource: "hr:leaves",
    action: "approve",
    description: "Approve/reject leave requests",
  },
  {
    name: "hr:payroll:view",
    resource: "hr:payroll",
    action: "view",
    description: "View payroll information",
  },
  {
    name: "hr:payroll:generate",
    resource: "hr:payroll",
    action: "generate",
    description: "Generate payroll",
  },
  {
    name: "hr:payroll:approve",
    resource: "hr:payroll",
    action: "approve",
    description: "Approve payroll",
  },
  {
    name: "hr:payroll:manage",
    resource: "hr:payroll",
    action: "manage",
    description: "Manage legacy payroll records (compatibility surface)",
  },
  {
    name: "hr:payroll:lock",
    resource: "hr:payroll",
    action: "lock",
    description: "Lock legacy payroll runs (compatibility surface)",
  },
  {
    name: "hr:payroll:reopen",
    resource: "hr:payroll",
    action: "reopen",
    description: "Reopen legacy payroll runs (compatibility surface)",
  },
  {
    name: "hr:payroll:publish",
    resource: "hr:payroll",
    action: "publish",
    description: "Publish legacy payslips (compatibility surface)",
  },
  {
    name: "hr:payroll:export",
    resource: "hr:payroll",
    action: "export",
    description: "Export legacy payroll data (compatibility surface)",
  },
  {
    name: "hr:payrolls:read",
    resource: "hr:payrolls",
    action: "read",
    description: "Read legacy payroll records (compatibility surface)",
  },
  {
    name: "hr:payrolls:manage",
    resource: "hr:payrolls",
    action: "manage",
    description: "Manage legacy payroll records (compatibility surface)",
  },
  {
    name: "hr:bonuses:manage",
    resource: "hr:bonuses",
    action: "manage",
    description: "Manage legacy bonus records (compatibility surface)",
  },
  {
    name: "hr:loans:view",
    resource: "hr:loans",
    action: "view",
    description: "View legacy salary loan records (compatibility surface)",
  },
  {
    name: "hr:loans:manage",
    resource: "hr:loans",
    action: "manage",
    description: "Manage legacy salary loan records (compatibility surface)",
  },
  {
    name: "hr:tax:view",
    resource: "hr:tax",
    action: "view",
    description: "View legacy tax declarations (compatibility surface)",
  },
  {
    name: "hr:tax:manage",
    resource: "hr:tax",
    action: "manage",
    description: "Manage legacy tax declarations (compatibility surface)",
  },
  {
    name: "hr:salary:view",
    resource: "hr:salary",
    action: "view",
    description: "View salary structures",
  },
  {
    name: "hr:salary:manage",
    resource: "hr:salary",
    action: "manage",
    description: "Manage salary structures",
  },
  {
    name: "hr:expenses:view",
    resource: "hr:expenses",
    action: "view",
    description: "View expenses",
  },
  {
    name: "hr:expenses:create",
    resource: "hr:expenses",
    action: "create",
    description: "Create expense requests",
  },
  {
    name: "hr:expenses:approve",
    resource: "hr:expenses",
    action: "approve",
    description: "Approve expense requests",
  },
  {
    name: "hr:assets:view",
    resource: "hr:assets",
    action: "view",
    description: "View assets",
  },
  {
    name: "hr:assets:manage",
    resource: "hr:assets",
    action: "manage",
    description: "Manage assets",
  },
  {
    name: "hr:documents:view",
    resource: "hr:documents",
    action: "view",
    description: "View documents",
  },
  {
    name: "hr:documents:manage",
    resource: "hr:documents",
    action: "manage",
    description: "Manage documents",
  },
  {
    name: "hr:documents:publish",
    resource: "hr:documents",
    action: "publish",
    description: "Classify company documents and publish them to the knowledge base",
  },
  {
    name: "hr:performance:view",
    resource: "hr:performance",
    action: "view",
    description: "View performance reviews",
  },
  {
    name: "hr:performance:manage",
    resource: "hr:performance",
    action: "manage",
    description: "Manage performance reviews",
  },
  {
    name: "hr:goals:view",
    resource: "hr:goals",
    action: "view",
    description: "View goals",
  },
  {
    name: "hr:goals:manage",
    resource: "hr:goals",
    action: "manage",
    description: "Manage goals",
  },
  {
    name: "hr:employees:manage",
    resource: "hr:employees",
    action: "manage",
    description: "Manage employees (admin-level: full CRUD + HR operations)",
  },
  {
    name: "hr:benefits:view",
    resource: "hr:benefits",
    action: "view",
    description: "View employee benefit plans and enrollments",
  },
  {
    name: "hr:benefits:manage",
    resource: "hr:benefits",
    action: "manage",
    description: "Manage benefit plans, enrollment windows, and review claims",
  },
  {
    name: "hr:travel:manage",
    resource: "hr:travel",
    action: "manage",
    description: "Approve and manage travel requests",
  },
  { name: "hr:alumni:read", resource: "hr:alumni", action: "read", description: "Read alumni records" },
  { name: "hr:alumni:write", resource: "hr:alumni", action: "write", description: "Write alumni records" },
  { name: "hr:bank-details:view", resource: "hr:bank-details", action: "view", description: "View unmasked employee bank account details (sensitive)" },
  { name: "hr:career-ladders:manage", resource: "hr:career-ladders", action: "manage", description: "Manage career ladders" },
  { name: "hr:expenses:manage", resource: "hr:expenses", action: "manage", description: "Manage expense requests" },
  { name: "hr:expenses:read", resource: "hr:expenses", action: "read", description: "Read expense requests" },
  { name: "hr:handbook:manage", resource: "hr:handbook", action: "manage", description: "Manage the employee handbook" },
  { name: "hr:integrations:manage", resource: "hr:integrations", action: "manage", description: "Manage HR integrations" },
  { name: "hr:onboarding:tasks:complete", resource: "hr:onboarding:tasks", action: "complete", description: "Complete own or assigned employee onboarding tasks" },
  { name: "hr:onboarding:tasks:view", resource: "hr:onboarding:tasks", action: "view", description: "View employee onboarding tasks" },
  { name: "hr:travel:create", resource: "hr:travel", action: "create", description: "Submit travel requests" },
  { name: "hr:onboarding:manage", resource: "hr:onboarding", action: "manage", description: "Manage onboarding" },
  { name: "hr:reporting-lines:manage", resource: "hr:reporting-lines", action: "manage", description: "Set and schedule reporting lines, run bulk reporting changes and confirm fallback managers" },
  { name: "hr:reporting-lines:review", resource: "hr:reporting-lines", action: "review", description: "Review employee reporting-manager correction requests" },
  { name: "hr:reporting-lines:override", resource: "hr:reporting-lines", action: "override", description: "Update the reporting manager policy, exceed the repeated-change threshold and make emergency changes" },
  { name: "hr:feedback:view", resource: "hr:feedback", action: "view", description: "View 360 feedback cycles" },
  { name: "hr:email-templates:manage", resource: "hr:email-templates", action: "manage", description: "Manage HR email templates" },
  { name: "hr:exit:view", resource: "hr:exit", action: "view", description: "View exits, resignations, and offboarding progress" },
  { name: "hr:exit:manage", resource: "hr:exit", action: "manage", description: "Manage employee exits and offboarding" },
  { name: "hr:import:manage", resource: "hr:import", action: "manage", description: "Create, preview, commit, and roll back HR bulk import jobs" },
  { name: "hr:export:manage", resource: "hr:export", action: "manage", description: "Export HR entity data (employees, attendance, assets, leave balances, documents)" },
  { name: "hr:templates:view", resource: "hr:templates", action: "view", description: "View HR templates" },
  { name: "hr:forms:view", resource: "hr:forms", action: "view", description: "View HR forms and submissions" },
  { name: "hr:automations:view", resource: "hr:automations", action: "view", description: "View HR automation rules and run logs" },
  { name: "hr:cases:view", resource: "hr:cases", action: "view", description: "View HR cases and disciplinary actions" },
  { name: "hr:compliance:manage", resource: "hr:compliance", action: "manage", description: "Manage compliance records" },
  { name: "hr:identity:view", resource: "hr:identity", action: "view", description: "View identity provisioning and access lifecycle" },
  { name: "hr:safety:view", resource: "hr:safety", action: "view", description: "View safety incidents and submit wellness check-ins" },
  { name: "hr:analytics:read", resource: "hr:analytics", action: "read", description: "Read HR analytics" },
  { name: "hr:policies:view", resource: "hr:policies", action: "view", description: "View HR policies" },
  { name: "hr:policies:manage", resource: "hr:policies", action: "manage", description: "Create, update, activate, and archive HR policies" },
  { name: "hr:workflows:view", resource: "hr:workflows", action: "view", description: "View HR approval workflows and instances" },
  { name: "hr:workflows:manage", resource: "hr:workflows", action: "manage", description: "Manage HR approval workflow definitions" },
  { name: "hr:requisitions:view", resource: "hr:requisitions", action: "view", description: "View job requisitions" },
  { name: "hr:requisitions:manage", resource: "hr:requisitions", action: "manage", description: "Manage and approve job requisitions" },
  { name: "hr:sensitive:view", resource: "hr:sensitive", action: "view", description: "View employee sensitive fields (salary, bank, tax, government ID, medical)" },
  { name: "hr:sensitive:manage", resource: "hr:sensitive", action: "manage", description: "Manage employee sensitive fields" },
  { name: "hr:custom-fields:manage", resource: "hr:custom-fields", action: "manage", description: "Manage HR custom field definitions" },
  {
    name: "hr:helpdesk:view",
    resource: "hr:helpdesk",
    action: "view",
    description: "Open the employee support agent view",
  },
  {
    name: "hr:helpdesk:create",
    resource: "hr:helpdesk",
    action: "create",
    description: "Create employee support requests on the agent surface",
  },
  {
    name: "hr:helpdesk:manage",
    resource: "hr:helpdesk",
    action: "manage",
    description: "Administer employee support: every queue, routing and SLA configuration",
  },
  {
    name: "hr:helpdesk:queue-hr",
    resource: "hr:helpdesk",
    action: "queue-hr",
    description: "Work the HR employee support queue",
  },
  {
    name: "hr:helpdesk:queue-it",
    resource: "hr:helpdesk",
    action: "queue-it",
    description: "Work the IT employee support queue",
  },
  {
    name: "hr:helpdesk:queue-finance",
    resource: "hr:helpdesk",
    action: "queue-finance",
    description: "Work the Finance employee support queue",
  },
  {
    name: "hr:helpdesk:queue-admin",
    resource: "hr:helpdesk",
    action: "queue-admin",
    description: "Work the Admin employee support queue",
  },
  {
    name: "hr:helpdesk:queue-legal",
    resource: "hr:helpdesk",
    action: "queue-legal",
    description: "Work the Legal employee support queue",
  },
];
