import type { Permission } from "./types";

export const INVENTORY_PERMISSIONS: Permission[] = [
  { name: "inventory:products:read", resource: "inventory:products", action: "read", description: "View products list and details" },
  { name: "inventory:products:create", resource: "inventory:products", action: "create", description: "Create new products" },
  { name: "inventory:products:update", resource: "inventory:products", action: "update", description: "Update product information" },
  { name: "inventory:products:delete", resource: "inventory:products", action: "delete", description: "Delete products" },
  { name: "inventory:stock:read", resource: "inventory:stock", action: "read", description: "View stock levels and movements" },
  { name: "inventory:stock:adjust", resource: "inventory:stock", action: "adjust", description: "Create stock adjustments" },
  { name: "inventory:stock:transfer", resource: "inventory:stock", action: "transfer", description: "Create stock transfers between locations" },
  { name: "inventory:stock:reserve", resource: "inventory:stock", action: "reserve", description: "Reserve stock for orders" },
  { name: "inventory:stock:reconcile", resource: "inventory:stock", action: "reconcile", description: "Reconcile stock via cycle counts and audits" },
  { name: "inventory:warehouses:scope-all", resource: "inventory:warehouses", action: "scope-all", description: "See and transact in every warehouse, bypassing warehouse assignment" },
  { name: "inventory:adjustments:approve", resource: "inventory:adjustments", action: "approve", description: "Approve a stock adjustment raised by someone else" },
  { name: "inventory:adjustments:post", resource: "inventory:adjustments", action: "post", description: "Post an approved stock adjustment to the ledger" },
  { name: "inventory:warehouses:read", resource: "inventory:warehouses", action: "read", description: "View warehouses and locations" },
  { name: "inventory:warehouses:manage", resource: "inventory:warehouses", action: "manage", description: "Create and manage warehouses and locations" },
  { name: "inventory:vendors:read", resource: "inventory:vendors", action: "read", description: "View vendor list and details" },
  { name: "inventory:vendors:manage", resource: "inventory:vendors", action: "manage", description: "Create and manage vendors" },
  { name: "inventory:purchase-orders:read", resource: "inventory:purchase-orders", action: "read", description: "View purchase orders" },
  { name: "inventory:purchase-orders:create", resource: "inventory:purchase-orders", action: "create", description: "Create purchase orders" },
  { name: "inventory:purchase-orders:update", resource: "inventory:purchase-orders", action: "update", description: "Edit existing purchase orders" },
  { name: "inventory:purchase-orders:approve", resource: "inventory:purchase-orders", action: "approve", description: "Approve and send purchase orders" },
  { name: "inventory:purchase-orders:receive", resource: "inventory:purchase-orders", action: "receive", description: "Receive goods against purchase orders" },
  { name: "inventory:vendor-returns:manage", resource: "inventory:vendor-returns", action: "manage", description: "Manage vendor return orders" },
  { name: "inventory:sales-orders:read", resource: "inventory:sales-orders", action: "read", description: "View sales orders" },
  { name: "inventory:sales-orders:create", resource: "inventory:sales-orders", action: "create", description: "Create sales orders" },
  { name: "inventory:sales-orders:update", resource: "inventory:sales-orders", action: "update", description: "Edit existing sales orders" },
  { name: "inventory:sales-orders:confirm", resource: "inventory:sales-orders", action: "confirm", description: "Confirm sales orders and commit stock" },
  { name: "inventory:sales-orders:ship", resource: "inventory:sales-orders", action: "ship", description: "Ship sales orders and deduct stock" },
  { name: "inventory:sales-orders:invoice", resource: "inventory:sales-orders", action: "invoice", description: "Generate invoices from sales orders" },
  { name: "inventory:customer-returns:manage", resource: "inventory:customer-returns", action: "manage", description: "Manage customer return orders" },
  { name: "inventory:picking:substitute", resource: "inventory:picking", action: "substitute", description: "Swap a different SKU in at the shelf, rewriting the sales-order line and its reservation" },
  { name: "inventory:picking:review", resource: "inventory:picking", action: "review", description: "Own and resolve pick exceptions raised by pickers" },
  { name: "inventory:reports:read", resource: "inventory:reports", action: "read", description: "View inventory reports and analytics" },
  { name: "inventory:valuation:read", resource: "inventory:valuation", action: "read", description: "View inventory valuation and costing reports" },
  { name: "inventory:quality:read", resource: "inventory:quality", action: "read", description: "View quality inspections and holds" },
  { name: "inventory:quality:inspect", resource: "inventory:quality", action: "inspect", description: "Create and conduct quality inspections" },
  { name: "inventory:quality:release", resource: "inventory:quality", action: "release", description: "Release quality holds" },
  { name: "inventory:quality:recall", resource: "inventory:quality", action: "recall", description: "Initiate and manage product recalls" },
  { name: "inventory:quality:plans:manage", resource: "inventory:quality:plans", action: "manage", description: "Author and version inspection plans that decide which arrivals must be inspected before they become available" },
  { name: "inventory:packages:manage", resource: "inventory:packages", action: "manage", description: "Create and manage shipment packages" },
  { name: "inventory:shipments:manage", resource: "inventory:shipments", action: "manage", description: "Create and manage shipments" },
  { name: "inventory:loads:manage", resource: "inventory:loads", action: "manage", description: "Create and manage dispatch loads" },
  { name: "inventory:channels:manage", resource: "inventory:channels", action: "manage", description: "Manage sales channel integrations" },
  { name: "inventory:3pl:manage", resource: "inventory:3pl", action: "manage", description: "Manage third-party logistics connections" },
  { name: "inventory:replenishment:manage", resource: "inventory:replenishment", action: "manage", description: "Manage replenishment rules and forecasting" },
  { name: "inventory:settings:manage", resource: "inventory:settings", action: "manage", description: "Manage inventory module settings" },
  { name: "inventory:webhooks:manage", resource: "inventory:webhooks", action: "manage", description: "Manage inventory webhooks" },
  { name: "inventory:ai:read", resource: "inventory:ai", action: "read", description: "Read AI-assisted inventory surfaces: the operations brief, the digest, insight explanations and supplier-delay signals" },
  { name: "inventory:ai:manage", resource: "inventory:ai", action: "manage", description: "Dismiss or update AI-generated inventory insights" },
  { name: "inventory:ai:propose", resource: "inventory:ai", action: "propose", description: "Propose AI-generated reorder draft POs and confirm them" },
  { name: "inventory:export", resource: "inventory:export", action: "export", description: "Export inventory data" },
  { name: "inventory:audit:read", resource: "inventory:audit", action: "read", description: "Read the inventory audit trail — who changed which record, and when" },
  { name: "inventory:audit:export", resource: "inventory:audit", action: "export", description: "Take an immutable, checksummed audit export of the inventory ledger and audit trail" },
  { name: "inventory:import", resource: "inventory:import", action: "import", description: "Import inventory data" },
];
