import { HR_PERMISSIONS } from "./hr";
import { CRM_PERMISSIONS } from "./crm";
import { SHARED_PERMISSIONS } from "./shared";
import { SUPPORT_PERMISSIONS } from "./support";
import { KB_PERMISSIONS } from "./kb";
import { INVENTORY_PERMISSIONS } from "./inventory";
import { SURVEYS_PERMISSIONS } from "./surveys";
import { FEEDBUCKET_PERMISSIONS } from "./feedbucket";
import { NOTIFICATIONS_PERMISSIONS } from "./notifications";
import { ACCOUNTING_PERMISSIONS } from "./accounting";
import { ROLES } from "@/lib/constants/roles";

export const PERMISSIONS = [
  ...HR_PERMISSIONS,
  ...CRM_PERMISSIONS,
  ...SHARED_PERMISSIONS,
  ...SUPPORT_PERMISSIONS,
  ...KB_PERMISSIONS,
  ...INVENTORY_PERMISSIONS,
  ...SURVEYS_PERMISSIONS,
  ...FEEDBUCKET_PERMISSIONS,
  ...NOTIFICATIONS_PERMISSIONS,
  ...ACCOUNTING_PERMISSIONS,
];

const EMPLOYEE_SELF_SERVICE = [
  "self:attendance",
  "self:leaves",
  "self:expenses",
  "self:payslips",
  "hr:leaves:create",
  "hr:expenses:create",
  "kb:spaces:view",
  "kb:articles:view",
];

export const SYSTEM_ROLES = [
  ROLES.OWNER,
  ROLES.CEO,
  ROLES.HR,
  ROLES.SALES,
  ROLES.CUSTOMER_SUPPORT,
  ROLES.ENGINEERING,
  ROLES.DESIGN,
  ROLES.VIDEO_EDITOR,
  ROLES.DIGITAL_MARKETING,
  ROLES.BLOG_EDITOR,
  ROLES.BRANCH_MANAGER,
  ROLES.BRANCH_HR,
  ROLES.ACCOUNTANT,
] as const;

const ALL_PERMISSIONS = PERMISSIONS.map((p) => p.name);

export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  OWNER: ALL_PERMISSIONS,

  CEO: ALL_PERMISSIONS,

  HR: [
    ...EMPLOYEE_SELF_SERVICE,
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:employees:delete",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:payroll:generate",
    "hr:payroll:approve",
    "hr:salary:view",
    "hr:salary:manage",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:assets:view",
    "hr:assets:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "accounting:view",
    "accounting:report",
    "accounting:reimbursements:read",
    "reports:view",
    "reports:create",
    "reports:export",
  ],

  SALES: [
    ...EMPLOYEE_SELF_SERVICE,
    "crm:leads:view",
    "crm:leads:update",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  CUSTOMER_SUPPORT: [
    ...EMPLOYEE_SELF_SERVICE,
    "feedbucket:submissions:view",
    "feedbucket:submissions:update",
    "feedbucket:submissions:assign",
    "feedbucket:submissions:manage",
    "feedbucket:widgets:view",
    "dashboard:support:view",
    "support:kb:view",
    "support:kb:manage",
    "support:macros:view",
    "support:macros:manage",
    "kb:spaces:view",
    "kb:spaces:manage",
    "kb:categories:manage",
    "kb:articles:view",
    "kb:articles:create",
    "kb:articles:update",
    "kb:articles:delete",
    "kb:articles:manage",
    "kb:analytics:view",
    "kb:ai:generate",
    "projects:roadmap:view",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  ENGINEERING: [
    ...EMPLOYEE_SELF_SERVICE,
    "feedbucket:submissions:view",
    "feedbucket:submissions:update",
    "feedbucket:submissions:assign",
    "feedbucket:submissions:manage",
    "feedbucket:widgets:view",
    "feedbucket:widgets:create",
    "feedbucket:widgets:update",
    "feedbucket:widgets:delete",
    "feedbucket:widgets:manage",
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:sprints:view",
    "projects:timesheets:view",
    "projects:timesheets:create",
    "projects:goals:view",
    "projects:roadmap:view",
  ],

  DESIGN: [
    ...EMPLOYEE_SELF_SERVICE,
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  VIDEO_EDITOR: [
    ...EMPLOYEE_SELF_SERVICE,
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  DIGITAL_MARKETING: [
    ...EMPLOYEE_SELF_SERVICE,
    "projects:view",
    "projects:tickets:view",
    "projects:tickets:create",
    "projects:tickets:update",
    "projects:timesheets:view",
    "projects:timesheets:create",
  ],

  BLOG_EDITOR: [...EMPLOYEE_SELF_SERVICE],

  BRANCH_MANAGER: [
    ...EMPLOYEE_SELF_SERVICE,
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "crm:leads:view",
    "crm:leads:create",
    "crm:leads:update",
    "crm:leads:assign",
    "crm:targets:view",
    "crm:reports:view",
    "projects:view",
    "projects:tickets:view",
    "reports:view",
    "settings:view",
    "dashboard:sales:view",
  ],

  BRANCH_HR: [
    ...EMPLOYEE_SELF_SERVICE,
    "hr:employees:view",
    "hr:employees:create",
    "hr:employees:update",
    "hr:attendance:view",
    "hr:attendance:manage",
    "hr:leaves:view",
    "hr:leaves:approve",
    "hr:payroll:view",
    "hr:payroll:generate",
    "hr:expenses:view",
    "hr:expenses:approve",
    "hr:documents:view",
    "hr:documents:manage",
    "hr:assets:view",
    "hr:assets:manage",
    "hr:performance:view",
    "hr:performance:manage",
    "hr:goals:view",
    "hr:goals:manage",
    "projects:view",
    "projects:tickets:view",
    "reports:view",
  ],

  INVENTORY_MANAGER: [
    "inventory:products:read",
    "inventory:products:create",
    "inventory:products:update",
    "inventory:products:delete",
    "inventory:stock:read",
    "inventory:stock:adjust",
    "inventory:stock:transfer",
    "inventory:stock:reserve",
    "inventory:stock:reconcile",
    "inventory:warehouses:read",
    "inventory:warehouses:manage",
    "inventory:vendors:read",
    "inventory:vendors:manage",
    "inventory:purchase-orders:read",
    "inventory:purchase-orders:create",
    "inventory:purchase-orders:update",
    "inventory:purchase-orders:approve",
    "inventory:purchase-orders:receive",
    "inventory:vendor-returns:manage",
    "inventory:sales-orders:read",
    "inventory:sales-orders:create",
    "inventory:sales-orders:update",
    "inventory:sales-orders:confirm",
    "inventory:sales-orders:ship",
    "inventory:sales-orders:invoice",
    "inventory:customer-returns:manage",
    "inventory:reports:read",
    "inventory:valuation:read",
    "inventory:quality:read",
    "inventory:quality:inspect",
    "inventory:quality:release",
    "inventory:quality:scrap",
    "inventory:quality:recall",
    "inventory:packages:manage",
    "inventory:shipments:manage",
    "inventory:loads:manage",
    "inventory:channels:manage",
    "inventory:3pl:manage",
    "inventory:replenishment:manage",
    "inventory:settings:manage",
    "inventory:import",
    "inventory:export",
    "inventory:webhooks:manage",
    "accounting:view",
  ],

  ACCOUNTANT: [
    ...EMPLOYEE_SELF_SERVICE,
    "accounting:accounts:manage",
    "accounting:journal:create",
    "accounting:journal:post",
    "accounting:journal:approve",
    "accounting:periods:read",
    "accounting:periods:manage",
    "accounting:periods:reopen",
    "accounting:general-ledger:read",
    "accounting:settings:read",
    "accounting:settings:manage",
    "accounting:dimensions:read",
    "accounting:dimensions:manage",
    "accounting:receivables:read",
    "accounting:receivables:manage",
    "accounting:receivables:approve",
    "accounting:credit-notes:read",
    "accounting:credit-notes:create",
    "accounting:credit-notes:manage",
    "accounting:reminders:read",
    "accounting:reminders:manage",
    "accounting:collections:read",
    "accounting:collections:manage",
    "accounting:payables:read",
    "accounting:payables:manage",
    "accounting:payables:approve",
    "accounting:vendor-credits:read",
    "accounting:vendor-credits:create",
    "accounting:vendor-credits:manage",
    "accounting:payment-runs:read",
    "accounting:payment-runs:manage",
    "accounting:payment-runs:approve",
    "accounting:banking:read",
    "accounting:banking:manage",
    "accounting:banking:import",
    "accounting:banking:reconcile",
    "accounting:taxes:read",
    "accounting:taxes:manage",
    "accounting:taxes:pay",
    "accounting:reports:export",
    "accounting:budgets:read",
    "accounting:budgets:create",
    "accounting:budgets:update",
    "accounting:budgets:approve",
    "accounting:forecast:read",
    "accounting:forecast:manage",
    "accounting:assets:read",
    "accounting:assets:create",
    "accounting:assets:update",
    "accounting:assets:manage",
    "accounting:reimbursements:read",
    "accounting:reimbursements:manage",
    "accounting:reimbursements:approve",
    "accounting:approvals:read",
    "accounting:approvals:decide",
    "accounting:audit:read",
    "accounting:audit:export",
    "accounting:recurring:read",
    "accounting:recurring:manage",
    "reports:view",
    "reports:export",
    "reports:generate",
    "reports:schedule",
    "audit-log:read",
  ],
};

