import type { Permission } from "./types";

export const SHARED_PERMISSIONS: Permission[] = [
  {
    name: "accounting:view",
    resource: "accounting",
    action: "view",
    description: "View chart of accounts, journal entries, and accounting reports",
  },
  {
    name: "accounting:manage",
    resource: "accounting",
    action: "manage",
    description: "Create and edit accounts and post manual journal entries",
  },
  {
    name: "accounting:report",
    resource: "accounting",
    action: "report",
    description: "Generate Trial Balance, P&L, and other accounting reports",
  },
  {
    name: "build:view",
    resource: "projects",
    action: "view",
    description: "View projects",
  },
  {
    name: "build:create",
    resource: "projects",
    action: "create",
    description: "Create projects",
  },
  {
    name: "build:update",
    resource: "projects",
    action: "update",
    description: "Update projects",
  },
  {
    name: "build:delete",
    resource: "projects",
    action: "delete",
    description: "Delete projects",
  },
  {
    name: "build:tickets:view",
    resource: "build:tickets",
    action: "view",
    description: "View tickets",
  },
  {
    name: "build:tickets:create",
    resource: "build:tickets",
    action: "create",
    description: "Create tickets",
  },
  {
    name: "build:tickets:update",
    resource: "build:tickets",
    action: "update",
    description: "Update tickets",
  },
  {
    name: "build:tickets:delete",
    resource: "build:tickets",
    action: "delete",
    description: "Delete tickets",
  },
  {
    name: "build:tickets:assign",
    resource: "build:tickets",
    action: "assign",
    description: "Assign tickets",
  },
  {
    name: "build:sprints:view",
    resource: "build:sprints",
    action: "view",
    description: "View sprints",
  },
  {
    name: "build:sprints:manage",
    resource: "build:sprints",
    action: "manage",
    description: "Manage sprints",
  },
  {
    name: "build:timesheets:view",
    resource: "build:timesheets",
    action: "view",
    description: "View timesheets",
  },
  {
    name: "build:timesheets:create",
    resource: "build:timesheets",
    action: "create",
    description: "Create timesheet entries",
  },
  {
    name: "build:goals:view",
    resource: "build:goals",
    action: "view",
    description: "View goals and OKRs",
  },
  {
    name: "build:goals:manage",
    resource: "build:goals",
    action: "manage",
    description: "Create, update, and check in on goals and OKRs",
  },
  {
    name: "build:roadmap:view",
    resource: "build:roadmap",
    action: "view",
    description: "View the product roadmap, feedback, and changelog",
  },
  {
    name: "build:roadmap:manage",
    resource: "build:roadmap",
    action: "manage",
    description: "Manage roadmap items, feedback, and changelog entries",
  },
  {
    name: "reports:view",
    resource: "reports",
    action: "view",
    description: "View reports",
  },
  {
    name: "reports:create",
    resource: "reports",
    action: "create",
    description: "Create reports",
  },
  {
    name: "reports:export",
    resource: "reports",
    action: "export",
    description: "Export reports",
  },
  {
    name: "reports:generate",
    resource: "reports",
    action: "generate",
    description: "Generate reports",
  },
  {
    name: "reports:schedule",
    resource: "reports",
    action: "schedule",
    description: "Schedule reports",
  },
  {
    name: "settings:view",
    resource: "settings",
    action: "view",
    description: "View settings",
  },
  {
    name: "settings:manage",
    resource: "settings",
    action: "manage",
    description: "Manage settings",
  },
  {
    name: "settings:rbac:manage",
    resource: "settings:rbac",
    action: "manage",
    description: "Manage RBAC permissions",
  },
  {
    name: "settings:automations:view",
    resource: "settings:automations",
    action: "view",
    description: "View automation rules and run history",
  },
  {
    name: "settings:automations:manage",
    resource: "settings:automations",
    action: "manage",
    description: "Create, edit, and run automation rules",
  },
  {
    name: "dashboard:sales:view",
    resource: "dashboard:sales",
    action: "view",
    description: "View Sales dashboard",
  },
  {
    name: "dashboard:customer-executive:view",
    resource: "dashboard:customer-executive",
    action: "view",
    description: "View Customer Executive dashboard",
  },
  {
    name: "dashboard:support:view",
    resource: "dashboard:support",
    action: "view",
    description: "View Support CRM dashboard",
  },
  {
    name: "self:attendance",
    resource: "self",
    action: "attendance",
    description: "Check in/out own attendance",
  },
  {
    name: "self:leaves",
    resource: "self",
    action: "leaves",
    description: "Submit and view own leave requests",
  },
  {
    name: "self:expenses",
    resource: "self",
    action: "expenses",
    description: "Submit and view own expense claims",
  },
  {
    name: "self:payslips",
    resource: "self",
    action: "payslips",
    description: "View own payslips",
  },
  {
    name: "self:cases",
    resource: "self",
    action: "cases",
    description: "View and acknowledge disciplinary actions issued to oneself",
  },
  { name: "branch:create", resource: "branch", action: "create", description: "Create branches" },
  { name: "branch:update", resource: "branch", action: "update", description: "Update branches" },
];
