-- Final NOT NULL alignment pass 2: numeric, jsonb, array columns.
-- Backfill existing NULLs with the column default, then SET NOT NULL.

UPDATE attendance              SET break_hours = '0'           WHERE break_hours IS NULL;
UPDATE attendance              SET breaks = '[]'::jsonb        WHERE breaks IS NULL;
UPDATE blog_posts              SET tags = '{}'                 WHERE tags IS NULL;
UPDATE calendar_events         SET attendee_ids = '[]'::jsonb  WHERE attendee_ids IS NULL;
UPDATE contacts                SET tags = '[]'::jsonb          WHERE tags IS NULL;
UPDATE content_calendar_items  SET tags = '{}'                 WHERE tags IS NULL;
UPDATE crm_campaigns           SET roi = '0'                   WHERE roi IS NULL;
UPDATE crm_campaigns           SET spend = '0'                 WHERE spend IS NULL;
UPDATE crm_companies           SET renewal_value = '0'         WHERE renewal_value IS NULL;
UPDATE crm_companies           SET revenue = '0'               WHERE revenue IS NULL;
UPDATE crm_content             SET conv_rate = '0'             WHERE conv_rate IS NULL;
UPDATE crm_monthly_metrics     SET csat = '0'                  WHERE csat IS NULL;
UPDATE crm_monthly_metrics     SET retention = '0'             WHERE retention IS NULL;
UPDATE crm_monthly_metrics     SET revenue = '0'               WHERE revenue IS NULL;
UPDATE crm_views               SET filters = '{}'::jsonb       WHERE filters IS NULL;
UPDATE deals                   SET value = '0'                 WHERE value IS NULL;
UPDATE document_types          SET applicable_roles = '{}'     WHERE applicable_roles IS NULL;
UPDATE fnf_settlements         SET basic_dues = '0'            WHERE basic_dues IS NULL;
UPDATE fnf_settlements         SET bonus_due = '0'             WHERE bonus_due IS NULL;
UPDATE fnf_settlements         SET deductions = '0'            WHERE deductions IS NULL;
UPDATE fnf_settlements         SET leave_encashment = '0'      WHERE leave_encashment IS NULL;
UPDATE fnf_settlements         SET loan_recovery = '0'         WHERE loan_recovery IS NULL;
UPDATE fnf_settlements         SET net_payable = '0'           WHERE net_payable IS NULL;
UPDATE goals                   SET current_value = '0'         WHERE current_value IS NULL;
UPDATE interview_questions     SET tags = '{}'                 WHERE tags IS NULL;
UPDATE interviews              SET panel_interviewer_ids = '[]'::jsonb WHERE panel_interviewer_ids IS NULL;
UPDATE invoices                SET discount = '0'              WHERE discount IS NULL;
UPDATE invoices                SET line_items = '[]'::jsonb    WHERE line_items IS NULL;
UPDATE invoices                SET tax_amount = '0'            WHERE tax_amount IS NULL;
UPDATE invoices                SET tax_rate = '0'              WHERE tax_rate IS NULL;
UPDATE key_results             SET current_value = '0'         WHERE current_value IS NULL;
UPDATE lead_assignment_rules   SET conditions = '[]'::jsonb    WHERE conditions IS NULL;
UPDATE lead_assignment_rules   SET round_robin_user_ids = '[]'::jsonb WHERE round_robin_user_ids IS NULL;
UPDATE leave_requests          SET lop_days = '0'              WHERE lop_days IS NULL;
UPDATE notification_preferences SET categories = '{}'::jsonb   WHERE categories IS NULL;
UPDATE onboarding_tasks        SET depends_on_task_ids = '[]'::jsonb WHERE depends_on_task_ids IS NULL;
UPDATE organizations           SET allowed_email_domains = '{}' WHERE allowed_email_domains IS NULL;
UPDATE payrolls                SET allowances = '0'            WHERE allowances IS NULL;
UPDATE payrolls                SET deductions = '0'            WHERE deductions IS NULL;
UPDATE payrolls                SET hra = '0'                   WHERE hra IS NULL;
UPDATE payrolls                SET overtime_amount = '0'       WHERE overtime_amount IS NULL;
UPDATE payrolls                SET overtime_days = '0'         WHERE overtime_days IS NULL;
UPDATE payrolls                SET overtime_hours = '0'        WHERE overtime_hours IS NULL;
UPDATE project_members         SET hourly_rate = '0'           WHERE hourly_rate IS NULL;
UPDATE project_views           SET filters = '{}'::jsonb       WHERE filters IS NULL;
UPDATE roles                   SET permissions = '[]'::jsonb   WHERE permissions IS NULL;
UPDATE salary_structures       SET allowances = '0'            WHERE allowances IS NULL;
UPDATE salary_structures       SET deductions = '0'            WHERE deductions IS NULL;
UPDATE salary_structures       SET hra_percentage = '40'       WHERE hra_percentage IS NULL;
UPDATE support_ticket_messages SET attachments = '[]'::jsonb   WHERE attachments IS NULL;
UPDATE targets                 SET current_value = '0'         WHERE current_value IS NULL;
UPDATE terminations            SET supporting_doc_urls = '{}'  WHERE supporting_doc_urls IS NULL;
UPDATE territories             SET assigned_reps = '{}'        WHERE assigned_reps IS NULL;
UPDATE territories             SET cities = '{}'               WHERE cities IS NULL;
UPDATE territories             SET states = '{}'               WHERE states IS NULL;
UPDATE tickets                 SET time_spent = '0'            WHERE time_spent IS NULL;
UPDATE timesheets              SET hours = '0'                 WHERE hours IS NULL;
UPDATE webhook_endpoints       SET events = '[]'::jsonb        WHERE events IS NULL;

ALTER TABLE attendance              ALTER COLUMN break_hours SET NOT NULL;
ALTER TABLE attendance              ALTER COLUMN breaks SET NOT NULL;
ALTER TABLE blog_posts              ALTER COLUMN tags SET NOT NULL;
ALTER TABLE calendar_events         ALTER COLUMN attendee_ids SET NOT NULL;
ALTER TABLE contacts                ALTER COLUMN tags SET NOT NULL;
ALTER TABLE content_calendar_items  ALTER COLUMN tags SET NOT NULL;
ALTER TABLE crm_campaigns           ALTER COLUMN roi SET NOT NULL;
ALTER TABLE crm_campaigns           ALTER COLUMN spend SET NOT NULL;
ALTER TABLE crm_companies           ALTER COLUMN renewal_value SET NOT NULL;
ALTER TABLE crm_companies           ALTER COLUMN revenue SET NOT NULL;
ALTER TABLE crm_content             ALTER COLUMN conv_rate SET NOT NULL;
ALTER TABLE crm_monthly_metrics     ALTER COLUMN csat SET NOT NULL;
ALTER TABLE crm_monthly_metrics     ALTER COLUMN retention SET NOT NULL;
ALTER TABLE crm_monthly_metrics     ALTER COLUMN revenue SET NOT NULL;
ALTER TABLE crm_views               ALTER COLUMN filters SET NOT NULL;
ALTER TABLE deals                   ALTER COLUMN value SET NOT NULL;
ALTER TABLE document_types          ALTER COLUMN applicable_roles SET NOT NULL;
ALTER TABLE fnf_settlements         ALTER COLUMN basic_dues SET NOT NULL;
ALTER TABLE fnf_settlements         ALTER COLUMN bonus_due SET NOT NULL;
ALTER TABLE fnf_settlements         ALTER COLUMN deductions SET NOT NULL;
ALTER TABLE fnf_settlements         ALTER COLUMN leave_encashment SET NOT NULL;
ALTER TABLE fnf_settlements         ALTER COLUMN loan_recovery SET NOT NULL;
ALTER TABLE fnf_settlements         ALTER COLUMN net_payable SET NOT NULL;
ALTER TABLE goals                   ALTER COLUMN current_value SET NOT NULL;
ALTER TABLE interview_questions     ALTER COLUMN tags SET NOT NULL;
ALTER TABLE interviews              ALTER COLUMN panel_interviewer_ids SET NOT NULL;
ALTER TABLE invoices                ALTER COLUMN discount SET NOT NULL;
ALTER TABLE invoices                ALTER COLUMN line_items SET NOT NULL;
ALTER TABLE invoices                ALTER COLUMN tax_amount SET NOT NULL;
ALTER TABLE invoices                ALTER COLUMN tax_rate SET NOT NULL;
ALTER TABLE key_results             ALTER COLUMN current_value SET NOT NULL;
ALTER TABLE lead_assignment_rules   ALTER COLUMN conditions SET NOT NULL;
ALTER TABLE lead_assignment_rules   ALTER COLUMN round_robin_user_ids SET NOT NULL;
ALTER TABLE leave_requests          ALTER COLUMN lop_days SET NOT NULL;
ALTER TABLE notification_preferences ALTER COLUMN categories SET NOT NULL;
ALTER TABLE onboarding_tasks        ALTER COLUMN depends_on_task_ids SET NOT NULL;
ALTER TABLE organizations           ALTER COLUMN allowed_email_domains SET NOT NULL;
ALTER TABLE payrolls                ALTER COLUMN allowances SET NOT NULL;
ALTER TABLE payrolls                ALTER COLUMN deductions SET NOT NULL;
ALTER TABLE payrolls                ALTER COLUMN hra SET NOT NULL;
ALTER TABLE payrolls                ALTER COLUMN overtime_amount SET NOT NULL;
ALTER TABLE payrolls                ALTER COLUMN overtime_days SET NOT NULL;
ALTER TABLE payrolls                ALTER COLUMN overtime_hours SET NOT NULL;
ALTER TABLE project_members         ALTER COLUMN hourly_rate SET NOT NULL;
ALTER TABLE project_views           ALTER COLUMN filters SET NOT NULL;
ALTER TABLE roles                   ALTER COLUMN permissions SET NOT NULL;
ALTER TABLE salary_structures       ALTER COLUMN allowances SET NOT NULL;
ALTER TABLE salary_structures       ALTER COLUMN deductions SET NOT NULL;
ALTER TABLE salary_structures       ALTER COLUMN hra_percentage SET NOT NULL;
ALTER TABLE support_ticket_messages ALTER COLUMN attachments SET NOT NULL;
ALTER TABLE targets                 ALTER COLUMN current_value SET NOT NULL;
ALTER TABLE terminations            ALTER COLUMN supporting_doc_urls SET NOT NULL;
ALTER TABLE territories             ALTER COLUMN assigned_reps SET NOT NULL;
ALTER TABLE territories             ALTER COLUMN cities SET NOT NULL;
ALTER TABLE territories             ALTER COLUMN states SET NOT NULL;
ALTER TABLE tickets                 ALTER COLUMN time_spent SET NOT NULL;
ALTER TABLE timesheets              ALTER COLUMN hours SET NOT NULL;
ALTER TABLE webhook_endpoints       ALTER COLUMN events SET NOT NULL;

UPDATE quotes SET tax_amount = '0' WHERE tax_amount IS NULL;
UPDATE quotes SET discount_amount = '0' WHERE discount_amount IS NULL;
UPDATE quote_line_items SET tax_rate = '0' WHERE tax_rate IS NULL;
ALTER TABLE quotes ALTER COLUMN tax_amount SET NOT NULL;
ALTER TABLE quotes ALTER COLUMN discount_amount SET NOT NULL;
ALTER TABLE quote_line_items ALTER COLUMN tax_rate SET NOT NULL;
