import { LayoutDashboard, Users, Briefcase, Receipt, FileText, Timer, BarChart3, Network, ShieldCheck, Target, ClipboardCheck, Map, ListChecks, Inbox, Building2, SlidersHorizontal, ShieldAlert, LayoutTemplate, LayoutGrid, CheckSquare, Plug, Banknote, Layers, Boxes } from "lucide-react";
import type { NavGroup } from "./sidebar-nav-types";

export const WORK_MANAGEMENT_NAV_GROUPS: NavGroup[] = [
{
    label: "Timesheets",
    product: "timesheets",
    module: "timesheets",
    requiredPermission: [
      "timesheets:entries:view",
      "timesheets:team:view",
      "timesheets:approvals:view",
      "timesheets:exceptions:view",
      "timesheets:billing:view",
      "timesheets:payroll:view",
      "timesheets:reports:view",
      "timesheets:settings:view",
      "timesheets:access:view",
    ],
    routes: [
      {
        label: "My Time",
        icon: Timer,
        href: "/timesheets",
        exact: true,
        requiredPermission: "timesheets:entries:view",
      },
      {
        label: "Team",
        icon: Users,
        href: "/timesheets/team",
        requiredPermission: "timesheets:team:view",
      },
      {
        label: "Approvals",
        icon: ListChecks,
        href: "/timesheets/approvals",
        requiredPermission: "timesheets:approvals:view",
      },
      {
        label: "Exceptions",
        icon: ShieldAlert,
        href: "/timesheets/exceptions",
        requiredPermission: "timesheets:exceptions:view",
      },
      {
        label: "Billing",
        icon: Receipt,
        href: "/timesheets/billing",
        requiredPermission: "timesheets:billing:view",
      },
      {
        label: "Payroll",
        icon: Banknote,
        href: "/timesheets/payroll",
        requiredPermission: "timesheets:payroll:view",
      },
      {
        label: "Reports",
        icon: BarChart3,
        href: "/timesheets/reports",
        requiredPermission: "timesheets:reports:view",
      },
      {
        label: "Settings",
        icon: SlidersHorizontal,
        href: "/timesheets/settings",
        requiredPermission: "timesheets:settings:view",
      },
      {
        label: "Access",
        icon: ShieldCheck,
        href: "/timesheets/access",
        requiredPermission: "timesheets:access:view",
      },
    ],
  },
{
    label: "Delivery",
    product: "build",
    module: "build",
    requiredPermission: ["build:view", "build:tickets:view", "build:portal:view"],
    routes: [
      {
        label: "Home",
        icon: LayoutDashboard,
        href: "/build/command-center",
        requiredPermission: "build:view",
      },
      {
        label: "Inbox",
        icon: Inbox,
        href: "/build/inbox",
        requiredPermission: "build:tickets:view",
      },
      {
        label: "My issues",
        icon: CheckSquare,
        href: "/build/my-work",
        requiredPermission: "build:tickets:view",
      },
      {
        label: "Drafts",
        icon: FileText,
        href: "/build/drafts",
        requiredPermission: "build:tickets:view",
      },
      {
        label: "All issues",
        icon: Layers,
        href: "/build/all-work",
        requiredPermission: "build:tickets:view",
      },
      {
        label: "Projects",
        icon: Briefcase,
        href: "/build",
        exact: true,
        requiredPermission: "build:view",
      },
      {
        label: "Client Access",
        icon: ShieldCheck,
        href: "/build/client-access",
        requiredPermission: "build:portal:view",
      },
      {
        label: "Delivery Teams",
        icon: Network,
        href: "/build/teams",
        requiredPermission: "build:teams:view",
      },
      {
        label: "Members",
        icon: Users,
        href: "/build/members",
        requiredPermission: "build:view",
      },
      {
        label: "Customers",
        icon: Building2,
        href: "/build/customers",
        requiredPermission: "crm:leads:view",
      },
    ],
  },
{
    label: "Product",
    product: "build",
    module: "build",
    defaultCollapsed: true,
    requiredPermission: [
      "build:roadmap:view",
      "build:goals:view",
      "build:portfolios:view",
      "build:managed-products:view",
      "build:workspaces:view",
      "build:approvals:view",
      "build:create",
      "integrations:git:view",
    ],
    routes: [
      {
        label: "Roadmap",
        icon: Map,
        href: "/build/roadmap",
        requiredPermission: "build:roadmap:view",
      },
      {
        label: "Goals",
        icon: Target,
        href: "/build/goal",
        requiredPermission: "build:goals:view",
      },
      {
        label: "Portfolios",
        icon: LayoutGrid,
        href: "/build/portfolios",
        requiredPermission: "build:portfolios:view",
      },
      {
        label: "Programs",
        icon: Layers,
        href: "/build/programs",
        requiredPermission: "build:programs:view",
      },
      {
        label: "Managed Products",
        icon: Layers,
        href: "/build/managed-products",
        requiredPermission: "build:managed-products:view",
      },
      {
        label: "PM Workspaces",
        icon: Boxes,
        href: "/build/pm-workspaces",
        requiredPermission: "build:workspaces:view",
      },
      {
        label: "Approvals",
        icon: ClipboardCheck,
        href: "/build/approvals",
        requiredPermission: "build:approvals:view",
      },
      {
        label: "Templates",
        icon: LayoutTemplate,
        href: "/build/templates",
        requiredPermission: "build:create",
      },
      {
        label: "Settings",
        icon: Plug,
        href: "/build/settings/integrations",
        requiredPermission: "integrations:git:view",
      },
      {
        label: "Access",
        icon: ShieldCheck,
        href: "/build/access",
        requiredPermission: "build:access:view",
      },
    ],
  },
];
