import { Users, Clock, Receipt, FileText, BarChart3, ClipboardList, ShieldCheck, CreditCard, Wallet, TrendingUp, BookOpen, Package, Bell, Scale, Coins, Landmark, RefreshCcw, BarChart2, Inbox, SlidersHorizontal, Calculator, Tag, ArrowLeftRight, ShoppingCart, Truck, NotebookPen, PlayCircle, Lock, Layers, PiggyBank, Percent, ArrowDownToLine, HandCoins, TrendingDown, FileStack } from "lucide-react";
import type { NavGroup } from "./sidebar-nav-types";

export const FINANCE_NAV_GROUPS: NavGroup[] = [
{
    label: "Accounting & Finance",
    product: "finance",
    module: "finance",
    requiredPermission: [
      "accounting:accounts:read",
      "accounting:assets:read",
      "accounting:banking:read",
      "accounting:banking:reconcile",
      "accounting:budgets:read",
      "accounting:credit-notes:read",
      "accounting:dimensions:read",
      "accounting:forecast:read",
      "accounting:general-ledger:read",
      "accounting:journal:create",
      "accounting:journal:read",
      "accounting:payables:read",
      "accounting:payment-runs:read",
      "accounting:periods:read",
      "accounting:read",
      "accounting:receivables:read",
      "accounting:recurring:read",
      "accounting:reimbursements:read",
      "accounting:reminders:read",
      "accounting:reports:read",
      "accounting:settings:read",
      "accounting:taxes:read",
      "accounting:vendor-credits:read",
      "payments:providers:view",
    ],
    routes: [
      {
        label: "Overview",
        icon: Calculator,
        href: "/accounting",
        exact: true,
        requiredPermission: "accounting:reports:read",
      },
      {
        label: "Sales",
        icon: TrendingUp,
        href: "/accounting/invoices",
        activePrefixes: ["/billing/invoices"],
        requiredPermission: "accounting:read",
        children: [
          {
            label: "Invoices",
            icon: FileText,
            href: "/accounting/invoices",
            activePrefixes: ["/billing/invoices"],
            requiredPermission: "accounting:read",
          },
          {
            label: "Customers",
            icon: Users,
            href: "/accounting/customers",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "Recurring invoices",
            icon: RefreshCcw,
            href: "/accounting/recurring-invoices",
            requiredPermission: "accounting:recurring:read",
          },
          {
            label: "Credit notes",
            icon: FileStack,
            href: "/accounting/credit-notes",
            requiredPermission: "accounting:credit-notes:read",
          },
          {
            label: "Payments received",
            icon: HandCoins,
            href: "/accounting/payments-received",
            requiredPermission: "accounting:receivables:read",
          },
          {
            label: "Payment reminders",
            icon: Bell,
            href: "/accounting/payment-reminders",
            requiredPermission: "accounting:reminders:read",
          },
          {
            label: "Aged receivables",
            icon: Clock,
            href: "/accounting/aged-receivables",
            requiredPermission: "accounting:reports:read",
          },
        ],
      },
      {
        label: "Purchases",
        icon: ShoppingCart,
        href: "/accounting/purchase-bills",
        requiredPermission: "accounting:journal:read",
        children: [
          {
            label: "Purchase bills",
            icon: Receipt,
            href: "/accounting/purchase-bills",
            requiredPermission: "accounting:journal:read",
          },
          {
            label: "Vendors",
            icon: Truck,
            href: "/accounting/vendors",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "Recurring bills",
            icon: RefreshCcw,
            href: "/accounting/recurring-bills",
            requiredPermission: "accounting:recurring:read",
          },
          {
            label: "Vendor credits",
            icon: FileStack,
            href: "/accounting/vendor-credits",
            requiredPermission: "accounting:vendor-credits:read",
          },
          {
            label: "Vendor payments",
            icon: Coins,
            href: "/accounting/vendor-payments",
            requiredPermission: "accounting:payables:read",
          },
          {
            label: "Payment runs",
            icon: PlayCircle,
            href: "/accounting/payment-runs",
            requiredPermission: "accounting:payment-runs:read",
          },
          {
            label: "Aged payables",
            icon: Clock,
            href: "/accounting/aged-payables",
            requiredPermission: "accounting:reports:read",
          },
        ],
      },
      {
        label: "Banking",
        icon: Landmark,
        href: "/accounting/banking",
        requiredPermission: "accounting:banking:read",
        children: [
          {
            label: "Bank accounts",
            icon: Landmark,
            href: "/accounting/banking",
            exact: true,
            requiredPermission: "accounting:banking:read",
          },
          {
            label: "Import statement",
            icon: ArrowDownToLine,
            href: "/accounting/banking/import",
            requiredPermission: "accounting:banking:read",
          },
          {
            label: "Reconciliation",
            icon: Scale,
            href: "/accounting/banking/reconciliation",
            requiredPermission: "accounting:banking:reconcile",
          },
          {
            label: "Transfers",
            icon: ArrowLeftRight,
            href: "/accounting/banking/transfers",
            requiredPermission: "accounting:banking:read",
          },
        ],
      },
      {
        label: "Expenses",
        icon: Wallet,
        href: "/accounting/expenses",
        requiredPermission: "accounting:reimbursements:read",
        children: [
          {
            label: "Expenses",
            icon: Wallet,
            href: "/accounting/expenses",
            exact: true,
            requiredPermission: "accounting:reimbursements:read",
          },
          {
            label: "Receipt inbox",
            icon: Inbox,
            href: "/accounting/expenses/receipts",
            requiredPermission: "accounting:reimbursements:read",
          },
          {
            label: "Reimbursements",
            icon: RefreshCcw,
            href: "/accounting/expenses/reimbursements",
            requiredPermission: "accounting:reimbursements:read",
          },
          {
            label: "Policies",
            icon: FileText,
            href: "/accounting/expenses/policies",
            requiredPermission: "accounting:reimbursements:read",
          },
        ],
      },
      {
        label: "Accounting",
        icon: BookOpen,
        href: "/accounting/coa",
        requiredPermission: "accounting:accounts:read",
        children: [
          {
            label: "Chart of accounts",
            icon: BookOpen,
            href: "/accounting/coa",
            requiredPermission: "accounting:accounts:read",
          },
          {
            label: "Journal entries",
            icon: NotebookPen,
            href: "/accounting/journal",
            requiredPermission: "accounting:journal:read",
          },
          {
            label: "General ledger",
            icon: ClipboardList,
            href: "/accounting/general-ledger",
            requiredPermission: "accounting:general-ledger:read",
          },
          {
            label: "Period close",
            icon: Lock,
            href: "/accounting/period-close",
            requiredPermission: "accounting:periods:read",
          },
          {
            label: "Opening balances",
            icon: Scale,
            href: "/accounting/opening-balances",
            requiredPermission: "accounting:journal:create",
          },
          {
            label: "Dimensions",
            icon: Tag,
            href: "/accounting/dimensions",
            requiredPermission: "accounting:dimensions:read",
          },
        ],
      },
      {
        label: "Taxes",
        icon: Percent,
        href: "/accounting/taxes",
        requiredPermission: "accounting:taxes:read",
        children: [
          {
            label: "Tax dashboard",
            icon: Percent,
            href: "/accounting/taxes",
            exact: true,
            requiredPermission: "accounting:taxes:read",
          },
          {
            label: "GSTR-1",
            icon: FileText,
            href: "/accounting/gstr-1",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "GSTR-3B",
            icon: BarChart2,
            href: "/accounting/gstr-3b",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "Tax payments",
            icon: Coins,
            href: "/accounting/taxes/payments",
            requiredPermission: "accounting:taxes:read",
          },
          {
            label: "Tax codes",
            icon: Tag,
            href: "/accounting/taxes/codes",
            requiredPermission: "accounting:taxes:read",
          },
        ],
      },
      {
        label: "Reports",
        icon: BarChart3,
        href: "/accounting/reports",
        requiredPermission: "accounting:reports:read",
        children: [
          {
            label: "All reports",
            icon: BarChart3,
            href: "/accounting/reports",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "Trial balance",
            icon: Scale,
            href: "/accounting/trial-balance",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "Profit & loss",
            icon: TrendingUp,
            href: "/accounting/profit-loss",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "Balance sheet",
            icon: Landmark,
            href: "/accounting/balance-sheet",
            requiredPermission: "accounting:reports:read",
          },
          {
            label: "Cash flow",
            icon: Coins,
            href: "/accounting/cash-flow",
            requiredPermission: "accounting:reports:read",
          },
        ],
      },
      {
        label: "Budgets",
        icon: PiggyBank,
        href: "/accounting/budgets",
        requiredPermission: "accounting:budgets:read",
        children: [
          {
            label: "Budgets",
            icon: PiggyBank,
            href: "/accounting/budgets",
            requiredPermission: "accounting:budgets:read",
          },
          {
            label: "Cash forecast",
            icon: TrendingDown,
            href: "/accounting/forecast",
            requiredPermission: "accounting:forecast:read",
          },
          {
            label: "Scenarios",
            icon: Layers,
            href: "/accounting/scenarios",
            requiredPermission: "accounting:forecast:read",
          },
        ],
      },
      {
        label: "Assets",
        icon: Package,
        href: "/accounting/assets",
        requiredPermission: "accounting:assets:read",
        children: [
          {
            label: "Fixed assets",
            icon: Package,
            href: "/accounting/assets",
            requiredPermission: "accounting:assets:read",
          },
          {
            label: "Depreciation runs",
            icon: TrendingDown,
            href: "/accounting/assets/depreciation",
            requiredPermission: "accounting:assets:read",
          },
        ],
      },
      {
        label: "Access",
        icon: ShieldCheck,
        href: "/accounting/access",
        requiredPermission: "accounting:access:view",
      },
      {
        label: "Settings",
        icon: SlidersHorizontal,
        href: "/accounting/settings",
        requiredPermission: [
          "accounting:settings:read",
          "payments:providers:view",
        ],
        children: [
          {
            label: "Finance Settings",
            icon: SlidersHorizontal,
            href: "/accounting/settings",
            exact: true,
            requiredPermission: "accounting:settings:read",
          },
          {
            label: "Payment Providers",
            icon: CreditCard,
            href: "/accounting/settings/payment-providers",
            requiredPermission: "payments:providers:view",
          },
        ],
      },
    ],
  },
];
