import type { Permission } from "./types";

export const SHARED_PERMISSIONS: Permission[] = [
  {
    name: "accounting:view",
    resource: "accounting",
    action: "view",
    description: "View chart of accounts, journal entries, and accounting reports",
  },
  {
    name: "accounting:manage",
    resource: "accounting",
    action: "manage",
    description: "Create and edit accounts and post manual journal entries",
  },
  {
    name: "accounting:report",
    resource: "accounting",
    action: "report",
    description: "Generate Trial Balance, P&L, and other accounting reports",
  },
  {
    name: "projects:view",
    resource: "projects",
    action: "view",
    description: "View projects",
  },
  {
    name: "projects:create",
    resource: "projects",
    action: "create",
    description: "Create projects",
  },
  {
    name: "projects:update",
    resource: "projects",
    action: "update",
    description: "Update projects",
  },
  {
    name: "projects:delete",
    resource: "projects",
    action: "delete",
    description: "Delete projects",
  },
  {
    name: "projects:tickets:view",
    resource: "projects:tickets",
    action: "view",
    description: "View tickets",
  },
  {
    name: "projects:tickets:create",
    resource: "projects:tickets",
    action: "create",
    description: "Create tickets",
  },
  {
    name: "projects:tickets:update",
    resource: "projects:tickets",
    action: "update",
    description: "Update tickets",
  },
  {
    name: "projects:tickets:delete",
    resource: "projects:tickets",
    action: "delete",
    description: "Delete tickets",
  },
  {
    name: "projects:tickets:assign",
    resource: "projects:tickets",
    action: "assign",
    description: "Assign tickets",
  },
  {
    name: "projects:sprints:view",
    resource: "projects:sprints",
    action: "view",
    description: "View sprints",
  },
  {
    name: "projects:sprints:manage",
    resource: "projects:sprints",
    action: "manage",
    description: "Manage sprints",
  },
  {
    name: "projects:timesheets:view",
    resource: "projects:timesheets",
    action: "view",
    description: "View timesheets",
  },
  {
    name: "projects:timesheets:create",
    resource: "projects:timesheets",
    action: "create",
    description: "Create timesheet entries",
  },
  {
    name: "reports:view",
    resource: "reports",
    action: "view",
    description: "View reports",
  },
  {
    name: "reports:create",
    resource: "reports",
    action: "create",
    description: "Create reports",
  },
  {
    name: "reports:export",
    resource: "reports",
    action: "export",
    description: "Export reports",
  },
  {
    name: "reports:generate",
    resource: "reports",
    action: "generate",
    description: "Generate reports",
  },
  {
    name: "reports:schedule",
    resource: "reports",
    action: "schedule",
    description: "Schedule reports",
  },
  {
    name: "settings:view",
    resource: "settings",
    action: "view",
    description: "View settings",
  },
  {
    name: "settings:manage",
    resource: "settings",
    action: "manage",
    description: "Manage settings",
  },
  {
    name: "settings:rbac:manage",
    resource: "settings:rbac",
    action: "manage",
    description: "Manage RBAC permissions",
  },
  {
    name: "dashboard:sales:view",
    resource: "dashboard:sales",
    action: "view",
    description: "View Sales dashboard",
  },
  {
    name: "dashboard:customer-executive:view",
    resource: "dashboard:customer-executive",
    action: "view",
    description: "View Customer Executive dashboard",
  },
  {
    name: "dashboard:support:view",
    resource: "dashboard:support",
    action: "view",
    description: "View Support CRM dashboard",
  },
  {
    name: "self:attendance",
    resource: "self",
    action: "attendance",
    description: "Check in/out own attendance",
  },
  {
    name: "self:leaves",
    resource: "self",
    action: "leaves",
    description: "Submit and view own leave requests",
  },
  {
    name: "self:expenses",
    resource: "self",
    action: "expenses",
    description: "Submit and view own expense claims",
  },
  {
    name: "self:payslips",
    resource: "self",
    action: "payslips",
    description: "View own payslips",
  },
  { name: "dm:leads:create", resource: "dm:leads", action: "create", description: "Capture DM leads" },
  { name: "dm:leads:read", resource: "dm:leads", action: "read", description: "View DM leads" },
  { name: "dm:leads:update", resource: "dm:leads", action: "update", description: "Update DM leads" },
  { name: "dm:leads:delete", resource: "dm:leads", action: "delete", description: "Delete DM leads" },
  { name: "dm:leads:export", resource: "dm:leads", action: "export", description: "Export DM leads" },
  { name: "dm:campaigns:create", resource: "dm:campaigns", action: "create", description: "Create campaigns" },
  { name: "dm:campaigns:read", resource: "dm:campaigns", action: "read", description: "View campaigns" },
  { name: "dm:campaigns:update", resource: "dm:campaigns", action: "update", description: "Update campaigns" },
  { name: "dm:social:read", resource: "dm:social", action: "read", description: "View social stats" },
  { name: "dm:social:create", resource: "dm:social", action: "create", description: "Enter social stats" },
  { name: "branch:create", resource: "branch", action: "create", description: "Create branches" },
  { name: "branch:read", resource: "branch", action: "read", description: "View branches" },
  { name: "branch:update", resource: "branch", action: "update", description: "Update branches" },
  { name: "branch:manage_targets", resource: "branch", action: "manage_targets", description: "Manage branch targets" },
  { name: "chat:submit_lead", resource: "chat", action: "submit_lead", description: "Submit leads via chat" },
];
