
export const ROLES = {
  OWNER: "OWNER",
  CEO: "CEO",
  ADMIN: "ADMIN",
  HR: "HR",
  HR_MANAGER: "HR_MANAGER",
  BRANCH_HR: "BRANCH_HR",
  MANAGER: "MANAGER",
  BRANCH_MANAGER: "BRANCH_MANAGER",
  SALES: "SALES",
  SALES_MANAGER: "SALES_MANAGER",
  ENGINEERING: "ENGINEERING",
  DESIGN: "DESIGN",
  CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
  VIDEO_EDITOR: "VIDEO_EDITOR",
  DIGITAL_MARKETING: "DIGITAL_MARKETING",
  BLOG_EDITOR: "BLOG_EDITOR",
  ACCOUNTANT: "ACCOUNTANT",
} as const;

export const ADMIN_ROLES: readonly string[] = [
  ROLES.OWNER,
  ROLES.CEO,
  ROLES.HR,
];

export const EXPENSE_ADMIN_ROLES: readonly string[] = [
  ROLES.OWNER,
  ROLES.CEO,
  ROLES.HR,
];
