import { readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * The backend RBAC catalogue, read from the VENDORED contract rather than from a
 * sibling backend checkout.
 *
 * Measured on CI run 33719474880: 8 suites failed because they read
 * `../streamlineos-backend/src/...` and CI clones one repository. The page-level
 * RBAC gate had therefore never been enforced there. `contracts/permission-catalog.json`
 * is generated by `pnpm generate:permission-catalog` and held current by
 * `pnpm check:permission-catalog`, which fails on drift against both the
 * vendored OpenAPI contract (hermetically) and a fresh regeneration (where the
 * backend is present). Reading a stale copy is therefore a gate failure, not a
 * silent pass.
 */
export interface VendoredPermissionCatalog {
  readonly permissions: readonly string[];
  readonly delegableModuleIds: readonly string[];
  readonly memberDefaultPermissions: readonly string[];
  readonly ownerOnlyOperations: Readonly<Record<string, string>>;
}

export const PERMISSION_CATALOG_PATH = resolve(
  __dirname,
  "..",
  "contracts",
  "permission-catalog.json",
);

let cached: VendoredPermissionCatalog | null = null;

export function permissionCatalog(): VendoredPermissionCatalog {
  if (cached === null)
    cached = JSON.parse(
      readFileSync(PERMISSION_CATALOG_PATH, "utf8"),
    ) as VendoredPermissionCatalog;
  return cached;
}

/** Every permission name the backend declares, including the generated module-access keys. */
export function backendPermissionNames(): Set<string> {
  return new Set(permissionCatalog().permissions);
}

export function delegableModuleIds(): readonly string[] {
  return permissionCatalog().delegableModuleIds;
}

/** The keys every MEMBER keeps by default, before any role or grant. */
export function memberDefaultPermissions(): Set<string> {
  return new Set(permissionCatalog().memberDefaultPermissions);
}

/** Owner-only operation id -> the reason string the backend states for it. */
export function ownerOnlyOperations(): Map<string, string> {
  return new Map(Object.entries(permissionCatalog().ownerOnlyOperations));
}
