import { z } from "zod";

export const OPENAPI_HASH = "sha256:3a4912ddb36a036e2f209fe3c70015a3639a64af317e54b7668d7bc9f316ed07" as const;

export const genProjectListPageSchema = z.object({
  data: z.array(z.object({
    id: z.number().int(),
    name: z.string(),
    description: z.string().nullable(),
    key: z.string(),
    status: z.string(),
    priority: z.string().nullable(),
    startDate: z.string().nullable(),
    endDate: z.string().nullable(),
    managedProductId: z.number().int().nullable(),
    manager: z.object({
      id: z.string(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      image: z.string().nullable(),
    }).nullable(),
    progress: z.object({
      total: z.number().int(),
      done: z.number().int(),
      percentage: z.number().int(),
    }),
    health: z.enum(["on_track", "at_risk", "off_track"]),
    members: z.array(z.object({
      id: z.string(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      image: z.string().nullable(),
    })),
    teams: z.array(z.string()),
  })),
  hasMore: z.boolean(),
  nextCursor: z.number().int().nullable(),
});

export const genProjectRowSchema = z.object({
  id: z.number().int(),
  orgId: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  key: z.string(),
  clientMembershipId: z.number().int().nullable(),
  managerMembershipId: z.number().int().nullable(),
  startDate: z.string().nullable(),
  endDate: z.string().nullable(),
  status: z.string(),
  priority: z.string().nullable(),
  dealId: z.number().int().nullable(),
  managedProductId: z.number().int().nullable(),
  budget: z.string().nullable(),
  budgetMinor: z.number().int().nullable(),
  budgetCurrency: z.string().nullable(),
  settings: z.unknown(),
  deletedAt: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  statuses: z.array(z.object({
    id: z.number().int(),
    projectId: z.number().int(),
    orgId: z.string(),
    name: z.string(),
    order: z.number().int(),
    color: z.string().nullable(),
    type: z.enum(["backlog", "unstarted", "started", "completed", "cancelled"]).nullable(),
    wipLimit: z.number().int().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })),
  members: z.array(z.object({
    id: z.number().int(),
    orgId: z.string(),
    projectId: z.number().int(),
    membershipId: z.number().int(),
    role: z.string(),
    user: z.object({
      id: z.number().int(),
      user: z.object({
        id: z.string(),
        name: z.string().nullable(),
        firstName: z.string().nullable(),
        lastName: z.string().nullable(),
        email: z.string(),
        image: z.string().nullable(),
      }),
    }),
  })),
});

export const genProjectAnalyticsSchema = z.object({
  stateDistribution: z.unknown(),
  priorityBreakdown: z.unknown(),
  assigneeCompletion: z.unknown(),
  volumeOverTime: z.unknown(),
  cycleVelocity: z.unknown(),
  estimateVsActual: z.unknown(),
  healthScore: z.number().int(),
  healthStatus: z.string(),
  healthBreakdown: z.object({
    completionPct: z.number().int(),
    onTimePct: z.number().int(),
    velocityScore: z.number().int(),
    overdueTickets: z.number().int(),
    totalTickets: z.number().int(),
    openTickets: z.number().int(),
  }),
});

export const genTicketListPageSchema = z.object({
  data: z.array(z.object({
    id: z.number().int(),
    orgId: z.string(),
    title: z.string(),
    type: z.enum(["EPIC", "STORY", "TASK", "BUG"]),
    status: z.string(),
    priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]),
    projectId: z.number().int().nullable(),
    ticketNumber: z.number().int(),
    epicId: z.number().int().nullable(),
    assigneeMembershipId: z.number().int().nullable(),
    reporterId: z.string().nullable(),
    points: z.number().int().nullable(),
    storyPoints: z.number().int().nullable(),
    link: z.string().nullable(),
    rank: z.string(),
    parentTicketId: z.number().int().nullable(),
    originalEstimate: z.string().nullable(),
    timeSpent: z.string(),
    startDate: z.string().nullable(),
    dueDate: z.string().nullable(),
    moduleId: z.number().int().nullable(),
    cycleId: z.number().int().nullable(),
    sequenceId: z.string().nullable(),
    estimate: z.number().int().nullable(),
    health: z.enum(["on_track", "at_risk", "off_track"]).nullable(),
    version: z.number().int(),
    createdAt: z.string(),
    updatedAt: z.string(),
    descriptionExcerpt: z.string(),
    assigneeId: z.string().nullable(),
    assignee: z.object({
      id: z.string(),
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string(),
      image: z.string().nullable(),
    }).nullable(),
    assignees: z.array(z.object({
      id: z.number().int(),
      ticketId: z.number().int(),
      assignedAt: z.string(),
      assignedBy: z.string().nullable(),
      userId: z.string(),
      user: z.object({
        id: z.string(),
        name: z.string().nullable(),
        firstName: z.string().nullable(),
        lastName: z.string().nullable(),
        email: z.string(),
        image: z.string().nullable(),
      }),
    })),
    labels: z.array(z.object({
      id: z.number().int(),
      ticketId: z.number().int(),
      labelId: z.number().int(),
      createdAt: z.string(),
      label: z.object({
        id: z.number().int(),
        orgId: z.string(),
        name: z.string(),
        color: z.string().nullable(),
        createdAt: z.string(),
      }),
    })),
    cycle: z.object({
      id: z.number().int(),
      name: z.string(),
      status: z.string(),
      startDate: z.string(),
      endDate: z.string(),
    }).nullable(),
  })),
  pagination: z.object({
    limit: z.number().int(),
    hasMore: z.boolean(),
    nextCursor: z.string().nullable(),
  }),
});

export const genTicketDetailWireSchema = z.object({
  id: z.number().int(),
  orgId: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  type: z.enum(["EPIC", "STORY", "TASK", "BUG"]),
  status: z.string(),
  priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]),
  projectId: z.number().int().nullable(),
  ticketNumber: z.number().int(),
  epicId: z.number().int().nullable(),
  assigneeMembershipId: z.number().int().nullable(),
  reporterId: z.string().nullable(),
  reporterMembershipId: z.number().int().nullable(),
  points: z.number().int().nullable(),
  storyPoints: z.number().int().nullable(),
  link: z.string().nullable(),
  rank: z.string(),
  parentTicketId: z.number().int().nullable(),
  originalEstimate: z.string().nullable(),
  timeSpent: z.string(),
  startDate: z.string().nullable(),
  dueDate: z.string().nullable(),
  moduleId: z.number().int().nullable(),
  cycleId: z.number().int().nullable(),
  sequenceId: z.string().nullable(),
  estimate: z.number().int().nullable(),
  completionPercentage: z.number().int(),
  clientVisible: z.boolean(),
  isRecurring: z.boolean(),
  recurrenceRule: z.unknown(),
  recurrenceParentId: z.number().int().nullable(),
  recurrenceNextRunAt: z.string().nullable(),
  customerId: z.number().int().nullable(),
  health: z.enum(["on_track", "at_risk", "off_track"]).nullable(),
  version: z.number().int(),
  deletedAt: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  project: z.object({
    id: z.number().int(),
    name: z.string(),
    key: z.string(),
    orgId: z.string(),
  }).nullable(),
  epic: z.object({
    id: z.number().int(),
    name: z.string(),
  }).nullable(),
  assignee: z.object({
    user: z.object({
      id: z.string(),
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string(),
      image: z.string().nullable(),
    }).nullable(),
  }).nullable(),
  reporter: z.object({
    id: z.string(),
    name: z.string().nullable(),
    firstName: z.string().nullable(),
    lastName: z.string().nullable(),
    email: z.string(),
    image: z.string().nullable(),
  }).nullable(),
  assignees: z.array(z.object({
    id: z.number().int(),
    ticketId: z.number().int(),
    assignedAt: z.string(),
    assignedBy: z.string().nullable(),
    user: z.object({
      userId: z.string(),
      user: z.object({
        id: z.string(),
        name: z.string().nullable(),
        firstName: z.string().nullable(),
        lastName: z.string().nullable(),
        email: z.string(),
        image: z.string().nullable(),
      }).nullable(),
    }),
  })),
  members: z.array(z.object({
    user: z.object({
      user: z.object({
        id: z.string(),
        name: z.string().nullable(),
        firstName: z.string().nullable(),
        lastName: z.string().nullable(),
        email: z.string(),
        image: z.string().nullable(),
      }).nullable(),
    }),
  })),
  watchers: z.array(z.object({
    user: z.object({
      id: z.string(),
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string(),
      image: z.string().nullable(),
    }).nullable(),
  })),
  attachments: z.array(z.object({
    id: z.number().int(),
    filename: z.string(),
    url: z.string(),
    mimeType: z.string().nullable(),
    uploader: z.object({
      id: z.string(),
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string(),
      image: z.string().nullable(),
    }).nullable(),
  })),
  labels: z.array(z.object({
    id: z.number().int(),
    name: z.string(),
    color: z.string().nullable(),
  })),
  comments: z.array(z.object({
    id: z.number().int(),
    orgId: z.string(),
    ticketId: z.number().int(),
    userId: z.string(),
    content: z.string(),
    parentCommentId: z.number().int().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
    user: z.object({
      id: z.string(),
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string(),
      image: z.string().nullable(),
    }).nullable(),
    reactions: z.array(z.object({
      emoji: z.string(),
      userId: z.string(),
    })).optional(),
  })).optional(),
});

export const genCustomStateListSchema = z.array(z.object({
  id: z.number().int(),
  orgId: z.string(),
  projectId: z.number().int(),
  name: z.string(),
  order: z.number().int(),
  color: z.string().nullable(),
  type: z.enum(["backlog", "unstarted", "started", "completed", "cancelled"]).nullable(),
  wipLimit: z.number().int().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
}));

export const genCustomFieldListSchema = z.array(z.object({
  id: z.number().int(),
  orgId: z.string(),
  projectId: z.number().int().nullable(),
  name: z.string(),
  type: z.string(),
  options: z.array(z.string()).nullable(),
  required: z.boolean().nullable(),
  position: z.number().int().nullable(),
  createdAt: z.string(),
}));

export const genBuildMemberPageSchema = z.object({
  data: z.array(z.object({
    id: z.string(),
    name: z.string().nullable(),
    firstName: z.string().nullable(),
    lastName: z.string().nullable(),
    image: z.string().nullable(),
    email: z.string(),
    role: z.string(),
    joinedAt: z.string(),
  })),
  pagination: z.object({
    limit: z.number().int(),
    hasMore: z.boolean(),
    nextCursor: z.string().nullable(),
  }),
});

export const genReleasePageSchema = z.object({
  data: z.array(z.object({
    id: z.number().int(),
    orgId: z.string(),
    projectId: z.number().int(),
    name: z.string(),
    version: z.string(),
    rowVersion: z.number().int(),
    description: z.string().nullable(),
    status: z.string(),
    releaseDate: z.string().nullable(),
    publishedAt: z.string().nullable(),
    createdBy: z.string().nullable(),
    createdByUser: z.object({
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string().nullable(),
    }).nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
    ticketCount: z.number().int(),
  })),
  pagination: z.object({
    limit: z.number().int(),
    hasMore: z.boolean(),
    nextCursor: z.string().nullable(),
  }),
});

export const genWebhookPageSchema = z.object({
  data: z.array(z.object({
    id: z.number().int(),
    orgId: z.string(),
    projectId: z.number().int(),
    url: z.string(),
    events: z.array(z.string()),
    isActive: z.boolean(),
    hasSecret: z.boolean(),
    secretSetAt: z.string().nullable(),
    version: z.number().int(),
    createdAt: z.string(),
    updatedAt: z.string(),
    lastDeliveryAt: z.string().nullable(),
    lastDeliveryStatus: z.enum(["success", "failed", "pending"]).nullable(),
    failureRate: z.number().nullable(),
  })),
  hasMore: z.boolean(),
  nextCursor: z.number().int().nullable(),
});

export const genAutomationPageSchema = z.object({
  data: z.array(z.object({
    id: z.number().int(),
    projectId: z.number().int(),
    name: z.string(),
    triggerEvent: z.string(),
    isActive: z.boolean(),
    conditions: z.array(z.object({
      field: z.string(),
      operator: z.enum(["equals", "not_equals", "contains", "is_empty", "is_not_empty"]),
      value: z.string().optional(),
    })),
    actions: z.array(z.object({
      type: z.enum(["set_status", "set_assignee", "set_priority", "add_label", "add_comment"]),
      value: z.string(),
    })),
    createdBy: z.string().nullable(),
    createdByUser: z.object({
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string().nullable(),
    }).nullable(),
    lastRunAt: z.string().nullable(),
    lastFailureAt: z.string().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })),
  pagination: z.object({
    limit: z.number().int(),
    hasMore: z.boolean(),
    nextCursor: z.string().nullable(),
  }),
});

export const genTicketLabelListSchema = z.array(z.object({
  id: z.number().int(),
  orgId: z.string(),
  name: z.string(),
  color: z.string(),
  createdAt: z.string(),
}));

export const genAllWorkPageSchema = z.object({
  data: z.array(z.object({
    id: z.number().int(),
    title: z.string(),
    type: z.string(),
    status: z.string(),
    priority: z.string().nullable(),
    projectId: z.number().int().nullable(),
    projectKey: z.string().nullable(),
    projectName: z.string().nullable(),
    ticketNumber: z.number().int(),
    dueDate: z.string().nullable(),
    startDate: z.string().nullable(),
    points: z.number().nullable(),
    estimate: z.number().nullable(),
    rank: z.string().nullable(),
    version: z.number().int(),
    cycleId: z.number().int().nullable(),
    epicId: z.number().int().nullable(),
    assigneeId: z.string().nullable(),
    assignee: z.object({
      id: z.string(),
      name: z.string().nullable(),
      firstName: z.string().nullable(),
      lastName: z.string().nullable(),
      email: z.string().nullable(),
      image: z.string().nullable(),
    }).nullable(),
    labels: z.array(z.object({
      id: z.number().int(),
      name: z.string(),
      color: z.string().nullable(),
    })),
    createdAt: z.string(),
    updatedAt: z.string(),
  })),
  limit: z.number().int(),
  nextCursor: z.string().nullable(),
  hasMore: z.boolean(),
  total: z.number().int().optional(),
});
