/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Every `pgEnum` declared under `backend/src/db/schema/**`, as the literal
 * member list Postgres will accept for that column.
 *
 * Regenerate:  pnpm -C backend generate:db-enums
 * Re-vendor:   pnpm -C frontend generate:db-enums
 *
 * Gates:       backend  check:db-enums          (file matches the schema)
 *              frontend check:db-enums-vendor   (both copies are byte-identical)
 *
 * Read a member list from here instead of hand-writing `z.enum([...])`, and
 * never type an enum-shaped column as `z.string()`:
 *
 *     import { DB_ENUMS } from "src/db/enums.generated";
 *     category: z.enum(DB_ENUMS.notification_category),
 */

export const DB_ENUMS = {
  acct_document_status: ["DRAFT", "POSTED", "PARTIALLY_PAID", "PAID", "VOID"],
  acct_settlement_status: ["POSTED", "REVERSED"],
  ack_status: ["PENDING", "ACKNOWLEDGED", "DECLINED"],
  action_item_status: ["open", "in_progress", "done", "converted", "cancelled"],
  affiliate_status: ["PENDING", "ACTIVE", "SUSPENDED"],
  ai_credit_reservation_status: ["RESERVED", "SETTLED", "RELEASED"],
  ai_credit_txn_type: ["PURCHASE", "USAGE", "REFUND", "PLAN_GRANT", "EXPIRY"],
  ai_feedback_rating: ["UP", "DOWN"],
  ai_job_status: ["QUEUED", "RUNNING", "COMPLETED", "FAILED", "DEAD", "CANCELLED"],
  ai_proposal_status: ["PROPOSED", "CONFIRMED", "EXECUTED", "EXPIRED", "CANCELLED"],
  ap_document_type: ["BILL", "DEBIT_NOTE"],
  app_install_status: ["TRIALING", "ACTIVE", "CANCELLED"],
  application_status: ["APPLIED", "SHORTLISTED", "INTERVIEWING", "OFFERED", "ACCEPTED", "REJECTED", "WITHDRAWN"],
  approval_entity_type: ["task", "milestone", "budget", "release", "change_request", "document", "timesheet", "client_approval"],
  approval_status: ["requested", "pending", "approved", "rejected", "changes_requested", "escalated", "cancelled"],
  ar_document_type: ["INVOICE", "CREDIT_NOTE"],
  asset_status: ["AVAILABLE", "ASSIGNED", "MAINTENANCE", "RETIRED"],
  assignment_rule_type: ["assign_user", "round_robin", "weighted_round_robin", "least_loaded", "territory"],
  attendance_accuracy_bucket: ["LE_10_M", "GT_10_LE_50_M", "GT_50_LE_100_M", "GT_100_M", "UNKNOWN"],
  attendance_correction_action: ["VOID", "REPLACE"],
  attendance_correction_replacement_kind: ["CHECK_IN", "CHECK_OUT", "BREAK_START", "BREAK_END", "AUTO_CHECKOUT"],
  attendance_distance_bucket: ["INSIDE_RADIUS", "OUTSIDE_LE_50_M", "OUTSIDE_GT_50_M", "UNKNOWN"],
  attendance_event_kind: ["CHECK_IN", "CHECK_OUT", "BREAK_START", "BREAK_END", "AUTO_CHECKOUT", "CORRECTION"],
  attendance_event_source: ["SELF_SERVICE", "HR_ADMIN", "BIOMETRIC_DEVICE", "REGULARIZATION", "IMPORT", "MIGRATION", "SYSTEM"],
  attendance_session_state: ["WORKING", "ON_BREAK", "CLOSED"],
  automation_action_outcome: ["success", "failure"],
  automation_run_outcome: ["matched_success", "matched_partial_failure", "matched_failed", "not_matched", "blocked_loop_guard", "blocked_rate_limit", "error"],
  bank_identifier_scheme: ["IFSC_ACCOUNT", "IBAN", "ROUTING_ACCOUNT", "SORT_ACCOUNT", "BSB_ACCOUNT", "UPI", "OTHER"],
  bank_match_kind: ["receipt", "payment", "journal"],
  bank_statement_source: ["csv", "manual", "feed"],
  blog_post_status: ["draft", "published", "archived"],
  bonus_type: ["PERFORMANCE", "FESTIVAL", "REFERRAL", "SPOT", "ANNUAL", "JOINING", "RETENTION", "COMMISSION", "ADJUSTMENT"],
  broadcast_audience_kind: ["ROLE", "DEPARTMENT", "USER"],
  broadcast_audience_type: ["all", "roles", "departments", "users"],
  broadcast_status: ["DRAFT", "SCHEDULED", "QUEUED", "SENDING", "SENT", "CANCELLED", "FAILED"],
  bug_severity: ["blocker", "critical", "major", "minor", "trivial"],
  bug_status: ["new", "triaged", "assigned", "in_progress", "fixed", "ready_for_qa", "verified", "reopened", "closed"],
  candidate_status: ["NEW", "SCREENING", "INTERVIEW", "OFFER", "HIRED", "REJECTED"],
  change_request_status: ["submitted", "under_review", "estimated", "awaiting_approval", "approved", "rejected", "in_progress", "completed"],
  changelog_type: ["feature", "improvement", "fix"],
  chat_message_type: ["text", "lead_submission", "system"],
  client_account_status: ["ACCOUNT_OPENING", "QUERIES", "PLAN_SELECTED", "INVESTED"],
  client_health_status: ["healthy", "at_risk", "critical"],
  command_fence_status: ["IN_FLIGHT", "COMPLETED", "FAILED"],
  commission_status: ["PENDING", "APPROVED", "PAID", "CANCELLED"],
  community_member_role: ["member", "moderator"],
  compliance_enforcement: ["off", "warn", "block_send", "block_post"],
  compliance_status: ["not_required", "pending", "submitted", "accepted", "rejected", "cancelled"],
  compliance_transport: ["none", "irp", "mock_irp", "peppol", "fatoora", "sdi", "mtd", "other"],
  crm_account_tier: ["free", "pro", "enterprise"],
  crm_activity_type: ["deal_won", "meeting", "proposal", "call", "email", "ticket", "escalation", "task_completed"],
  crm_campaign_status: ["active", "paused", "completed"],
  crm_consent_channel: ["EMAIL", "SMS", "WHATSAPP", "PHONE", "POST"],
  crm_consent_source: ["USER_ENTRY", "IMPORT", "WEB_FORM", "UNSUBSCRIBE_LINK", "API", "ENRICHMENT"],
  crm_consent_status: ["OPTED_IN", "OPTED_OUT", "UNKNOWN"],
  crm_deal_stage: ["Discovery", "Qualified", "Proposal", "Negotiation", "Closed Won"],
  crm_health: ["healthy", "at_risk", "critical"],
  crm_lead_status: ["visitor", "lead", "mql", "sql", "opportunity"],
  crm_legal_basis: ["CONSENT", "CONTRACT", "LEGITIMATE_INTEREST", "LEGAL_OBLIGATION"],
  crm_person_role: ["sales_rep", "csm"],
  crm_support_ticket_priority: ["critical", "high", "medium", "low"],
  crm_support_ticket_status: ["new", "in_progress", "resolved", "closed"],
  cycle_scope_event_type: ["added", "removed", "estimate_changed", "completed", "reopened"],
  cycle_status: ["draft", "active", "completed"],
  data_scope: ["all", "team", "own", "none"],
  decision_status: ["proposed", "accepted", "superseded", "revisit"],
  device_status: ["ACTIVE", "INACTIVE", "LOST", "RETURNED"],
  doc_audit_action: ["UPLOADED", "APPROVED", "REJECTED", "RE_UPLOAD_REQUESTED", "RE_UPLOADED"],
  document_classification: ["PERSONAL", "CONFIDENTIAL", "RESTRICTED", "INTERNAL"],
  document_type: ["CONTRACT", "CERTIFICATE", "ID_PROOF", "PAYSLIP", "POLICY", "OFFER_LETTER", "RESUME", "OTHER"],
  email_outbox_scope: ["PLATFORM", "TENANT"],
  email_suppression_reason: ["HARD_BOUNCE", "COMPLAINT", "UNSUBSCRIBE", "MANUAL", "INVALID_ADDRESS"],
  email_suppression_source: ["PROVIDER_WEBHOOK", "USER", "ADMIN", "IMPORT"],
  engagement_campaign_status: ["draft", "active", "completed", "cancelled"],
  enterprise_quote_status: ["DRAFT", "PENDING_APPROVAL", "APPROVED", "SENT", "ACCEPTED", "REJECTED", "EXPIRED"],
  exit_checklist_status: ["PENDING", "DONE", "WAIVED"],
  expense_status: ["DRAFT", "SUBMITTED", "PENDING", "APPROVED", "REJECTED", "REIMBURSEMENT_PENDING", "REIMBURSED", "PAID"],
  feedback_status: ["open", "planned", "in_progress", "completed", "declined"],
  feedback_type: ["SELF", "PEER", "MANAGER", "SKIP_LEVEL"],
  feedbucket_submission_priority: ["low", "medium", "high", "urgent"],
  feedbucket_submission_status: ["open", "in_progress", "resolved", "archived"],
  feedbucket_submission_type: ["bug", "idea", "feature", "question", "praise", "other"],
  fin_reimbursement_batch_status: ["DRAFT", "APPROVED", "PAID"],
  fnf_status: ["DRAFT", "PENDING_APPROVAL", "APPROVED", "PAID", "HR_REVIEW", "FINANCE_REVIEW"],
  form_submission_status: ["submitted", "processed", "rejected"],
  form_type: ["task_request", "bug_report", "feature_request", "change_request", "client_approval", "risk_report", "qa_issue", "generic"],
  gender: ["MALE", "FEMALE", "OTHER"],
  git_provider: ["github", "gitlab", "bitbucket"],
  git_ref_type: ["commit", "pull_request", "branch"],
  gl_account_type: ["ASSET", "CONTRA_ASSET", "LIABILITY", "CONTRA_LIABILITY", "EQUITY", "INCOME", "EXPENSE"],
  gl_book_status: ["ACTIVE", "ARCHIVED"],
  gl_fiscal_year_status: ["OPEN", "CLOSED"],
  gl_journal_source: ["manual", "opening_balance", "sales_invoice", "credit_note", "receipt", "purchase_bill", "debit_note", "payment", "bank_fee", "bank_transfer", "payroll_run", "expense_claim", "billing_invoice", "withholding", "fx_reval", "depreciation", "stock_move", "period_close"],
  gl_period_status: ["OPEN", "LOCKED"],
  gl_system_tag: ["cash", "bank", "undeposited", "ar_control", "ap_control", "grni", "sales", "other_income", "cogs", "opex", "salary", "equity_capital", "retained_earnings", "current_year_earnings", "fx_gain", "fx_loss", "rounding", "vat_input", "vat_output", "sales_tax_payable", "wht_payable", "gst_input_cgst", "gst_input_sgst", "gst_input_igst", "gst_input_utgst", "gst_input_cess", "gst_output_cgst", "gst_output_sgst", "gst_output_igst", "gst_output_utgst", "gst_output_cess", "psp_clearing", "razorpay_clearing", "stripe_clearing", "payment_fees", "net_pay_clearing", "statutory_payable", "fixed_asset", "accum_depreciation", "depreciation_expense", "deferred_revenue", "inventory", "inventory_write_off", "inventory_adjustment", "landed_cost"],
  guided_tour_progress_status: ["not_started", "in_progress", "completed", "dismissed"],
  helpdesk_queue: ["HR", "IT", "FINANCE", "ADMIN", "LEGAL"],
  hr_access_provisioning_action: ["grant", "revoke", "review"],
  hr_access_provisioning_status: ["pending", "completed", "verified", "failed"],
  hr_access_provisioning_trigger: ["joiner", "mover", "leaver", "manual"],
  hr_accommodation_status: ["requested", "under_review", "approved", "denied", "implemented"],
  hr_accommodation_task_status: ["pending", "in_progress", "completed"],
  hr_accommodation_type: ["equipment", "schedule", "workspace", "medical_restriction", "other"],
  hr_arrears_status: ["pending", "applied"],
  hr_benefit_category: ["health", "life", "accident", "retirement", "wellness", "perk", "other"],
  hr_benefit_status: ["draft", "active", "archived"],
  hr_case_category: ["grievance", "disciplinary", "harassment", "ethics", "performance", "workplace_conflict", "policy_violation", "other"],
  hr_case_severity: ["low", "medium", "high", "critical"],
  hr_case_status: ["open", "under_investigation", "resolved", "closed", "dismissed"],
  hr_claim_payout_route: ["payroll_payable", "finance_payable", "already_paid"],
  hr_claim_status: ["submitted", "in_review", "approved", "rejected", "paid"],
  hr_collective_agreement_status: ["active", "expired", "negotiating"],
  hr_comp_cycle_status: ["draft", "active", "calibrating", "approved", "closed"],
  hr_comp_recommendation_status: ["draft", "submitted", "calibrated", "approved"],
  hr_compliance_category: ["statutory_filing", "registration", "posting", "training", "audit", "other"],
  hr_compliance_event_status: ["pending", "done", "overdue"],
  hr_compliance_frequency: ["once", "monthly", "quarterly", "yearly"],
  hr_compliance_task_status: ["pending", "completed", "overdue"],
  hr_contract_status: ["active", "expiring", "ended", "renewed", "converted"],
  hr_contract_type: ["contractor", "consultant", "intern", "temporary", "agency", "freelancer"],
  hr_data_request_status: ["pending", "approved", "processing", "completed", "rejected", "partial"],
  hr_data_request_type: ["export", "delete", "anonymize", "correction"],
  hr_dependent_relationship: ["spouse", "child", "parent", "other"],
  hr_device_sync_status: ["success", "failed", "partial"],
  hr_disciplinary_action_type: ["verbal_warning", "written_warning", "final_warning", "suspension", "termination_recommended"],
  hr_effective_dated_change_status: ["draft", "approved", "applied"],
  hr_effective_dated_change_type: ["department", "manager", "location", "designation", "job_level", "employment_type", "compensation", "work_schedule", "policy_assignment"],
  hr_emergency_event_status: ["active", "resolved"],
  hr_emergency_event_type: ["office_closure", "disaster", "safety_check", "other"],
  hr_emergency_response_status: ["safe", "need_help", "no_response"],
  hr_employment_lifecycle_status: ["CANDIDATE", "PRE_JOINING", "ONBOARDING", "ACTIVE", "PROBATION", "CONFIRMED", "NOTICE", "EXITED", "ALUMNI", "SUSPENDED"],
  hr_enrollment_status: ["pending", "active", "waived", "terminated"],
  hr_enrollment_window_status: ["upcoming", "open", "closed"],
  hr_equity_grant_status: ["active", "exercised", "cancelled", "expired"],
  hr_equity_grant_type: ["ISO", "NSO", "RSU", "other"],
  hr_form_audience: ["internal", "public"],
  hr_form_status: ["draft", "active", "archived"],
  hr_form_submission_status: ["submitted", "in_review", "approved", "rejected"],
  hr_import_entity: ["employees", "leave_balances", "attendance", "assets", "document_metadata"],
  hr_import_row_status: ["valid", "error", "committed"],
  hr_import_status: ["validating", "previewed", "committing", "committed", "rolled_back", "failed"],
  hr_labor_case_status: ["open", "in_review", "resolved"],
  hr_leave_ledger_source: ["policy_accrual", "request", "cron", "manual", "import"],
  hr_leave_payroll_status: ["pending", "exported", "locked"],
  hr_leave_txn_type: ["accrual", "consumption", "carry_forward", "encashment", "expiry", "adjustment", "comp_off_earn", "comp_off_use", "reversal"],
  hr_legal_hold_item_type: ["employee_profile", "document", "case_evidence"],
  hr_legal_hold_status: ["active", "released"],
  hr_letter_type: ["offer", "appointment", "confirmation", "promotion", "transfer", "salary_revision", "warning", "experience", "relieving", "termination"],
  hr_loan_repayment_status: ["pending", "deducted", "paid", "skipped"],
  hr_payroll_adjustment_status: ["pending", "approved", "applied", "rejected"],
  hr_payroll_adjustment_type: ["arrears", "recovery", "correction"],
  hr_payroll_input_section: ["employee_master", "compensation", "attendance", "leave", "overtime", "reimbursement", "deduction", "lifecycle"],
  hr_payroll_input_status: ["open", "building", "built", "locked"],
  hr_policy_scope_type: ["organization", "country", "state", "location", "department", "team", "role", "job_level", "employment_type", "employee"],
  hr_policy_status: ["draft", "active", "archived"],
  hr_policy_type: ["leave", "attendance", "shift_roster", "overtime", "comp_off", "probation", "notice_period", "document_requirement", "approval", "expense", "travel", "asset", "wfh", "remote_work", "payroll_eligibility"],
  hr_poll_status: ["draft", "active", "closed"],
  hr_position_status: ["open", "filled", "frozen", "future"],
  hr_proxy_scope: ["approvals", "hr_admin", "manager_tasks"],
  hr_reorg_scenario_status: ["draft", "proposed", "applied"],
  hr_reporting_line_type: ["primary", "matrix", "dotted"],
  hr_retention_action: ["delete", "anonymize"],
  hr_retention_record_type: ["employee", "document", "case", "attendance", "payroll"],
  hr_safety_incident_severity: ["low", "medium", "high", "critical"],
  hr_safety_incident_status: ["open", "investigating", "mitigated", "closed"],
  hr_safety_incident_type: ["injury", "accident", "near_miss", "hazard", "environmental", "other"],
  hr_simulation_type: ["policy", "leave", "attendance", "approval", "payroll"],
  hr_template_kind: ["onboarding_checklist", "offboarding_checklist", "probation_review", "performance_review", "goal", "letter", "document_request", "email", "notification", "survey", "training", "asset_assignment", "exit_interview"],
  hr_template_status: ["draft", "review", "approved", "active", "archived"],
  hr_time_device_status: ["active", "inactive", "faulty"],
  hr_time_device_type: ["biometric", "rfid", "mobile", "other"],
  hr_union_membership_status: ["active", "inactive"],
  hr_variance_approval_status: ["pending", "approved", "rejected"],
  hr_webhook_delivery_status: ["pending", "delivered", "failed", "dead"],
  hr_work_auth_status: ["active", "expiring", "expired", "pending_renewal"],
  hr_work_auth_type: ["work_permit", "visa", "right_to_work", "citizenship_proof", "other"],
  hr_worker_type: ["FULL_TIME", "PART_TIME", "CONTRACTOR", "CONSULTANT", "INTERN", "TEMPORARY", "AGENCY", "FREELANCER"],
  hr_workflow_action: ["approved", "rejected", "reassigned", "escalated", "commented", "cancelled", "reopened"],
  hr_workflow_approver_type: ["direct_manager", "managers_manager", "hr_role", "finance_role", "department_head", "location_hr", "named_user", "dynamic_expression"],
  hr_workflow_instance_status: ["pending", "in_progress", "approved", "rejected", "cancelled", "reopened"],
  hr_workflow_object_type: ["leave_request", "attendance_regularization", "overtime_request", "comp_off_request", "expense_reimbursement", "travel_request", "employee_data_change", "document_review", "asset_request", "onboarding", "offboarding", "probation_confirmation", "promotion", "transfer", "salary_revision", "resignation", "termination", "grievance_case"],
  hr_workflow_status: ["draft", "active", "archived"],
  hr_workflow_step_mode: ["serial", "parallel_all", "parallel_any"],
  incentive_status: ["PENDING", "APPROVED", "REJECTED", "ADDED_TO_PAYROLL"],
  incident_follow_up_status: ["open", "in_progress", "done", "cancelled"],
  incident_severity: ["critical", "high", "medium", "low"],
  incident_status: ["detected", "investigating", "mitigating", "resolved", "postmortem", "closed"],
  intake_source: ["manual", "web_form", "email"],
  intake_status: ["pending", "accepted", "declined", "duplicate"],
  interview_result: ["PENDING", "PASSED", "FAILED", "NO_SHOW"],
  interview_type: ["PHONE", "VIDEO", "ONSITE", "TECHNICAL", "HR", "FINAL", "ASSESSMENT", "VOICE_SCREEN"],
  inv_3pl_status: ["DISCONNECTED", "CONNECTED", "ERROR"],
  inv_adj_reason: ["PURCHASE", "SALE", "RETURN", "DAMAGE", "EXPIRY", "THEFT", "RECOUNT", "OTHER", "SCRAP"],
  inv_adjustment_status: ["DRAFT", "PENDING_APPROVAL", "APPROVED", "PENDING_POST", "POSTED", "CANCELLED"],
  inv_ai_feedback_verdict: ["USEFUL", "WRONG", "STALE", "UNSAFE"],
  inv_ai_insight_status: ["NEW", "ACKNOWLEDGED", "DISMISSED"],
  inv_asn_status: ["DRAFT", "CONFIRMED", "IN_TRANSIT", "ARRIVED", "CLOSED", "CANCELLED"],
  inv_barcode_type: ["GTIN", "EAN13", "UPC", "CODE128", "QR", "OTHER"],
  inv_channel_delivery_status: ["PENDING", "PROCESSED", "FAILED", "DEAD"],
  inv_channel_job_kind: ["STOCK_PUSH", "STOCK_PULL", "ORDER_PULL", "ORDER_IMPORT", "SHIP_CONFIRM"],
  inv_channel_pub_status: ["PENDING", "PUBLISHED", "FAILED"],
  inv_channel_snapshot_diff_status: ["OPEN", "ACCEPTED", "DISMISSED"],
  inv_channel_snapshot_policy: ["RECORD_DIFFERENCE", "ALLOW_ADJUSTMENT"],
  inv_channel_status: ["ACTIVE", "PAUSED"],
  inv_channel_type: ["INTERNAL", "SHOPIFY", "WOOCOMMERCE", "MARKETPLACE", "B2B", "THREE_PL"],
  inv_costing_method: ["STANDARD", "WEIGHTED_AVERAGE", "FIFO"],
  inv_customer_return_disposition: ["RESTOCK", "QUARANTINE", "SCRAP", "RETURN_TO_VENDOR"],
  inv_cycle_count_status: ["PLANNED", "COUNTING", "REVIEW", "POSTED", "CANCELLED"],
  inv_dock_appointment_status: ["BOOKED", "ARRIVED", "COMPLETED", "CANCELLED", "NO_SHOW"],
  inv_dock_direction: ["INBOUND", "OUTBOUND"],
  inv_drug_schedule: ["OTC", "H", "H1", "X", "NARCOTIC"],
  inv_expiry_policy: ["BLOCK", "WARN", "ALLOW"],
  inv_facility_type: ["DARK_STORE", "WAREHOUSE", "YARD", "SITE_STORE"],
  inv_grn_discrepancy: ["SHORT", "OVER", "DAMAGED", "WRONG_ITEM"],
  inv_grn_quality: ["ACCEPTED", "REJECTED"],
  inv_grn_status: ["DRAFT", "COUNTING", "QUALITY_REVIEW", "POSTED", "CANCELLED"],
  inv_gst_mode: ["REGULAR", "COMPOSITION"],
  inv_handling_unit_kind: ["PALLET", "CARTON", "CAGE", "TOTE"],
  inv_handling_unit_status: ["OPEN", "CLOSED", "SHIPPED", "EMPTY"],
  inv_idempotency_status: ["IN_FLIGHT", "COMPLETED", "FAILED"],
  inv_import_row_status: ["PENDING", "APPLIED", "FAILED", "SKIPPED"],
  inv_inspection_plan_version_status: ["DRAFT", "ACTIVE", "SUPERSEDED"],
  inv_inspection_sampling_method: ["ALL", "PERCENTAGE", "FIXED_QUANTITY"],
  inv_job_status: ["PENDING", "VALIDATING", "RUNNING", "COMPLETED", "FAILED"],
  inv_labor_task_kind: ["PICK", "PUTAWAY", "COUNT", "RECEIVE"],
  inv_landed_cost_basis: ["VALUE", "QUANTITY"],
  inv_landed_cost_charge_type: ["FREIGHT", "DUTY", "INSURANCE", "HANDLING", "OTHER"],
  inv_landed_cost_status: ["DRAFT", "APPLIED"],
  inv_load_status: ["DRAFT", "DISPATCHED", "ARRIVED", "CLOSED", "CANCELLED"],
  inv_location_type: ["ZONE", "AISLE", "RACK", "BIN", "RECEIVING", "SHIPPING", "QUARANTINE", "SCRAP", "TRANSIT", "RETURNS"],
  inv_lot_status: ["ACTIVE", "EXPIRED", "BLOCKED", "CONSUMED", "RECALLED"],
  inv_material_family: ["CEMENT_AGGREGATE", "STEEL_REBAR", "BRICK_BLOCK", "TILE_STONE", "PAINT_COATING", "PLUMBING", "ELECTRICAL", "SANITARYWARE", "WOOD_PANEL", "GLASS_MIRROR", "HARDWARE_FASTENER", "ADHESIVE_CHEMICAL", "FALSE_CEILING", "LIGHTING", "OTHER"],
  inv_measure_mode: ["PIECES", "CATCH_WEIGHT"],
  inv_near_expiry_policy: ["ALLOW", "DEPRIORITIZE", "BLOCK"],
  inv_ownership: ["OWNED", "VENDOR", "CUSTOMER"],
  inv_package_status: ["OPEN", "CLOSED", "SHIPPED"],
  inv_pick_exception: ["SHORT", "NOT_FOUND", "DAMAGED", "SUBSTITUTED", "WRONG_LOCATION"],
  inv_pick_exception_resolution: ["ACCEPTED", "REJECTED"],
  inv_pick_exception_status: ["OPEN", "RESOLVED"],
  inv_pick_list_status: ["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED"],
  inv_platform_po_status: ["RECEIVED", "REJECTED", "ACCEPTED", "CANCELLED"],
  inv_po_status: ["DRAFT", "SENT", "PARTIAL", "RECEIVED", "CLOSED", "CANCELLED"],
  inv_product_status: ["ACTIVE", "INACTIVE", "DISCONTINUED"],
  inv_product_type: ["STOCKABLE", "CONSUMABLE", "SERVICE"],
  inv_project_status: ["PLANNING", "ACTIVE", "ON_HOLD", "COMPLETED", "CANCELLED"],
  inv_putaway_disposition: ["STORAGE", "QUARANTINE"],
  inv_putaway_status: ["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED"],
  inv_qc_provider: ["BLINKIT", "INSTAMART", "ZEPTO"],
  inv_qty_input_mode: ["WHOLE", "DECIMAL", "SCALE"],
  inv_quality_disposition: ["RELEASE_TO_AVAILABLE", "QUARANTINE", "RETURN_TO_VENDOR", "SCRAP"],
  inv_quality_hold_status: ["ACTIVE", "RELEASED"],
  inv_quality_inspection_status: ["PENDING", "IN_PROGRESS", "PASSED", "FAILED", "DISPOSITION_REQUIRED", "COMPLETED", "CANCELLED"],
  inv_quantity_bucket: ["ON_HAND", "BLOCKED", "QUALITY_HOLD"],
  inv_reason_category: ["ADJUSTMENT", "COUNT", "SCRAP", "RETURN", "TRANSFER", "OTHER"],
  inv_recall_status: ["OPEN", "IN_PROGRESS", "CLOSED"],
  inv_requirement_status: ["DRAFT", "REQUESTED", "RESERVED", "PARTIALLY_FULFILLED", "FULFILLED", "CANCELLED"],
  inv_reservation_status: ["ACTIVE", "CONSUMED", "RELEASED", "EXPIRED"],
  inv_reservation_strategy: ["MANUAL", "AUTO_ON_CONFIRM", "FEFO", "FIFO"],
  inv_return_status: ["DRAFT", "APPROVED", "POSTED", "CANCELLED"],
  inv_sale_mode: ["PACKED", "LOOSE"],
  inv_serial_status: ["IN_STOCK", "RESERVED", "SHIPPED", "RETURNED", "SCRAPPED", "QUARANTINE"],
  inv_shipment_status: ["DRAFT", "PACKED", "LABEL_CREATED", "SHIPPED", "DELIVERED", "CANCELLED"],
  inv_slotting_match: ["VELOCITY_CLASS", "CATEGORY", "PRODUCT_VARIANT"],
  inv_slotting_recommendation_status: ["PENDING", "APPROVED", "DISMISSED", "SUPERSEDED"],
  inv_so_status: ["DRAFT", "CONFIRMED", "PARTIALLY_RESERVED", "RESERVED", "PICKED", "PACKED", "SHIPPED", "PARTIALLY_SHIPPED", "INVOICED", "CANCELLED", "CLOSED"],
  inv_tax_treatment: ["TAXABLE", "EXEMPT", "NIL_RATED", "ZERO_RATED", "NON_GST"],
  inv_tracking_method: ["NONE", "LOT", "SERIAL"],
  inv_transfer_status: ["PENDING", "RESERVED", "IN_TRANSIT", "COMPLETED", "CANCELLED"],
  inv_txn_type: ["PURCHASE", "SALE", "ADJUSTMENT_IN", "ADJUSTMENT_OUT", "TRANSFER_IN", "TRANSFER_OUT", "RETURN_IN", "RETURN_OUT", "GRN", "OPENING_BALANCE", "VENDOR_RETURN", "CUSTOMER_RETURN", "CYCLE_COUNT_GAIN", "CYCLE_COUNT_LOSS", "SCRAP", "QUARANTINE_IN", "QUARANTINE_OUT", "RESERVATION_CREATE", "RESERVATION_RELEASE", "RESERVATION_CONSUME", "KIT_ASSEMBLE_IN", "KIT_ASSEMBLE_OUT", "KIT_DISASSEMBLE_IN", "KIT_DISASSEMBLE_OUT"],
  inv_velocity_class: ["A", "B", "C"],
  inv_vendor_return_reason: ["DAMAGED", "WRONG_ITEM", "EXCESS", "EXPIRED", "QUALITY_REJECTED"],
  inv_webhook_event_status: ["PENDING", "DELIVERED", "FAILED"],
  invitation_status: ["PENDING", "ACCEPTED", "DECLINED", "EXPIRED", "REVOKED"],
  invoice_line_detail: ["summary", "raw"],
  invoice_status: ["DRAFT", "ISSUED", "SENT", "PARTIALLY_PAID", "OVERDUE", "PAID", "FAILED", "VOIDED"],
  job_posting_status: ["DRAFT", "OPEN", "PAUSED", "CLOSED", "FILLED"],
  kb_audience: ["internal", "public", "mixed"],
  kb_space_role: ["viewer", "commenter", "editor", "publisher", "admin"],
  kb_translation_status: ["draft", "in_progress", "translated", "published", "outdated"],
  lead_email_direction: ["sent", "received"],
  lead_task_status: ["open", "done"],
  leave_status: ["PENDING", "APPROVED", "REJECTED", "CANCELLED"],
  loan_status: ["PENDING", "APPROVED", "ACTIVE", "REPAID", "REJECTED"],
  managed_product_status: ["active", "archived"],
  meeting_status: ["SCHEDULED", "COMPLETED", "CANCELLED", "NO_SHOW"],
  meeting_type: ["meeting", "standup", "retro", "planning", "review"],
  membership_status: ["INVITED", "ACTIVE", "SUSPENDED", "LEFT"],
  module_setup_checklist_status: ["not_started", "in_progress", "completed"],
  module_status: ["backlog", "planned", "in-progress", "completed", "paused", "cancelled"],
  notification_category: ["SECURITY", "CRM", "HRMS", "BILLING", "AI", "PROJECTS", "WORKFLOW", "MARKETING", "SYSTEM", "CHAT", "PAYROLL", "RECRUITMENT", "KNOWLEDGE", "SIGN", "INVENTORY", "SURVEYS", "CALENDAR", "SUPPORT", "ACCOUNTING"],
  notification_channel: ["IN_APP", "EMAIL", "PUSH", "SMS", "WHATSAPP", "WEBHOOK"],
  notification_consent_source: ["USER", "ADMIN", "IMPORT", "SIGNUP", "API"],
  notification_consent_state: ["GRANTED", "WITHDRAWN"],
  notification_delivery_status: ["PENDING", "QUEUED", "SENDING", "SENT", "DELIVERED", "READ", "CLICKED", "FAILED", "BOUNCED", "SUPPRESSED", "CANCELLED", "DEAD"],
  notification_legal_basis: ["CONSENT", "CONTRACT", "LEGITIMATE_INTEREST", "LEGAL_OBLIGATION"],
  notification_policy_scope: ["ORG", "ROLE", "DEPARTMENT", "TEAM", "PROJECT"],
  notification_priority: ["LOW", "NORMAL", "HIGH", "CRITICAL"],
  notification_provider: ["SMTP", "TWILIO", "META_WHATSAPP", "WEBHOOK", "WEB_PUSH", "INTERNAL", "SANDBOX"],
  notification_queue_status: ["PENDING", "LOCKED", "DONE", "FAILED", "DEAD"],
  notification_quiet_hours_behavior: ["respect", "bypass_if_high", "always_bypass"],
  notification_suppression_reason: ["DEDUPE", "MUTE", "UNSUBSCRIBE", "INVALID_RECIPIENT", "RATE_LIMIT", "QUIET_HOURS", "NO_PROVIDER", "CONSENT_MISSING", "CHANNEL_DISABLED", "COST_LIMIT", "NO_ACCESS"],
  notification_type: ["INFO", "SUCCESS", "WARNING", "ERROR"],
  nps_category: ["promoter", "passive", "detractor"],
  nps_survey_status: ["draft", "active", "closed"],
  okr_goal_level: ["company", "team", "individual"],
  okr_goal_status: ["not_started", "on_track", "at_risk", "off_track", "completed"],
  okr_kr_metric: ["number", "percentage", "currency", "boolean"],
  onboarding_doc_status: ["PENDING", "IN_PROGRESS", "SUBMITTED", "APPROVED"],
  onboarding_document_status: ["PENDING", "SUBMITTED", "APPROVED", "REJECTED", "RE_UPLOAD_REQUESTED"],
  onboarding_flow_session_status: ["not_started", "in_progress", "completed", "skipped", "abandoned"],
  onboarding_flow_step_status: ["todo", "in_progress", "done", "skipped", "blocked"],
  onboarding_flow_type: ["org_setup", "member_setup", "employee_onboarding", "module_setup", "guided_tour", "payment_setup"],
  onboarding_status: ["PENDING", "IN_PROGRESS", "COMPLETED", "REJECTED"],
  org_size: ["1-10", "11-50", "51-200", "201-1000", "1000+"],
  organization_status: ["ACTIVE", "ARCHIVED", "PURGE_SCHEDULED", "PURGED"],
  outbox_delivery_state: ["PENDING", "IN_FLIGHT", "DELIVERED", "DEAD", "SUPPRESSED"],
  party_kind: ["PERSON", "ORGANISATION"],
  party_role: ["customer", "vendor", "both"],
  party_type: ["CUSTOMER", "VENDOR", "PARTNER", "BOTH"],
  pay_frequency: ["MONTHLY", "SEMI_MONTHLY", "BI_WEEKLY", "WEEKLY"],
  payment_environment: ["test", "live"],
  payment_manual_method_status: ["enabled", "missing_instructions", "disabled"],
  payment_provider_status: ["not_configured", "test_mode_ready", "needs_credentials", "needs_business_details", "needs_kyc", "kyc_pending", "kyc_rejected", "needs_webhook", "webhook_failing", "test_payment_required", "ready_for_live", "live", "degraded", "disabled"],
  payment_test_transaction_status: ["created", "pending", "succeeded", "failed"],
  payment_webhook_endpoint_status: ["not_verified", "verified", "failing"],
  payment_webhook_processing_status: ["received", "processed", "failed", "ignored_duplicate"],
  payroll_approval_status: ["PENDING", "APPROVED", "REJECTED"],
  payroll_bank_batch_status: ["DRAFT", "GENERATED", "SENT", "PARTIALLY_PAID", "PAID", "FAILED"],
  payroll_bank_item_status: ["PENDING", "SENT", "PAID", "FAILED", "HELD"],
  payroll_calendar_event_type: ["ATTENDANCE_CUTOFF", "REIMBURSEMENT_CUTOFF", "DECLARATION_CUTOFF", "PREVIEW_DUE", "APPROVAL_DEADLINE", "PAY_DATE", "PUBLISH_DATE"],
  payroll_command_status: ["IN_FLIGHT", "SUCCEEDED", "FAILED"],
  payroll_entity_status: ["ACTIVE", "INACTIVE", "ARCHIVED"],
  payroll_exception_severity: ["BLOCKER", "WARNING", "INFO"],
  payroll_exception_status: ["OPEN", "RESOLVED", "OVERRIDDEN"],
  payroll_input_source: ["ATTENDANCE", "LEAVE", "TIMESHEET", "UPLOAD", "MANUAL"],
  payroll_job_status: ["PENDING", "RUNNING", "SUCCEEDED", "FAILED", "DEAD_LETTER"],
  payroll_journal_batch_status: ["DRAFT", "POSTED", "EXPORTED", "REVERSED", "FAILED"],
  payroll_journal_recon_status: ["UNRECONCILED", "RECONCILED", "DISPUTED"],
  payroll_loan_adjustment_type: ["SKIP_EMI", "EXTRA_RECOVERY", "FORECLOSURE", "MANUAL_ADJUST"],
  payroll_period_status: ["OPEN", "CUTOFF", "LOCKED", "CLOSED"],
  payroll_policy_status: ["DRAFT", "ACTIVE", "SUPERSEDED", "ARCHIVED"],
  payroll_run_event_type: ["GENERATED", "RECALCULATED", "APPROVAL_SUBMITTED", "APPROVED", "REJECTED", "LOCKED", "REOPENED", "MARKED_PAID", "PAYSLIPS_PUBLISHED", "BANK_BATCH_GENERATED", "BANK_BATCH_SENT", "BANK_ITEM_PAID", "BANK_ITEM_FAILED", "EXCEPTION_OVERRIDDEN", "INPUT_OVERRIDDEN", "CLOSED"],
  payroll_run_status: ["PREPARING", "DRAFT", "PREVIEW_READY", "EXCEPTIONS_FOUND", "PENDING_APPROVAL", "APPROVED", "LOCKED", "PAID", "PAYSLIPS_PUBLISHED", "CLOSED", "REOPENED"],
  payroll_tax_window_status: ["DRAFT", "OPEN", "CLOSED", "LOCKED"],
  payroll_template_category: ["INDIAN_STANDARD", "INDIAN_STARTUP", "CONTRACTOR", "SALES_INCENTIVE", "GLOBAL_REMOTE", "HOURLY", "MANUFACTURING", "STAFFING", "EXECUTIVE", "CUSTOM", "COUNTRY_STANDARD"],
  payroll_worker_type: ["EMPLOYEE", "CONTRACTOR", "CONSULTANT", "INTERN", "EOR"],
  payslip_layout: ["CLASSIC", "MODERN", "COMPLIANCE"],
  payslip_publication_status: ["PENDING", "PUBLISHED", "FAILED"],
  payslip_publish_channel: ["PORTAL", "EMAIL"],
  pip_status: ["ACTIVE", "EXTENDED", "COMPLETED", "TERMINATED"],
  portal_audience: ["CLIENT_PORTAL"],
  portal_grant_status: ["ACTIVE", "SUSPENDED", "REVOKED", "EXPIRED"],
  portal_invitation_status: ["PENDING", "ACCEPTED", "REVOKED", "EXPIRED"],
  portal_membership_status: ["PENDING", "ACTIVE", "SUSPENDED", "REVOKED"],
  project_meeting_status: ["scheduled", "in_progress", "completed", "cancelled"],
  project_portfolio_health: ["on_track", "at_risk", "off_track"],
  project_portfolio_status: ["active", "on_hold", "completed", "archived"],
  project_status: ["ACTIVE", "COMPLETED", "ARCHIVED"],
  project_update_audience: ["internal", "client"],
  project_update_status: ["draft", "published"],
  quote_status: ["DRAFT", "SENT", "ACCEPTED", "REJECTED", "EXPIRED"],
  referral_status: ["PENDING", "SIGNED_UP", "ACTIVATED", "REWARDED", "EXPIRED"],
  reimbursement_status: ["PENDING", "APPROVED", "REJECTED", "PAID"],
  relocation_checksum_scope: ["table", "partition", "object", "index"],
  resignation_status: ["SUBMITTED", "PENDING_HR", "HR_APPROVED", "FINAL_APPROVED", "IN_PROGRESS", "APPROVED", "WITHDRAWN", "COMPLETED", "REJECTED"],
  revenue_event_type: ["new_subscription", "upgrade", "downgrade", "churn", "reactivation", "addon_purchase", "refund"],
  review_cycle_status: ["DRAFT", "ACTIVE", "COMPLETED", "CANCELLED"],
  review_status: ["DRAFT", "IN_PROGRESS", "COMPLETED", "ARCHIVED"],
  reward_point_source: ["kudos", "badge", "manual", "redemption"],
  risk_impact: ["low", "medium", "high"],
  risk_probability: ["low", "medium", "high"],
  risk_status: ["open", "mitigating", "monitoring", "accepted", "closed"],
  roadmap_status: ["planned", "in_progress", "completed", "cancelled"],
  salary_component_calc_method: ["FIXED", "PERCENT_OF_BASIC", "PERCENT_OF_GROSS", "FORMULA", "ATTENDANCE_BASED", "TIMESHEET_BASED", "MANUAL"],
  salary_component_type: ["EARNING", "DEDUCTION", "EMPLOYER_CONTRIBUTION", "REIMBURSEMENT", "TAX", "ADJUSTMENT"],
  salary_profile_status: ["UPCOMING", "ACTIVE", "SUPERSEDED"],
  scoring_operator: ["eq", "gt", "lt", "contains", "in"],
  sign_actor_type: ["internal_user", "external_signer", "system"],
  sign_audit_event_type: ["envelope_created", "envelope_updated", "envelope_deleted", "document_uploaded", "recipient_added", "recipient_updated", "recipient_removed", "field_added", "field_updated", "field_deleted", "envelope_validated", "envelope_sent", "email_delivered", "email_bounced", "reminder_sent", "signing_link_opened", "authentication_passed", "authentication_failed", "consent_accepted", "document_viewed", "field_completed", "signature_adopted", "recipient_completed", "recipient_declined", "recipient_delegated", "envelope_corrected", "envelope_voided", "envelope_expired", "envelope_extended", "envelope_completed", "final_pdf_generated", "certificate_generated", "certificate_regenerated", "document_downloaded", "template_created", "template_published", "template_archived", "bulk_job_created", "bulk_job_completed", "bulk_job_cancelled", "public_form_published", "public_form_submitted", "admin_setting_changed"],
  sign_auth_method: ["email_link", "access_code", "otp_email", "otp_sms", "sso", "passkey", "kba", "id_verification"],
  sign_bulk_job_status: ["pending", "validating", "running", "completed", "failed", "cancelled"],
  sign_bulk_row_status: ["pending", "success", "failed"],
  sign_cc_timing: ["on_send", "on_complete"],
  sign_conversion_status: ["pending", "converted", "failed", "not_needed"],
  sign_envelope_status: ["draft", "ready_to_send", "sent", "delivered", "partially_completed", "completed", "declined", "voided", "expired", "correction_required", "failed"],
  sign_field_type: ["signature", "initials", "date_signed", "text", "multiline", "email", "name", "company", "title", "checkbox", "radio", "dropdown", "attachment", "stamp", "strikethrough", "readonly_merge"],
  sign_recipient_status: ["pending", "invited", "viewed", "authenticated", "signing", "completed", "declined", "delegated", "bounced", "expired"],
  sign_recipient_type: ["signer", "approver", "cc", "viewer", "in_person_host", "internal_reviewer"],
  sign_routing_mode: ["parallel", "sequential", "mixed"],
  sign_signature_asset_type: ["signature", "initials", "stamp"],
  sign_signature_method: ["drawn", "typed", "uploaded", "saved"],
  sign_template_status: ["draft", "published", "archived"],
  sign_watermark_scope: ["tenant", "template", "envelope"],
  sla_applies_to: ["lead", "deal", "both"],
  sla_priority: ["low", "medium", "high", "urgent"],
  state_group: ["backlog", "unstarted", "started", "completed", "cancelled"],
  subscription_plan: ["STARTER", "PROFESSIONAL", "ENTERPRISE"],
  subscription_status: ["TRIAL", "ACTIVE", "PAST_DUE", "CANCELLED", "SUSPENDED", "EXPIRED"],
  succession_readiness: ["ready_now", "1_2_years", "3_plus"],
  support_activity_action: ["created", "status_changed", "priority_changed", "assignee_changed", "replied", "internal_note", "resolved", "reopened", "merged", "linked", "split", "snoozed", "unsnoozed"],
  support_channel_type: ["email", "chat", "whatsapp", "sms"],
  support_external_entity_type: ["project", "invoice", "calendar_event", "chat_channel"],
  support_saved_view_visibility: ["personal", "team", "global"],
  support_suggestion_status: ["pending", "accepted", "rejected"],
  support_suggestion_type: ["summary", "sentiment", "category", "priority", "spam", "reply", "macro", "kb_article", "duplicate", "handoff_summary", "root_cause_cluster"],
  support_ticket_link_relation: ["duplicate", "related", "split"],
  support_ticket_priority: ["LOW", "MEDIUM", "HIGH", "URGENT"],
  support_ticket_status: ["OPEN", "IN_PROGRESS", "WAITING", "RESOLVED", "CLOSED"],
  survey_assessment_attempt_status: ["not_started", "in_progress", "submitted", "passed", "failed", "expired"],
  survey_automation_event_status: ["pending", "processed", "failed", "skipped"],
  survey_collector_status: ["active", "paused", "closed", "expired"],
  survey_collector_type: ["public_link", "email", "qr", "embed", "popup", "crm_campaign", "hr_audience", "support_trigger", "live_session", "manual_access_code"],
  survey_form_mode: ["survey", "assessment", "live_session", "lead_qualification", "custom"],
  survey_form_status: ["draft", "testing", "published", "paused", "closed", "archived"],
  survey_live_session_status: ["draft", "waiting", "active", "paused", "ended"],
  survey_participant_status: ["invited", "delivered", "opened", "started", "partial", "completed", "disqualified", "bounced", "unsubscribed", "expired"],
  survey_question_type: ["short_text", "long_text", "single_select", "multi_select", "dropdown", "rating", "star_rating", "nps", "number", "email", "phone", "date", "matrix", "likert", "ranking", "slider", "yes_no", "consent", "content_block"],
  survey_response_session_status: ["in_progress", "submitted", "invalid", "excluded", "deleted_by_policy"],
  survey_status: ["DRAFT", "ACTIVE", "CLOSED"],
  task_entity_type: ["LEAD", "DEAL", "CONTACT", "PROJECT"],
  task_status: ["pending", "completed", "cancelled"],
  tax_category: ["standard", "reduced", "super_reduced", "zero", "exempt", "out_of_scope", "reverse_charge"],
  tax_gl_role: ["output_payable", "input_recoverable", "reverse_charge_output", "reverse_charge_input", "blocked_input", "withheld"],
  tax_regime: ["GST_IN", "VAT_EU", "VAT_GB", "VAT_GCC", "GST_SG", "GST_AU", "GST_HST_CA", "SALES_TAX_US", "PAN_IN", "TAN_IN", "EIN_US", "GENERIC"],
  tax_regime_type: ["OLD", "NEW"],
  tax_registration_owner: ["book", "party"],
  tax_supply_nature: ["domestic_b2b", "domestic_b2c", "export", "import", "intra_community", "oss_b2c", "reverse_charge", "outside_scope"],
  template_approval_status: ["NOT_REQUIRED", "PENDING", "APPROVED", "REJECTED"],
  termination_status: ["DRAFT", "PENDING_FINAL", "APPROVED", "REJECTED", "SENT", "COMPLETED"],
  test_case_automation_status: ["manual", "automated", "planned"],
  test_case_priority: ["low", "medium", "high"],
  test_result_status: ["not_run", "passed", "failed", "blocked", "skipped"],
  test_run_status: ["not_started", "in_progress", "completed", "aborted"],
  ticket_activity_action: ["created", "status_changed", "priority_changed", "assignee_changed", "title_changed", "sprint_changed", "due_date_changed", "comment_added", "comment_updated", "comment_deleted", "label_changed", "estimate_changed", "cycle_changed", "type_changed"],
  ticket_priority: ["LOW", "MEDIUM", "HIGH", "URGENT"],
  ticket_status: ["TODO", "IN_PROGRESS", "IN_REVIEW", "DONE"],
  ticket_type: ["EPIC", "STORY", "TASK", "BUG"],
  timer_session_source: ["WEB", "MOBILE", "DESKTOP", "API"],
  timer_session_status: ["RUNNING", "PAUSED", "STOPPED", "CONVERTED", "DISCARDED"],
  timesheet_approval_mode: ["MANAGER", "AUTO", "MULTI_LEVEL"],
  timesheet_approver_source: ["REPORTING_MANAGER", "PROJECT_MANAGER"],
  timesheet_billing_type: ["BILLABLE", "NON_BILLABLE", "FIXED"],
  timesheet_budget_status: ["ACTIVE", "ARCHIVED"],
  timesheet_budget_type: ["HOURS", "AMOUNT"],
  timesheet_entry_source: ["MANUAL", "TIMER", "API", "IMPORT"],
  timesheet_entry_status: ["PENDING", "APPROVED", "REJECTED"],
  timesheet_export_format: ["CSV", "XLSX", "JSON", "PDF"],
  timesheet_export_status: ["PENDING", "PROCESSING", "COMPLETED", "FAILED"],
  timesheet_export_type: ["PAYROLL", "BILLING", "INVOICE_DRAFT"],
  timesheet_invoicing_status: ["UNINVOICED", "INVOICE_DRAFTED", "INVOICED"],
  timesheet_pay_period: ["WEEKLY", "BIWEEKLY", "SEMIMONTHLY", "MONTHLY"],
  timesheet_payroll_status: ["UNPROCESSED", "EXPORTED"],
  timesheet_period_status: ["OPEN", "DRAFT", "SUBMITTED", "APPROVED", "REJECTED", "LOCKED"],
  timesheet_rate_source: ["RATE_CARD", "PROJECT_MEMBER"],
  timesheet_rounding_rule: ["NONE", "NEAREST_5", "NEAREST_6", "NEAREST_10", "NEAREST_15", "ROUND_UP", "ROUND_DOWN"],
  view_layout: ["board", "list", "table", "calendar", "gantt"],
  wfh_request_status: ["PENDING", "APPROVED", "REJECTED"],
  whiteboard_share_role: ["viewer", "editor"],
  whiteboard_visibility: ["project", "private", "public"],
  work_item_relation_type: ["blocks", "blocked_by", "duplicate_of", "relates_to"],
  worker_engagement_status: ["PLANNED", "ACTIVE", "COMPLETED", "TERMINATED", "CANCELLED"],
  workflow_approval_status: ["pending", "approved", "rejected", "delegated", "expired"],
  workflow_execution_status: ["pending", "running", "waiting", "completed", "failed", "cancelled", "timed_out", "dead_lettered"],
  workflow_node_type: ["trigger", "condition", "approval", "action", "delay", "loop", "ai_action", "integration", "script", "end"],
  workflow_status: ["draft", "published", "disabled", "archived"],
  workflow_trigger_type: ["event", "schedule", "webhook", "api", "manual"],
} as const;

export type DbEnumName = keyof typeof DB_ENUMS;
export type DbEnumMember<N extends DbEnumName> = (typeof DB_ENUMS)[N][number];
