/**
 * Complete HRMS module catalogue — every navigable surface under /hr.
 * Used by the People Hub module browser and settings-style indexes.
 */
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Award,
  BadgeCheck,
  Banknote,
  BarChart3,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileCheck,
  FileText,
  Fingerprint,
  FolderOpen,
  FormInput,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  HardDrive,
  HeartPulse,
  HelpCircle,
  IdCard,
  LayoutDashboard,
  LineChart,
  MapPin,
  Megaphone,
  MessageSquare,
  Network,
  Package,
  Plane,
  Plus,
  Scale,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  Sparkles,
  Target,
  Timer,
  TrendingUp,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
  Workflow,
  Wrench,
} from "lucide-react";

export type HrModuleTone =
  | "blue"
  | "emerald"
  | "amber"
  | "rose"
  | "violet"
  | "sky"
  | "slate";

export type HrModuleCategoryId =
  | "people"
  | "time"
  | "pay"
  | "talent"
  | "learning"
  | "ops"
  | "compliance"
  | "recruitment"
  | "settings";

export interface HrModuleDef {
  id: string;
  label: string;
  description: string;
  href: string;
  icon: LucideIcon;
  tone: HrModuleTone;
  category: HrModuleCategoryId;
  /** Highlight on hub */
  featured?: boolean;
}

export interface HrModuleCategory {
  id: HrModuleCategoryId;
  label: string;
  description: string;
}

export const HR_CATEGORIES: HrModuleCategory[] = [
  {
    id: "people",
    label: "People & org",
    description: "Directory, structure, and lifecycle",
  },
  {
    id: "time",
    label: "Time & attendance",
    description: "Presence, leave, shifts, and schedules",
  },
  {
    id: "pay",
    label: "Pay & expenses",
    description: "Compensation, claims, and cost",
  },
  {
    id: "talent",
    label: "Performance & talent",
    description: "Goals, feedback, and growth",
  },
  {
    id: "learning",
    label: "Learning",
    description: "Courses, training, and skills",
  },
  {
    id: "recruitment",
    label: "Recruitment",
    description: "Jobs, pipeline, and offers",
  },
  {
    id: "ops",
    label: "Workplace ops",
    description: "Assets, helpdesk, travel, and devices",
  },
  {
    id: "compliance",
    label: "Compliance & risk",
    description: "Policies, safety, and governance",
  },
  {
    id: "settings",
    label: "Settings & automation",
    description: "Configure HR for your org",
  },
];

/** Every HR module — keep in sync with app/(authenticated)/hr routes */
export const HR_MODULES: HrModuleDef[] = [
  // People
  {
    id: "hub",
    label: "People Hub",
    description: "Headcount, directory snapshot, and shortcuts",
    href: "/hr",
    icon: LayoutDashboard,
    tone: "blue",
    category: "people",
    featured: true,
  },
  {
    id: "employees",
    label: "Employee directory",
    description: "Browse and manage every team member",
    href: "/hr/employees",
    icon: Users,
    tone: "blue",
    category: "people",
    featured: true,
  },
  {
    id: "onboarding",
    label: "Onboarding",
    description: "Single & bulk hire, documents, probation",
    href: "/hr/onboarding",
    icon: UserPlus,
    tone: "emerald",
    category: "people",
    featured: true,
  },
  {
    id: "org-chart",
    label: "Org chart",
    description: "Reporting structure and hierarchy",
    href: "/hr/org-chart",
    icon: Network,
    tone: "violet",
    category: "people",
  },
  {
    id: "org",
    label: "Organization",
    description: "Departments, teams, and structure",
    href: "/hr/org",
    icon: Building2,
    tone: "slate",
    category: "people",
  },
  {
    id: "positions",
    label: "Positions",
    description: "Role definitions and headcount seats",
    href: "/hr/positions",
    icon: IdCard,
    tone: "sky",
    category: "people",
  },
  {
    id: "find-expert",
    label: "Find an expert",
    description: "Search skills across the company",
    href: "/hr/employees/find-expert",
    icon: Sparkles,
    tone: "violet",
    category: "people",
  },
  {
    id: "skills-matrix",
    label: "Skills matrix",
    description: "Cross-team capability heatmap",
    href: "/hr/employees/skills-matrix",
    icon: Share2,
    tone: "blue",
    category: "people",
  },
  {
    id: "skills",
    label: "Skills",
    description: "Skill catalogue and levels",
    href: "/hr/skills",
    icon: Award,
    tone: "amber",
    category: "people",
  },
  {
    id: "exit",
    label: "Exit",
    description: "Resignations and offboarding workflows",
    href: "/hr/exit",
    icon: UserMinus,
    tone: "rose",
    category: "people",
  },
  {
    id: "termination",
    label: "Termination",
    description: "End employment with audit trail",
    href: "/hr/termination",
    icon: UserMinus,
    tone: "rose",
    category: "people",
  },
  {
    id: "fnf",
    label: "Full & final",
    description: "Settlement and clearance",
    href: "/hr/fnf",
    icon: FileCheck,
    tone: "amber",
    category: "people",
  },
  {
    id: "identity",
    label: "Identity",
    description: "IDs, verification, and records",
    href: "/hr/identity",
    icon: Fingerprint,
    tone: "slate",
    category: "people",
  },
  {
    id: "contingent",
    label: "Contingent workforce",
    description: "Contractors and temporary staff",
    href: "/hr/contingent",
    icon: UsersRound,
    tone: "sky",
    category: "people",
  },
  {
    id: "delegations",
    label: "Delegations",
    description: "Acting managers and coverage",
    href: "/hr/delegations",
    icon: GitBranch,
    tone: "violet",
    category: "people",
  },
  {
    id: "engagement",
    label: "Engagement",
    description: "Pulse, surveys, and sentiment",
    href: "/hr/engagement",
    icon: HeartPulse,
    tone: "rose",
    category: "people",
  },
  {
    id: "retention",
    label: "Retention",
    description: "Flight risk and stay insights",
    href: "/hr/retention",
    icon: TrendingUp,
    tone: "emerald",
    category: "people",
  },
  {
    id: "announcements",
    label: "Announcements",
    description: "Company-wide people broadcasts",
    href: "/hr/announcements",
    icon: Megaphone,
    tone: "amber",
    category: "people",
  },
  {
    id: "handbook",
    label: "Handbook",
    description: "Employee handbook & policies hub",
    href: "/hr/handbook",
    icon: BookOpen,
    tone: "blue",
    category: "people",
  },
  {
    id: "workforce",
    label: "Workforce",
    description: "Planning and workforce overview",
    href: "/hr/workforce",
    icon: Users,
    tone: "blue",
    category: "people",
  },

  // Time
  {
    id: "attendance",
    label: "Attendance",
    description: "Daily presence and logs",
    href: "/hr/attendance",
    icon: CalendarCheck,
    tone: "emerald",
    category: "time",
    featured: true,
  },
  {
    id: "leaves",
    label: "Leaves",
    description: "Requests, balances, and approvals",
    href: "/hr/leaves",
    icon: CalendarOff,
    tone: "amber",
    category: "time",
    featured: true,
  },
  {
    id: "leaves-analytics",
    label: "Leave analytics",
    description: "Trends and leave patterns",
    href: "/hr/leaves/analytics",
    icon: LineChart,
    tone: "amber",
    category: "time",
  },
  {
    id: "leave-policies",
    label: "Leave policies",
    description: "Types, accrual, and rules",
    href: "/hr/leave-policies",
    icon: ClipboardList,
    tone: "slate",
    category: "time",
  },
  {
    id: "holidays",
    label: "Holidays",
    description: "Org holiday calendar",
    href: "/hr/holidays",
    icon: CalendarDays,
    tone: "sky",
    category: "time",
  },
  {
    id: "comp-off",
    label: "Comp-off",
    description: "Compensatory off requests",
    href: "/hr/comp-off",
    icon: CalendarClock,
    tone: "violet",
    category: "time",
  },
  {
    id: "shifts",
    label: "Shifts",
    description: "Shift templates and patterns",
    href: "/hr/shifts",
    icon: Clock,
    tone: "blue",
    category: "time",
  },
  {
    id: "rosters",
    label: "Rosters",
    description: "Team schedules and assignments",
    href: "/hr/rosters",
    icon: Calendar,
    tone: "blue",
    category: "time",
  },
  {
    id: "overtime",
    label: "Overtime",
    description: "OT requests and tracking",
    href: "/hr/overtime",
    icon: Timer,
    tone: "amber",
    category: "time",
  },
  {
    id: "work-logs",
    label: "Work logs",
    description: "Daily work logging",
    href: "/hr/work-logs",
    icon: ClipboardCheck,
    tone: "emerald",
    category: "time",
  },
  {
    id: "biometric",
    label: "Biometric",
    description: "Device punches and sync",
    href: "/hr/biometric",
    icon: Fingerprint,
    tone: "slate",
    category: "time",
  },
  {
    id: "geofencing",
    label: "Geofencing",
    description: "Location-based attendance",
    href: "/hr/geofencing",
    icon: MapPin,
    tone: "rose",
    category: "time",
  },
  {
    id: "approvals",
    label: "Approvals",
    description: "Cross-module approval inbox",
    href: "/hr/approvals",
    icon: BadgeCheck,
    tone: "emerald",
    category: "time",
    featured: true,
  },

  // Pay
  {
    id: "expenses",
    label: "Expenses",
    description: "Claims and reimbursements",
    href: "/hr/expenses",
    icon: Wallet,
    tone: "emerald",
    category: "pay",
    featured: true,
  },
  {
    id: "reimbursements",
    label: "Reimbursements",
    description: "Approved payout tracking",
    href: "/hr/reimbursements",
    icon: Banknote,
    tone: "emerald",
    category: "pay",
  },
  {
    id: "benefits",
    label: "Benefits",
    description: "Plans and enrollments",
    href: "/hr/benefits",
    icon: Gift,
    tone: "violet",
    category: "pay",
  },
  {
    id: "equity",
    label: "Equity",
    description: "ESOP and equity grants",
    href: "/hr/equity",
    icon: TrendingUp,
    tone: "blue",
    category: "pay",
  },
  {
    id: "compensation-planning",
    label: "Compensation planning",
    description: "Cycles and band planning",
    href: "/hr/compensation-planning",
    icon: Banknote,
    tone: "amber",
    category: "pay",
  },
  {
    id: "workforce-cost",
    label: "Workforce cost",
    description: "Cost analytics and headcount $",
    href: "/hr/workforce-cost",
    icon: LineChart,
    tone: "slate",
    category: "pay",
  },

  // Talent / performance
  {
    id: "performance",
    label: "Performance",
    description: "Reviews, goals, and PIPs",
    href: "/hr/performance",
    icon: Target,
    tone: "violet",
    category: "talent",
    featured: true,
  },
  {
    id: "performance-analytics",
    label: "Performance analytics",
    description: "Review cycle insights",
    href: "/hr/performance/analytics",
    icon: LineChart,
    tone: "violet",
    category: "talent",
  },
  {
    id: "goals",
    label: "Goals",
    description: "OKRs and personal targets",
    href: "/hr/goals",
    icon: Target,
    tone: "blue",
    category: "talent",
  },
  {
    id: "kpis",
    label: "KPIs",
    description: "Key performance indicators",
    href: "/hr/kpis",
    icon: Activity,
    tone: "emerald",
    category: "talent",
  },
  {
    id: "feedback",
    label: "Feedback",
    description: "Continuous peer feedback",
    href: "/hr/feedback",
    icon: MessageSquare,
    tone: "sky",
    category: "talent",
  },
  {
    id: "career-development",
    label: "Career development",
    description: "Paths and growth plans",
    href: "/hr/career-development",
    icon: TrendingUp,
    tone: "violet",
    category: "talent",
  },
  {
    id: "certifications",
    label: "Certifications",
    description: "Employee credentials",
    href: "/hr/certifications",
    icon: Award,
    tone: "amber",
    category: "talent",
  },
  {
    id: "background-verification",
    label: "Background verification",
    description: "BGV cases and status",
    href: "/hr/background-verification",
    icon: Shield,
    tone: "slate",
    category: "talent",
  },

  // Learning
  {
    id: "courses",
    label: "Courses",
    description: "Learning catalogue",
    href: "/hr/courses",
    icon: GraduationCap,
    tone: "blue",
    category: "learning",
  },
  {
    id: "training",
    label: "Training",
    description: "Sessions and completions",
    href: "/hr/training",
    icon: BookOpen,
    tone: "emerald",
    category: "learning",
  },
  {
    id: "learning-paths",
    label: "Learning paths",
    description: "Structured curricula",
    href: "/hr/learning-paths",
    icon: GitBranch,
    tone: "violet",
    category: "learning",
  },
  {
    id: "learning-analytics",
    label: "Learning analytics",
    description: "Completion and engagement",
    href: "/hr/learning/analytics",
    icon: LineChart,
    tone: "sky",
    category: "learning",
  },

  // Recruitment
  {
    id: "recruitment",
    label: "Recruitment home",
    description: "Hiring overview",
    href: "/hr/recruitment",
    icon: Briefcase,
    tone: "blue",
    category: "recruitment",
    featured: true,
  },
  {
    id: "jobs",
    label: "Jobs",
    description: "Open roles and postings",
    href: "/hr/recruitment/jobs",
    icon: Briefcase,
    tone: "blue",
    category: "recruitment",
  },
  {
    id: "candidates",
    label: "Candidates",
    description: "Talent database",
    href: "/hr/recruitment/candidates",
    icon: Users,
    tone: "emerald",
    category: "recruitment",
  },
  {
    id: "pipeline",
    label: "Pipeline",
    description: "Kanban hiring stages",
    href: "/hr/recruitment/pipeline",
    icon: GitBranch,
    tone: "violet",
    category: "recruitment",
  },
  {
    id: "interviews",
    label: "Interviews",
    description: "Schedule and scorecards",
    href: "/hr/recruitment/interviews",
    icon: Calendar,
    tone: "amber",
    category: "recruitment",
  },
  {
    id: "offers",
    label: "Offers",
    description: "Offer letters and status",
    href: "/hr/recruitment/offers",
    icon: FileText,
    tone: "emerald",
    category: "recruitment",
  },
  {
    id: "requisitions",
    label: "Requisitions",
    description: "Headcount requests",
    href: "/hr/recruitment/requisitions",
    icon: ClipboardList,
    tone: "slate",
    category: "recruitment",
  },
  {
    id: "recruitment-analytics",
    label: "Recruiting analytics",
    description: "Funnel and time-to-hire",
    href: "/hr/recruitment/analytics",
    icon: LineChart,
    tone: "sky",
    category: "recruitment",
  },
  {
    id: "talent-pools",
    label: "Talent pools",
    description: "Warm pipelines",
    href: "/hr/recruitment/talent-pools",
    icon: UsersRound,
    tone: "violet",
    category: "recruitment",
  },
  {
    id: "referrals",
    label: "Referrals",
    description: "Employee referrals",
    href: "/hr/recruitment/referrals",
    icon: Handshake,
    tone: "amber",
    category: "recruitment",
  },
  {
    id: "recruitment-settings",
    label: "Recruitment settings",
    description: "Flows, templates, SLA",
    href: "/hr/recruitment/settings",
    icon: Settings,
    tone: "slate",
    category: "recruitment",
  },
  {
    id: "recruitment-automations",
    label: "Hiring automations",
    description: "Auto-advance and drip rules",
    href: "/hr/recruitment/automations",
    icon: Sparkles,
    tone: "amber",
    category: "recruitment",
  },
  {
    id: "booking-links",
    label: "Booking links",
    description: "Self-serve interview scheduling",
    href: "/hr/recruitment/booking-links",
    icon: Calendar,
    tone: "sky",
    category: "recruitment",
  },
  {
    id: "candidate-import",
    label: "Import candidates",
    description: "Bulk resume / CSV import",
    href: "/hr/recruitment/candidates/import",
    icon: Share2,
    tone: "emerald",
    category: "recruitment",
  },
  {
    id: "candidate-intake",
    label: "Candidate intake",
    description: "Application intake forms",
    href: "/hr/recruitment/candidates/intake",
    icon: FormInput,
    tone: "blue",
    category: "recruitment",
  },
  {
    id: "diversity-report",
    label: "Diversity report",
    description: "Hiring diversity insights",
    href: "/hr/recruitment/diversity-report",
    icon: LineChart,
    tone: "violet",
    category: "recruitment",
  },
  {
    id: "email-sequences",
    label: "Email sequences",
    description: "Candidate nurture drips",
    href: "/hr/recruitment/email-sequences",
    icon: FormInput,
    tone: "sky",
    category: "recruitment",
  },
  {
    id: "headcount",
    label: "Headcount planning",
    description: "Open seats and budgets",
    href: "/hr/recruitment/headcount",
    icon: Users,
    tone: "slate",
    category: "recruitment",
  },
  {
    id: "hiring-flows",
    label: "Hiring flows",
    description: "Stage pipeline templates",
    href: "/hr/recruitment/hiring-flows",
    icon: GitBranch,
    tone: "violet",
    category: "recruitment",
  },
  {
    id: "recruitment-inbox",
    label: "Recruiting inbox",
    description: "Shared hiring mailbox",
    href: "/hr/recruitment/inbox",
    icon: MessageSquare,
    tone: "blue",
    category: "recruitment",
  },
  {
    id: "internal-jobs",
    label: "Internal jobs",
    description: "Internal mobility board",
    href: "/hr/recruitment/internal-jobs",
    icon: Briefcase,
    tone: "emerald",
    category: "recruitment",
  },
  {
    id: "interviewer-performance",
    label: "Interviewer performance",
    description: "Interviewer quality metrics",
    href: "/hr/recruitment/interviewer-performance",
    icon: Activity,
    tone: "amber",
    category: "recruitment",
  },
  {
    id: "new-job",
    label: "Post a job",
    description: "Create a new job posting",
    href: "/hr/recruitment/jobs/new",
    icon: Plus,
    tone: "blue",
    category: "recruitment",
  },
  {
    id: "offer-templates",
    label: "Offer templates",
    description: "Reusable offer letters",
    href: "/hr/recruitment/offer-templates",
    icon: FileText,
    tone: "slate",
    category: "recruitment",
  },
  {
    id: "question-bank",
    label: "Question bank",
    description: "Interview question library",
    href: "/hr/recruitment/question-bank",
    icon: BookOpen,
    tone: "violet",
    category: "recruitment",
  },
  {
    id: "recruiters",
    label: "Recruiters",
    description: "Recruiter workload",
    href: "/hr/recruitment/recruiters",
    icon: UserCheck,
    tone: "sky",
    category: "recruitment",
  },
  {
    id: "refer",
    label: "Refer someone",
    description: "Share a referral link",
    href: "/hr/recruitment/refer",
    icon: Handshake,
    tone: "amber",
    category: "recruitment",
  },
  {
    id: "recruitment-reports",
    label: "Recruiting reports",
    description: "Hiring reports pack",
    href: "/hr/recruitment/reports",
    icon: LineChart,
    tone: "blue",
    category: "recruitment",
  },
  {
    id: "scorecard-analytics",
    label: "Scorecard analytics",
    description: "Interview score insights",
    href: "/hr/recruitment/scorecard-analytics",
    icon: BarChart3,
    tone: "violet",
    category: "recruitment",
  },
  {
    id: "scorecard-templates",
    label: "Scorecard templates",
    description: "Interview scorecards",
    href: "/hr/recruitment/scorecard-templates",
    icon: ClipboardCheck,
    tone: "slate",
    category: "recruitment",
  },
  {
    id: "recruitment-sla",
    label: "Recruiting SLA",
    description: "Stage SLA targets",
    href: "/hr/recruitment/sla",
    icon: Timer,
    tone: "rose",
    category: "recruitment",
  },
  {
    id: "sla-report",
    label: "SLA report",
    description: "SLA breach analytics",
    href: "/hr/recruitment/sla-report",
    icon: LineChart,
    tone: "rose",
    category: "recruitment",
  },
  {
    id: "vendors",
    label: "Staffing vendors",
    description: "Agencies and partners",
    href: "/hr/recruitment/vendors",
    icon: Building2,
    tone: "slate",
    category: "recruitment",
  },
  {
    id: "document-templates",
    label: "Document templates",
    description: "Offer letters, NDAs, policies",
    href: "/hr/documents/templates",
    icon: FileText,
    tone: "blue",
    category: "ops",
  },
  {
    id: "document-template-new",
    label: "New document template",
    description: "Create an HTML document template",
    href: "/hr/documents/templates/new",
    icon: Plus,
    tone: "sky",
    category: "ops",
  },
  {
    id: "document-editor-new",
    label: "New rich document",
    description: "Compose a new HR document",
    href: "/hr/documents/editor/new",
    icon: FileText,
    tone: "violet",
    category: "ops",
  },
  {
    id: "onboarding-my-tasks",
    label: "My onboarding tasks",
    description: "Tasks assigned to you",
    href: "/hr/onboarding/my-tasks",
    icon: ClipboardCheck,
    tone: "emerald",
    category: "people",
  },
  {
    id: "probation",
    label: "Probation reviews",
    description: "Confirm or extend probation",
    href: "/hr/onboarding/probation",
    icon: UserCheck,
    tone: "amber",
    category: "people",
  },

  // Ops
  {
    id: "assets",
    label: "Assets",
    description: "Company equipment inventory",
    href: "/hr/assets",
    icon: Package,
    tone: "blue",
    category: "ops",
  },
  {
    id: "asset-returns",
    label: "Asset returns",
    description: "Return and clearance tracking",
    href: "/hr/asset-returns",
    icon: Package,
    tone: "amber",
    category: "ops",
  },
  {
    id: "devices",
    label: "Devices",
    description: "Issued devices registry",
    href: "/hr/devices",
    icon: HardDrive,
    tone: "slate",
    category: "ops",
  },
  {
    id: "documents",
    label: "Documents",
    description: "Employee document vault",
    href: "/hr/documents",
    icon: FolderOpen,
    tone: "blue",
    category: "ops",
  },
  {
    id: "document-types",
    label: "Document types",
    description: "Required doc configuration",
    href: "/hr/document-types",
    icon: FileText,
    tone: "slate",
    category: "ops",
  },
  {
    id: "document-review",
    label: "Document review",
    description: "Approve submitted documents",
    href: "/hr/document-review",
    icon: FileCheck,
    tone: "emerald",
    category: "ops",
  },
  {
    id: "helpdesk",
    label: "Helpdesk",
    description: "HR tickets and requests",
    href: "/hr/helpdesk",
    icon: HelpCircle,
    tone: "violet",
    category: "ops",
    featured: true,
  },
  {
    id: "cases",
    label: "Cases",
    description: "Employee relations cases",
    href: "/hr/cases",
    icon: Scale,
    tone: "rose",
    category: "ops",
  },
  {
    id: "travel",
    label: "Travel",
    description: "Travel requests",
    href: "/hr/travel",
    icon: Plane,
    tone: "sky",
    category: "ops",
  },
  {
    id: "travel-approvals",
    label: "Travel approvals",
    description: "Approve travel plans",
    href: "/hr/travel/approvals",
    icon: BadgeCheck,
    tone: "sky",
    category: "ops",
  },
  {
    id: "email-templates",
    label: "Email templates",
    description: "HR communication templates",
    href: "/hr/email-templates",
    icon: FormInput,
    tone: "slate",
    category: "ops",
  },
  {
    id: "emergency",
    label: "Emergency",
    description: "Emergency contacts & protocols",
    href: "/hr/emergency",
    icon: ShieldAlert,
    tone: "rose",
    category: "ops",
  },
  {
    id: "accommodations",
    label: "Accommodations",
    description: "Workplace accommodations",
    href: "/hr/accommodations",
    icon: HeartPulse,
    tone: "emerald",
    category: "ops",
  },

  // Compliance
  {
    id: "compliance",
    label: "Compliance",
    description: "Calendar and obligations",
    href: "/hr/compliance",
    icon: ClipboardCheck,
    tone: "amber",
    category: "compliance",
  },
  {
    id: "safety",
    label: "Safety",
    description: "Incidents and safety logs",
    href: "/hr/safety",
    icon: Shield,
    tone: "rose",
    category: "compliance",
  },
  {
    id: "legal-holds",
    label: "Legal holds",
    description: "Preservation holds",
    href: "/hr/legal-holds",
    icon: Scale,
    tone: "slate",
    category: "compliance",
  },
  {
    id: "labor-relations",
    label: "Labor relations",
    description: "Unions and labor matters",
    href: "/hr/labor-relations",
    icon: Handshake,
    tone: "violet",
    category: "compliance",
  },
  {
    id: "analytics",
    label: "HR analytics",
    description: "People metrics dashboard",
    href: "/hr/analytics",
    icon: LineChart,
    tone: "blue",
    category: "compliance",
    featured: true,
  },
  {
    id: "event-stream",
    label: "Event stream",
    description: "HR audit activity feed",
    href: "/hr/event-stream",
    icon: Activity,
    tone: "slate",
    category: "compliance",
  },
  {
    id: "simulator",
    label: "Simulator",
    description: "What-if people scenarios",
    href: "/hr/simulator",
    icon: Wrench,
    tone: "sky",
    category: "compliance",
  },

  // Settings
  {
    id: "settings",
    label: "HR settings",
    description: "Module configuration hub",
    href: "/hr/settings",
    icon: Settings,
    tone: "slate",
    category: "settings",
    featured: true,
  },
  {
    id: "settings-company",
    label: "Company profile",
    description: "Org identity for HR",
    href: "/hr/settings/company",
    icon: Building2,
    tone: "blue",
    category: "settings",
  },
  {
    id: "settings-policies",
    label: "Policies",
    description: "Policy library",
    href: "/hr/settings/policies",
    icon: FileText,
    tone: "slate",
    category: "settings",
  },
  {
    id: "settings-workflows",
    label: "Workflows",
    description: "Approval workflows",
    href: "/hr/settings/workflows",
    icon: Workflow,
    tone: "violet",
    category: "settings",
  },
  {
    id: "settings-automations",
    label: "Automations",
    description: "Triggered HR actions",
    href: "/hr/settings/automations",
    icon: Sparkles,
    tone: "amber",
    category: "settings",
  },
  {
    id: "settings-templates",
    label: "Templates",
    description: "Document & letter templates",
    href: "/hr/settings/templates",
    icon: FileText,
    tone: "sky",
    category: "settings",
  },
  {
    id: "settings-forms",
    label: "Forms",
    description: "Custom HR forms",
    href: "/hr/settings/forms",
    icon: FormInput,
    tone: "emerald",
    category: "settings",
  },
  {
    id: "settings-custom-fields",
    label: "Custom fields",
    description: "Extend employee data",
    href: "/hr/settings/custom-fields",
    icon: FormInput,
    tone: "blue",
    category: "settings",
  },
  {
    id: "settings-import-export",
    label: "Import / export",
    description: "Bulk data tools",
    href: "/hr/settings/import-export",
    icon: Share2,
    tone: "emerald",
    category: "settings",
  },
  {
    id: "settings-integrations",
    label: "Integrations",
    description: "Connected HR systems",
    href: "/hr/settings/integrations",
    icon: Globe,
    tone: "violet",
    category: "settings",
  },
  {
    id: "settings-versions",
    label: "Versions",
    description: "Config version history",
    href: "/hr/settings/versions",
    icon: GitBranch,
    tone: "slate",
    category: "settings",
  },
  {
    id: "settings-preview",
    label: "Preview",
    description: "Preview employee experience",
    href: "/hr/settings/preview",
    icon: UserCheck,
    tone: "sky",
    category: "settings",
  },
];

export function getModulesByCategory(category: HrModuleCategoryId): HrModuleDef[] {
  return HR_MODULES.filter((m) => m.category === category);
}

export function getFeaturedModules(): HrModuleDef[] {
  return HR_MODULES.filter((m) => m.featured);
}

export function searchModules(query: string): HrModuleDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return HR_MODULES;
  return HR_MODULES.filter(
    (m) =>
      m.label.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.id.includes(q),
  );
}
