"use client";

import { format } from "date-fns";
import { FileText } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { EmptyState } from "@/components/ui/empty-state";
import { Skeleton } from "@/components/ui/skeleton";
import type { LetterRender } from "@/hooks/api/hr/letters";
import { cn } from "@/lib/utils";

const LETTER_TYPE_LABELS: Record<string, string> = {
  offer: "Offer",
  appointment: "Appointment",
  confirmation: "Confirmation",
  promotion: "Promotion",
  transfer: "Transfer",
  salary_revision: "Salary Revision",
  warning: "Warning",
  experience: "Experience",
  relieving: "Relieving",
  termination: "Termination",
};

function LetterTypeBadge({ type }: { type: string | null }) {
  if (!type) return null;
  return (
    <span className="inline-flex items-center text-[10px] font-semibold px-2 py-0.5 rounded-full border bg-blue-50 border-blue-200 text-blue-700 dark:bg-blue-950/40 dark:border-blue-800 dark:text-blue-300">
      {LETTER_TYPE_LABELS[type] ?? type}
    </span>
  );
}

interface LettersHistoryTableProps {
  letters: LetterRender[];
  isLoading: boolean;
  className?: string;
}

export function LettersHistoryTable({ letters, isLoading, className }: LettersHistoryTableProps) {
  if (isLoading) {
    return (
      <div className={cn("rounded-2xl border border-border bg-card shadow-sm overflow-hidden", className)}>
        <div className="space-y-0 divide-y divide-border">
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="p-3.5 flex gap-3 items-center">
              <Skeleton className="h-7 w-7 rounded-lg" />
              <div className="flex-1 space-y-1.5">
                <Skeleton className="h-3.5 w-40" />
                <Skeleton className="h-3 w-24" />
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (letters.length === 0) {
    return (
      <EmptyState
        illustration={<FileText className="h-8 w-8 text-muted-foreground" />}
        title="No letters generated"
        description="Generated letters will appear here."
        compact
      />
    );
  }

  return (
    <div className={cn("rounded-2xl border border-border bg-card shadow-sm overflow-hidden", className)}>
      <ScrollArea className="w-full" type="auto">
        <div className="min-w-[520px]">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/40 hover:bg-muted/40">
                <TableHead className="font-semibold text-foreground/80">Template</TableHead>
                <TableHead className="font-semibold text-foreground/80">Type</TableHead>
                <TableHead className="font-semibold text-foreground/80">Generated By</TableHead>
                <TableHead className="font-semibold text-foreground/80">Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {letters.map((letter) => (
                <TableRow key={letter.id} className="transition-colors duration-200">
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <div className="h-7 w-7 rounded-lg bg-blue-50 dark:bg-blue-950/40 flex items-center justify-center shrink-0">
                        <FileText className="h-3.5 w-3.5 text-blue-600 dark:text-blue-400" />
                      </div>
                      <span className="text-sm font-medium text-foreground">{letter.templateName}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <LetterTypeBadge type={letter.templateLetterType} />
                  </TableCell>
                  <TableCell className="text-sm text-muted-foreground">
                    {letter.rendererName ?? "—"}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground">
                    {letter.createdAt ? format(new Date(letter.createdAt), "MMM d, yyyy") : "—"}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </ScrollArea>
    </div>
  );
}
