"use client";

import { format } from "date-fns";
import { FileText } from "lucide-react";
import { EmptyState } from "@/components/ui/empty-state";
import type { LetterRender } from "@/hooks/api/hr/letters";
import { cn } from "@/lib/utils";
import { DataTable, type DataTableColumn } from "@/components/ui/data-table";

const LETTER_TYPE_LABELS: Record<string, string> = {
  offer: "Offer",
  appointment: "Appointment",
  confirmation: "Confirmation",
  promotion: "Promotion",
  transfer: "Transfer",
  salary_revision: "Salary Revision",
  warning: "Warning",
  experience: "Experience",
  relieving: "Relieving",
  termination: "Termination",
};

function LetterTypeBadge({ type }: { type: string | null }) {
  if (!type) return null;
  return (
    <span className="inline-flex items-center text-[10px] font-semibold px-2 py-0.5 rounded-full border bg-blue-100 border-blue-200 text-blue-700 dark:bg-blue-500/10 dark:border-blue-500/30 dark:text-blue-300">
      {LETTER_TYPE_LABELS[type] ?? type}
    </span>
  );
}

interface LettersHistoryTableProps {
  letters: LetterRender[];
  isLoading: boolean;
  className?: string;
}

const columns: DataTableColumn<LetterRender>[] = [
  {
    key: "template",
    header: "Template",
    cell: (letter) => (
      <div className="flex items-center gap-2">
        <div className="h-7 w-7 rounded-lg bg-blue-100 dark:bg-blue-500/10 flex items-center justify-center shrink-0">
          <FileText className="h-3.5 w-3.5 text-blue-600 dark:text-blue-400" />
        </div>
        <span className="text-sm font-medium text-foreground">{letter.templateName}</span>
      </div>
    ),
  },
  {
    key: "type",
    header: "Type",
    cell: (letter) => <LetterTypeBadge type={letter.templateLetterType} />,
  },
  {
    key: "generatedBy",
    header: "Generated By",
    className: "text-sm text-muted-foreground",
    cell: (letter) => <>{letter.rendererName ?? "—"}</>,
  },
  {
    key: "date",
    header: "Date",
    className: "text-xs text-muted-foreground",
    cell: (letter) => (
      <>{letter.createdAt ? format(new Date(letter.createdAt), "MMM d, yyyy") : "—"}</>
    ),
  },
];

export function LettersHistoryTable({ letters, isLoading, className }: LettersHistoryTableProps) {
  const emptyState = (
    <EmptyState
      illustration={<FileText className="h-8 w-8 text-muted-foreground" />}
      title="No letters generated"
      description="Generated letters will appear here."
      compact
    />
  );

  return (
    <DataTable
      data={letters}
      columns={columns}
      getRowKey={(letter) => letter.id}
      isLoading={isLoading}
      emptyState={emptyState}
      minWidth="520px"
      className={cn("rounded-2xl bg-card shadow-sm", className)}
    />
  );
}
