"use client";

import { format } from "date-fns";
import { FileText } from "lucide-react";
import { EmptyState } from "@/components/ui/empty-state";
import type { LetterRender } from "@/hooks/api/hr/letters";
import { cn } from "@/lib/utils";
import { DataTable, type DataTableColumn } from "@/components/ui/data-table";
import { TruncatedText } from "@/components/ui/truncated-text";

const LETTER_TYPE_LABELS: Record<string, string> = {
  offer: "Offer",
  appointment: "Appointment",
  confirmation: "Confirmation",
  promotion: "Promotion",
  transfer: "Transfer",
  salary_revision: "Salary Revision",
  warning: "Warning",
  experience: "Experience",
  relieving: "Relieving",
  termination: "Termination",
};

function LetterTypeBadge({ type }: { type: string | null }) {
  if (!type) return null;
  return (
    <span className="inline-flex items-center text-micro font-semibold px-2 py-0.5 rounded-full border bg-primary/10 border-primary/30 text-foreground">
      {LETTER_TYPE_LABELS[type] ?? type}
    </span>
  );
}

interface LettersHistoryTableProps {
  letters: LetterRender[];
  isLoading: boolean;
  className?: string;
}

const columns: DataTableColumn<LetterRender>[] = [
  {
    key: "template",
    header: "Template",
    cell: (letter) => (
      <div className="flex items-center gap-2 min-w-0">
        <div className="w-7 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
          <FileText className="h-3.5 w-3.5 text-primary" />
        </div>
        <TruncatedText text={letter.templateName ?? ""} className="text-sm font-medium text-foreground min-w-0 flex-1" />
      </div>
    ),
  },
  {
    key: "type",
    header: "Type",
    cell: (letter) => <LetterTypeBadge type={letter.templateLetterType} />,
  },
  {
    key: "generatedBy",
    header: "Generated By",
    className: "text-sm text-muted-foreground",
    cell: (letter) => (
      letter.rendererName
        ? <TruncatedText text={letter.rendererName} className="text-sm text-muted-foreground" />
        : <>{"—"}</>
    ),
  },
  {
    key: "date",
    header: "Date",
    className: "text-xs text-muted-foreground",
    cell: (letter) => (
      <>{letter.createdAt ? format(new Date(letter.createdAt), "MMM d, yyyy") : "—"}</>
    ),
  },
];

export function LettersHistoryTable({ letters, isLoading, className }: LettersHistoryTableProps) {
  const emptyState = (
    <EmptyState
      illustrationPreset="documents"
      title="No letters generated"
      description="Generated letters will appear here."
      compact
    />
  );

  return (
    <DataTable
      data={letters}
      columns={columns}
      getRowKey={(letter) => letter.id}
      isLoading={isLoading}
      emptyState={emptyState}
      minWidth="520px"
      className={cn("rounded-2xl bg-card shadow-sm", className)}
    />
  );
}
