-- Final NOT NULL alignment: columns where the Drizzle schema declares
-- .notNull() but the DB still allows NULL. All have defaults, so we
-- backfill any existing NULLs first.

------------------------------------------------------------------------------
-- Backfill NULL values to column defaults
------------------------------------------------------------------------------
UPDATE ab_tests SET audience_size = 0           WHERE audience_size IS NULL;
UPDATE ab_tests SET split_percent = 50          WHERE split_percent IS NULL;
UPDATE ab_tests SET status = 'draft'            WHERE status IS NULL;
UPDATE ab_tests SET variant_a_clicks = 0        WHERE variant_a_clicks IS NULL;
UPDATE ab_tests SET variant_a_opens = 0         WHERE variant_a_opens IS NULL;
UPDATE ab_tests SET variant_a_sent = 0          WHERE variant_a_sent IS NULL;
UPDATE ab_tests SET variant_b_clicks = 0        WHERE variant_b_clicks IS NULL;
UPDATE ab_tests SET variant_b_opens = 0         WHERE variant_b_opens IS NULL;
UPDATE ab_tests SET variant_b_sent = 0          WHERE variant_b_sent IS NULL;
UPDATE attendance SET auto_checked_out = false  WHERE auto_checked_out IS NULL;
UPDATE attendance SET is_overtime = false       WHERE is_overtime IS NULL;
UPDATE attendance SET status = 'PRESENT'        WHERE status IS NULL;
UPDATE calendar_events SET all_day = false              WHERE all_day IS NULL;
UPDATE calendar_events SET is_recurring = false         WHERE is_recurring IS NULL;
UPDATE calendar_events SET reminder_15min_sent = false  WHERE reminder_15min_sent IS NULL;
UPDATE clients SET health_score = 50            WHERE health_score IS NULL;
UPDATE clients SET health_status = 'healthy'    WHERE health_status IS NULL;
UPDATE content_calendar_items SET status = 'idea' WHERE status IS NULL;
UPDATE crm_campaigns SET leads = 0              WHERE leads IS NULL;
UPDATE crm_content SET leads = 0                WHERE leads IS NULL;
UPDATE crm_content SET views = 0                WHERE views IS NULL;
UPDATE crm_deals SET probability = 0            WHERE probability IS NULL;
UPDATE crm_monthly_metrics SET mqls = 0         WHERE mqls IS NULL;
UPDATE crm_monthly_metrics SET ticket_volume = 0 WHERE ticket_volume IS NULL;
UPDATE deals SET probability = 0                WHERE probability IS NULL;
UPDATE department_members SET role = 'member'   WHERE role IS NULL;
UPDATE documents SET expiry_reminder_sent = false WHERE expiry_reminder_sent IS NULL;
UPDATE documents SET is_active = true           WHERE is_active IS NULL;
UPDATE documents SET is_public = false          WHERE is_public IS NULL;
UPDATE documents SET version = 1                WHERE version IS NULL;
UPDATE expense_categories SET budget_period = 'MONTHLY' WHERE budget_period IS NULL;
UPDATE expense_categories SET is_active = true  WHERE is_active IS NULL;
UPDATE expenses SET currency = 'INR'            WHERE currency IS NULL;
UPDATE goals SET progress = 0                   WHERE progress IS NULL;
UPDATE goals SET status = 'IN_PROGRESS'         WHERE status IS NULL;
UPDATE goals SET type = 'OKR'                   WHERE type IS NULL;
UPDATE key_results SET progress = 0             WHERE progress IS NULL;
UPDATE landing_pages SET is_active = true       WHERE is_active IS NULL;
UPDATE landing_pages SET is_published = false   WHERE is_published IS NULL;
UPDATE leads SET score = 0                      WHERE score IS NULL;
UPDATE leave_requests SET priority = 'MEDIUM'   WHERE priority IS NULL;
UPDATE leave_types SET carry_forward = false    WHERE carry_forward IS NULL;
UPDATE notification_preferences SET email_enabled = true   WHERE email_enabled IS NULL;
UPDATE notification_preferences SET in_app_enabled = true  WHERE in_app_enabled IS NULL;
UPDATE notification_preferences SET push_enabled = true    WHERE push_enabled IS NULL;
UPDATE notification_preferences SET sms_enabled = false    WHERE sms_enabled IS NULL;
UPDATE notifications SET channel = 'in_app'     WHERE channel IS NULL;
UPDATE notifications SET is_read = false        WHERE is_read IS NULL;
UPDATE notifications SET sound = false          WHERE sound IS NULL;
UPDATE project_members SET role = 'CONTRIBUTOR' WHERE role IS NULL;
UPDATE project_template_tickets SET priority = 'MEDIUM' WHERE priority IS NULL;
UPDATE project_template_tickets SET type = 'TASK' WHERE type IS NULL;
UPDATE project_templates SET category = 'GENERAL' WHERE category IS NULL;
UPDATE reports SET is_scheduled = false         WHERE is_scheduled IS NULL;
UPDATE salary_loans SET paid_emis = 0           WHERE paid_emis IS NULL;
UPDATE salary_structures SET is_active = true   WHERE is_active IS NULL;
UPDATE social_metrics SET clicks = 0            WHERE clicks IS NULL;
UPDATE social_metrics SET comments = 0          WHERE comments IS NULL;
UPDATE social_metrics SET engagements = 0       WHERE engagements IS NULL;
UPDATE social_metrics SET followers = 0         WHERE followers IS NULL;
UPDATE social_metrics SET impressions = 0       WHERE impressions IS NULL;
UPDATE social_metrics SET reach = 0             WHERE reach IS NULL;
UPDATE social_metrics SET shares = 0            WHERE shares IS NULL;
UPDATE sprints SET status = 'PLANNED'           WHERE status IS NULL;
UPDATE targets SET period = 'daily'             WHERE period IS NULL;
UPDATE ticket_labels SET color = '#3B82F6'      WHERE color IS NULL;
UPDATE tickets SET completion_percentage = 0    WHERE completion_percentage IS NULL;
UPDATE tickets SET "order" = 0                  WHERE "order" IS NULL;
UPDATE timesheets SET is_billable = false       WHERE is_billable IS NULL;
UPDATE timesheets SET status = 'PENDING'        WHERE status IS NULL;
UPDATE users SET is_password_change_required = false WHERE is_password_change_required IS NULL;
UPDATE users SET is_profile_picture_required = false WHERE is_profile_picture_required IS NULL;
UPDATE users SET whatsapp_same_as_phone = true  WHERE whatsapp_same_as_phone IS NULL;

------------------------------------------------------------------------------
-- Set NOT NULL on columns
------------------------------------------------------------------------------
ALTER TABLE ab_tests ALTER COLUMN audience_size SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN split_percent SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN status SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN variant_a_clicks SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN variant_a_opens SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN variant_a_sent SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN variant_b_clicks SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN variant_b_opens SET NOT NULL;
ALTER TABLE ab_tests ALTER COLUMN variant_b_sent SET NOT NULL;
ALTER TABLE attendance ALTER COLUMN auto_checked_out SET NOT NULL;
ALTER TABLE attendance ALTER COLUMN is_overtime SET NOT NULL;
ALTER TABLE attendance ALTER COLUMN status SET NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN all_day SET NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN is_recurring SET NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN reminder_15min_sent SET NOT NULL;
ALTER TABLE clients ALTER COLUMN health_score SET NOT NULL;
ALTER TABLE clients ALTER COLUMN health_status SET NOT NULL;
ALTER TABLE content_calendar_items ALTER COLUMN status SET NOT NULL;
ALTER TABLE crm_campaigns ALTER COLUMN leads SET NOT NULL;
ALTER TABLE crm_content ALTER COLUMN leads SET NOT NULL;
ALTER TABLE crm_content ALTER COLUMN views SET NOT NULL;
ALTER TABLE crm_deals ALTER COLUMN probability SET NOT NULL;
ALTER TABLE crm_monthly_metrics ALTER COLUMN mqls SET NOT NULL;
ALTER TABLE crm_monthly_metrics ALTER COLUMN ticket_volume SET NOT NULL;
ALTER TABLE deals ALTER COLUMN probability SET NOT NULL;
ALTER TABLE department_members ALTER COLUMN role SET NOT NULL;
ALTER TABLE documents ALTER COLUMN expiry_reminder_sent SET NOT NULL;
ALTER TABLE documents ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE documents ALTER COLUMN is_public SET NOT NULL;
ALTER TABLE documents ALTER COLUMN version SET NOT NULL;
ALTER TABLE expense_categories ALTER COLUMN budget_period SET NOT NULL;
ALTER TABLE expense_categories ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE expenses ALTER COLUMN currency SET NOT NULL;
ALTER TABLE goals ALTER COLUMN progress SET NOT NULL;
ALTER TABLE goals ALTER COLUMN status SET NOT NULL;
ALTER TABLE goals ALTER COLUMN type SET NOT NULL;
ALTER TABLE key_results ALTER COLUMN progress SET NOT NULL;
ALTER TABLE landing_pages ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE landing_pages ALTER COLUMN is_published SET NOT NULL;
ALTER TABLE leads ALTER COLUMN score SET NOT NULL;
ALTER TABLE leave_requests ALTER COLUMN priority SET NOT NULL;
ALTER TABLE leave_types ALTER COLUMN carry_forward SET NOT NULL;
ALTER TABLE notification_preferences ALTER COLUMN email_enabled SET NOT NULL;
ALTER TABLE notification_preferences ALTER COLUMN in_app_enabled SET NOT NULL;
ALTER TABLE notification_preferences ALTER COLUMN push_enabled SET NOT NULL;
ALTER TABLE notification_preferences ALTER COLUMN sms_enabled SET NOT NULL;
ALTER TABLE notifications ALTER COLUMN channel SET NOT NULL;
ALTER TABLE notifications ALTER COLUMN is_read SET NOT NULL;
ALTER TABLE notifications ALTER COLUMN sound SET NOT NULL;
ALTER TABLE project_members ALTER COLUMN role SET NOT NULL;
ALTER TABLE project_template_tickets ALTER COLUMN priority SET NOT NULL;
ALTER TABLE project_template_tickets ALTER COLUMN type SET NOT NULL;
ALTER TABLE project_templates ALTER COLUMN category SET NOT NULL;
ALTER TABLE reports ALTER COLUMN is_scheduled SET NOT NULL;
ALTER TABLE salary_loans ALTER COLUMN paid_emis SET NOT NULL;
ALTER TABLE salary_structures ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE social_metrics ALTER COLUMN clicks SET NOT NULL;
ALTER TABLE social_metrics ALTER COLUMN comments SET NOT NULL;
ALTER TABLE social_metrics ALTER COLUMN engagements SET NOT NULL;
ALTER TABLE social_metrics ALTER COLUMN followers SET NOT NULL;
ALTER TABLE social_metrics ALTER COLUMN impressions SET NOT NULL;
ALTER TABLE social_metrics ALTER COLUMN reach SET NOT NULL;
ALTER TABLE social_metrics ALTER COLUMN shares SET NOT NULL;
ALTER TABLE sprints ALTER COLUMN status SET NOT NULL;
ALTER TABLE targets ALTER COLUMN period SET NOT NULL;
ALTER TABLE ticket_labels ALTER COLUMN color SET NOT NULL;
ALTER TABLE tickets ALTER COLUMN completion_percentage SET NOT NULL;
ALTER TABLE tickets ALTER COLUMN "order" SET NOT NULL;
ALTER TABLE timesheets ALTER COLUMN is_billable SET NOT NULL;
ALTER TABLE timesheets ALTER COLUMN status SET NOT NULL;
ALTER TABLE users ALTER COLUMN is_password_change_required SET NOT NULL;
ALTER TABLE users ALTER COLUMN is_profile_picture_required SET NOT NULL;
ALTER TABLE users ALTER COLUMN whatsapp_same_as_phone SET NOT NULL;
